#include "protheus.ch"

#define		POS_ITEM_DOC		01
#define		POS_COD_DOC			02
#define		POS_DESC_DOC		03
#define		POS_QUANT_DOC		04
#define		POS_PESO_DOC		05
#define		POS_LOTE_DOC		06
#define		POS_ITEM_AJUSTE		01
#define		POS_COD_AJUSTE		02
#define		POS_DESC_AJUSTE		03
#define		POS_LOCAL_AJUSTE	04
#define		POS_QUANT_AJUSTE	05
#define		POS_VLRUNIT_AJUSTE	06
#define		POS_PESO_AJUSTE		07
#define		POS_LOTE_AJUSTE		08
#define 	POS_VALID_AJUSTE	09
#define		POS_LOTEFOR_AJUSTE	10
#define		POS_OBS_AJUSTE		11
#define		POS_DELELTE_AJUSTE	12

#define 	OPERACAO_INCLUSAO	3
#define 	OPERACAO_ALTERACAO	4
#define		OPERACAO_EXCLUSAO	5
#define		OPERACAO_ESTORNO	6

namespace compras.entrada.refaturamento

/*/ {Protheus.doc} GerarRefaturamento

Rotina de Refaturamento

@type function
@author Elcilei Lopes - DsmSolutions
@since 27/11/2025
@version P12
@database ORACLE
/*/
User Function GerarRefaturamento()
	Private cTitulo             := ""   	as character
	Private cCodFornecedor      := ""   	as character
	Private cLojFornecedor      := ""   	as character
	Private cOpcao				:= "I"   	as character

	Private cNumProcesso 		:= ""   	as character
	Private cNotaFiscal			:= ""   	as character
	Private cSerieNota			:= ""   	as character
	Private dDtEmissao			:= cTod("") as date
	Private dDtConfirmar		:= cTod("") as date
	Private cStatusCabecalho	:= ""   	as character
	Private cPedidoVenda		:= ""   	as character

	Private aLogErro			:= {}		as array

	Private oTelaRefaturamento  := Nil  	as object
	Private oLayerRefaturamento := Nil		as object
	Private oGridItensDocumento := Nil		as object
	Private oGridAjusteItens    := Nil		as object
	Private oPanelCabecalho		:= Nil		as object
	Private oPnlTop				:= Nil		as object
	Private oPnlBotoes			:= Nil		as object

	Private aHeaderItens        := {}   	as array
	Private aHeaderAjuste       := {}   	as array
	Private aColsItens          := {}   	as array
	Private aColsAjuste         := {}   	as array

	Private cAliasSD1			:= ""		as character
	Private oTabelaTmpSd1		:= Nil		as object
	Private aColunas 			:= {}		as array

	Private cAliasTmpAjuste		:= ""		as character
	Private oTabelaTmpAjuste	:= Nil		as object

	cTitulo 		:= "Refaturamento Centrasa"
	dDtEmissao		:= dDatabase
	cNotaFiscal    	:= SF1->F1_DOC
	cSerieNota		:= SF1->F1_SERIE
	cCodFornecedor  := SF1->F1_FORNECE
	cLojFornecedor  := SF1->F1_LOJA

	If !podeExecutar()
		Return
	Endif

	SetKey(VK_F4, { || sadosPorLote()  } )

	criarTabelaTmpAjuste()

	gerarCabechalho()

	If !( carregaItensNotaGrid() )
		FWAlertWarning("Nenhum item encontradado para refaturamento.",cTitulo)
		Return
	Endif

	montaTelaRefaturamento()

Return

/*/
	Carrega dados do cabecalho
/*/
Static Function gerarCabechalho()

	dbSelectArea("SZ7")
	SZ7->(dbSetOrder(2))

	If ( SZ7->(dbSeek(FWxFilial("SZ7")+cNotaFiscal+cSerieNota+cCodFornecedor+cLojFornecedor)))
		cNumProcesso := SZ7->Z7_NUM
		dDtEmissao	 := SZ7->Z7_EMISSAO
		cPedidoVenda := SZ7->Z7_NUMPV

		If ( SZ7->Z7_STATUS == "1" )
			cStatusCabecalho := "Cadastrado"
			dDtConfirmar	 := cTod("")
			cOpcao			 := "I"
		Else
			cStatusCabecalho := "Confirmado"
			dDtConfirmar	 := SZ7->Z7_DTCONFI
			cOpcao			 := "V"
		Endif
	Else
		cNumProcesso 	 := GetSxeNum("SZ7","Z7_NUM")
		dDtEmissao	 	 := dDatabase
		cStatusCabecalho := ""

	EndIf
Return

/*/
	Carrega aCols Itens com itens da nota
/*/
Static Function carregaItensNotaGrid()
	Local lRet      	:= .F.  as logical
	Local cFiltro   	:= ""   as character
	Local cDescricao	:= ""	as character
	Local aFields 		:= {}	as array
	Local aCamposSX3	:= {}	as array
	Local cTesRefatura	:= ""	as character

	cAliasSD1		:= GetNextAlias()
	oTabelaTmpSd1	:= FWTemporaryTable():New(cAliasSD1)
	cTesRefatura	:= GetNewPar("FS_TESREFT","001")

	aHeaderItens:= {}

	aCamposSX3 := FWTamSX3("D1_ITEM")
	aAdd( aFields,	{"FS_ITEM"	    , aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("D1_COD")
	aAdd( aFields,	{"FS_PRODUTO"   , aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("B1_DESC")
	aAdd( aFields,	{"FS_DESCRI"	, aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("D1_LOCAL")
	aAdd( aFields,	{"FS_LOCAL"	, aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("D1_QUANT")
	aAdd( aFields,	{"FS_QUANT"	    , aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("D1_VUNIT")
	aAdd( aFields,	{"FS_VUNIT"	    , aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("D1_PESO")
	aAdd( aFields,	{"FS_PESO"	    , aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("D1_LOTECTL")
	aAdd( aFields,	{"FS_LOTECTL"	    , aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("D1_DTVALID")
	aAdd( aFields,	{"FS_DTVALID"	    , aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("D1_LOTEFOR")
	aAdd( aFields,	{"FS_LOTEFOR"	    , aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("D1_NUMSEQ")
	aAdd( aFields,	{"FS_NUMSEQ"	    , aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("D1_DOC")
	aAdd( aFields,	{"FS_DOC"	    , aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("D1_SERIE")
	aAdd( aFields,	{"FS_SERIE"	    , aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("D1_TES")
	aAdd( aFields,	{"FS_TES"	    , aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	oTabelaTmpSd1:SetFields( aFields )
	oTabelaTmpSd1:AddIndex("1", {"FS_ITEM","FS_PRODUTO"} )
	oTabelaTmpSd1:AddIndex("2", {"FS_PRODUTO"} )
	oTabelaTmpSd1:Create()

	montaHeadNota()

	aColsItens  := {}
	cFiltro     := cNotaFiscal+cSerieNota+cCodFornecedor+cLojFornecedor

	dbSelectArea("SB1")
	SB1->(dbSetOrder(1))

	dbSelectArea("SD1")
	SD1->(dbSetOrder(1))
	If ( SD1->(dbSeek(FWxFilial("SD1")+cFiltro)))
		While !( SD1->(eof())) .And. ( SD1->D1_FILIAL == FWxFilial("SD1") ) .And. ;
				( SD1->D1_DOC+SD1->D1_SERIE+SD1->D1_FORNECE+SD1->D1_LOJA == cFiltro )

			If ( SD1->D1_TES $ cTesRefatura) .And. ( SD1->D1_ZPESO > 0 )

				cDescricao := ""
				If SB1->(dbSeek(FWxFilial("SB1")+SD1->D1_COD))
					cDescricao := SB1->B1_DESC
				Endif

				RecLock( cAliasSD1, .T.)

				(cAliasSD1)->FS_ITEM 	:= SD1->D1_ITEM
				(cAliasSD1)->FS_PRODUTO	:= SD1->D1_COD
				(cAliasSD1)->FS_DESCRI	:= cDescricao
				(cAliasSD1)->FS_LOCAL	:= SD1->D1_LOCAL
				(cAliasSD1)->FS_QUANT	:= SD1->D1_QUANT
				(cAliasSD1)->FS_VUNIT	:= SD1->D1_VUNIT
				(cAliasSD1)->FS_PESO	:= SD1->D1_ZPESO
				(cAliasSD1)->FS_LOTECTL	:= SD1->D1_LOTECTL
				(cAliasSD1)->FS_DTVALID	:= SD1->D1_DTVALID
				(cAliasSD1)->FS_LOTEFOR	:= SD1->D1_LOTEFOR
				(cAliasSD1)->FS_NUMSEQ	:= SD1->D1_NUMSEQ
				(cAliasSD1)->FS_DOC		:= SD1->D1_DOC
				(cAliasSD1)->FS_SERIE	:= SD1->D1_SERIE
				(cAliasSD1)->FS_TES		:= SD1->D1_TES

				(cAliasSD1)->(MsUnlock())

				lRet := .T.

			EndIf

			SD1->(dbSkip())
		EndDo
	Else
		FWAlertWarning("Item do documento não encontrado",cTitulo)
	Endif

Return lRet

/*/
	Monta head da grid do itens da nota
/*/
Static Function montaHeadNota()
	Local aCamposSX3	:= {}	as array
	Local nRecord		:= 0	as numeric
	Local oColumn		:= Nil	as object

	aHeaderItens := {}

	aCamposSX3 := FWTamSX3("D1_ITEM")
	aAdd( aHeaderItens,	{"FS_ITEM"	    ,"Item Doc"		, aCamposSX3[3]	,aCamposSX3[1]	, aCamposSX3[2]	,""}	)

	aCamposSX3 := FWTamSX3("D1_COD")
	aAdd( aHeaderItens,	{"FS_PRODUTO"   ,"Produto"	    , aCamposSX3[3]	,aCamposSX3[1]	, aCamposSX3[2]	,""}	)

	aCamposSX3 := FWTamSX3("B1_DESC")
	aAdd( aHeaderItens,	{"FS_DESCRI"	,"Descrição"    , aCamposSX3[3]	,aCamposSX3[1]	, aCamposSX3[2]	,""}	)

	aCamposSX3 := FWTamSX3("D1_LOCAL")
	aAdd( aHeaderItens,	{"FS_LOCAL"		,"Armazém"    , aCamposSX3[3]	,aCamposSX3[1]	, aCamposSX3[2]	,""}	)

	aCamposSX3 := FWTamSX3("D1_QUANT")
	aAdd( aHeaderItens,	{"FS_QUANT"	    ,"Quantidade"   , aCamposSX3[3]	,aCamposSX3[1]	, aCamposSX3[2]	,X3Picture("D1_QUANT")}	)

	aCamposSX3 := FWTamSX3("D1_VUNIT")
	aAdd( aHeaderItens,	{"FS_VUNIT"	    ,"Vlr.Unitario"   , aCamposSX3[3]	,aCamposSX3[1]	, aCamposSX3[2]	,X3Picture("D1_VUNIT")}	)

	aCamposSX3 := FWTamSX3("D1_PESO")
	aAdd( aHeaderItens,	{"FS_PESO"	    ,"Peso"         , aCamposSX3[3]	,aCamposSX3[1]	, aCamposSX3[2]	,X3Picture("D1_PESO")}	)

	aCamposSX3 := FWTamSX3("D1_LOTECTL")
	aAdd( aHeaderItens,	{"FS_LOTECTL"	    ,"Lote"         ,aCamposSX3[3]	,aCamposSX3[1]	, aCamposSX3[2]	,""}	)

	aCamposSX3 := FWTamSX3("D1_DTVALID")
	aAdd( aHeaderItens,	{"FS_DTVALID"	    ,"Validade"         ,aCamposSX3[3]	,aCamposSX3[1]	, aCamposSX3[2]	,""}	)

	aCamposSX3 := FWTamSX3("D1_LOTEFOR")
	aAdd( aHeaderItens,	{"FS_LOTEFOR"    ,"Lote Fornec.",aCamposSX3[3]	,aCamposSX3[1]	, aCamposSX3[2]	,""}	)

	aCamposSX3 := FWTamSX3("D1_NUMSEQ")
	aAdd( aHeaderItens,	{"FS_NUMSEQ"    ,"Num.Sequenc.",aCamposSX3[3]	,aCamposSX3[1]	, aCamposSX3[2]	,""}	)

	aCamposSX3 := FWTamSX3("D1_DOC")
	aAdd( aHeaderItens,	{"FS_DOC"    ,"No.Documento",aCamposSX3[3]	,aCamposSX3[1]	, aCamposSX3[2]	,""}	)

	aCamposSX3 := FWTamSX3("D1_SERIE")
	aAdd( aHeaderItens,	{"FS_SERIE"    ,"Serie",aCamposSX3[3]	,aCamposSX3[1]	, aCamposSX3[2]	,""}	)

	aCamposSX3 := FWTamSX3("D1_TES")
	aAdd( aHeaderItens,	{"FS_TES"    ,"Tes",aCamposSX3[3]	,aCamposSX3[1]	, aCamposSX3[2]	,""}	)

	For nRecord := 1 To Len(aHeaderItens)
		oColumn := FWBrwColumn():New()
		oColumn:SetData(&("{|| " + cAliasSD1 + "->" + aHeaderItens[nRecord][1] +"}"))
		oColumn:SetTitle(aHeaderItens[nRecord][2])
		oColumn:SetType(aHeaderItens[nRecord][3])
		oColumn:SetSize(aHeaderItens[nRecord][4])
		oColumn:SetDecimal(aHeaderItens[nRecord][5])
		oColumn:SetPicture(aHeaderItens[nRecord][6])
		aAdd(aColunas, oColumn)
	Next

Return

/*/
	Monta tela do refaturamento
/*/
Static Function montaTelaRefaturamento()
	Local aSize	        := {} 	    as array
	Local oScrolTela	:= Nil		as object

	aSize               := FWGetDialogSize( oMainWnd )

	oLayerRefaturamento := FWLayer():New()

	DEFINE MSDIALOG oTelaRefaturamento TITLE cTitulo FROM aSize[1], aSize[2] To aSize[3], aSize[4] PIXEL
	oTelaRefaturamento:lMaximized := .T.

	oScrolTela := TScrollBox():New(oTelaRefaturamento,01,01,92,260,.F.,.F.,.F.)
	oScrolTela:Align	:= CONTROL_ALIGN_ALLCLIENT

	oPnlTop    := TPanel():New( 135,000,"",oScrolTela,,.F.,.F.,,,516,023,.F.,.F. )
	oPnlTop:Align	:= CONTROL_ALIGN_TOP

	oPnlBotoes := TPanel():New( 001,176,"",oPnlTop,,.F.,.F.,,,236,020,.F.,.F. )
	oPnlBotoes:Align:= CONTROL_ALIGN_RIGHT

	oPanelCabecalho	:= TPanel():New( 000,000,"",oScrolTela,,.F.,.F.,,,536,036,.F.,.F. )
	oPanelCabecalho:Align	:= CONTROL_ALIGN_TOP

	oLayerRefaturamento:init(oScrolTela,.F.)
	oLayerRefaturamento:AddLine("SUPERIOR"      , 040, .T.)
	oLayerRefaturamento:AddLine("INFERIOR"	    , 050, .T.)
	oLayerRefaturamento:AddCollumn("LY_SUPERIOR"	, 100, .T., "SUPERIOR")
	oLayerRefaturamento:AddCollumn("LY_INFERIOR"	, 100, .T., "INFERIOR")
	oLayerRefaturamento:AddWindow("LY_SUPERIOR"	    , "ITM_PROD"		, "Itens Produzidos"			, 100, .F., .F., , "SUPERIOR" , )
	oLayerRefaturamento:AddWindow("LY_INFERIOR"	    , "ITM_TRANS"		, "Transformações de produto"   , 100, .F., .F., , "INFERIOR" , )

	criarCabecalho()
	criarGerids()
	alimentaTabelaAjuste()

	ACTIVATE MSDIALOG oTelaRefaturamento CENTERED

	(cAliasSD1)->(dbCloseArea())
	(cAliasTmpAjuste)->(dbCloseArea())

Return

/*/
	Criar cabecalho da tela
/*/
Static Function criarCabecalho()
	Local oFont01			:= Nil  as object
	Local oBtnExcluir		:= Nil  as object
	Local oBtnConfirmar		:= Nil  as object
	Local oBtnEstornar		:= Nil  as object
	Local oBtnSalvar		:= Nil  as object
	Local oBtnCancelar		:= Nil  as object
	Local olblProcesso		:= Nil  as object
	Local olblNotafiscal	:= Nil  as object
	Local olblSerieNota		:= Nil  as object
	Local olblDtEmisso		:= Nil  as object
	Local olblDtConfirma	:= Nil  as object
	Local olblStatus		:= Nil  as object
	Local olblPEdidoVemda	:= Nil  as object
	Local oNumProcesso		:= Nil  as object
	Local oNumNotaFiscal	:= Nil  as object
	Local oPedidoVenda		:= Nil  as object
	Local oNumSerieFiscal	:= Nil  as object
	Local oDtEmissao		:= Nil  as object
	Local oDtConfirmacao	:= Nil  as object
	Local oCBoxStatus		:= Nil  as object

	oFont01    		:= TFont():New( "Segoe UI Semibold",0,-13,,.T.,0,,700,.F.,.F.,,,,,, )

	oBtnExcluir		:= TButton():New( 004,005,"Excluir",oPnlBotoes,{|| excluirRefaturamento()},040,013,,,,.T.,,"",,,,.F. )
	oBtnConfirmar 	:= TButton():New( 004,049,"Confirmar",oPnlBotoes,  {|| Processa({|| confirmarRefaturamento() }, "Confirmando Refaturamento") },040,013,,,,.T.,,"",,,,.F. )
	oBtnEstornar	:= TButton():New( 004,094,"Estornar",oPnlBotoes, {|| Processa({|| estornarRefaturamento()}, "Estoranando Refaturamento") }  ,040,013,,,,.T.,,"",,,,.F. )
	oBtnSalvar 		:= TButton():New( 004,138,"Salvar",oPnlBotoes,{|| salvarRefaturamento() },040,013,,,,.T.,,"",,,,.F. )
	oBtnCancelar 	:= TButton():New( 004,182,"Cancelar",oPnlBotoes,{|| cancelarRefaturamento()},040,013,,,,.T.,,"",,,,.F. )

	If (cOpcao == "I")
		oBtnEstornar:Disable()
	Else
		oBtnConfirmar:Disable()
		oBtnSalvar:Disable()
	Endif

	olblProcesso	:= TSay():New( 009,003,{||"No.Processo"},oPanelCabecalho,,oFont01,.F.,.F.,.F.,.T.,CLR_BLACK,CLR_WHITE,043,008)
	olblNotafiscal	:= TSay():New( 009,055,{||"Nota Fiscal"},oPanelCabecalho,,oFont01,.F.,.F.,.F.,.T.,CLR_BLACK,CLR_WHITE,043,008)
	olblSerieNota	:= TSay():New( 009,107,{||"Serie"},oPanelCabecalho,,oFont01,.F.,.F.,.F.,.T.,CLR_BLACK,CLR_WHITE,023,008)
	olblDtEmisso 	:= TSay():New( 009,142,{||"Dt. Emissao"},oPanelCabecalho,,oFont01,.F.,.F.,.F.,.T.,CLR_BLACK,CLR_WHITE,039,008)
	olblDtConfirma 	:= TSay():New( 009,194,{||"Dt. Confirmação"},oPanelCabecalho,,oFont01,.F.,.F.,.F.,.T.,CLR_BLACK,CLR_WHITE,052,008)
	olblStatus  	:= TSay():New( 009,257,{||"Status"},oPanelCabecalho,,oFont01,.F.,.F.,.F.,.T.,CLR_BLACK,CLR_WHITE,052,008)
	olblPEdidoVemda := TSay():New( 009,337,{||"No.Pedido Venda"},oPanelCabecalho,,oFont01,.F.,.F.,.F.,.T.,CLR_BLACK,CLR_WHITE,052,008)

	oNumProcesso 	:= TGet():New( 020,003,{|u| If(PCount()>0,cNumProcesso:=u,cNumProcesso)},oPanelCabecalho,042,008,'',,CLR_BLACK,CLR_WHITE,,,,.T.,"",,,.F.,.F.,,.T.,.F.,"","cNumProcesso",,)
	oNumNotaFiscal  := TGet():New( 020,055,{|u| If(PCount()>0,cNotaFiscal:=u,cNotaFiscal)},oPanelCabecalho,042,008,'',,CLR_BLACK,CLR_WHITE,,,,.T.,"",,,.F.,.F.,,.T.,.F.,"","cNotaFiscal",,)
	oNumSerieFiscal := TGet():New( 020,107,{|u| If(PCount()>0,cSerieNota:=u,cSerieNota)},oPanelCabecalho,024,008,'',,CLR_BLACK,CLR_WHITE,,,,.T.,"",,,.F.,.F.,,.T.,.F.,"","cSerieNota",,)
	oDtEmissao      := TGet():New( 020,142,{|u| If(PCount()>0,dDtEmissao:=u,dDtEmissao)},oPanelCabecalho,042,008,'',,CLR_BLACK,CLR_WHITE,,,,.T.,"",,,.F.,.F.,,.T.,.F.,"","dDtEmissao",,)
	oDtConfirmacao  := TGet():New( 020,194,{|u| If(PCount()>0,dDtConfirmar:=u,dDtConfirmar)},oPanelCabecalho,053,008,'',,CLR_BLACK,CLR_WHITE,,,,.T.,"",,,.F.,.F.,,.T.,.F.,"","dDtConfirmar",,)
	oCBoxStatus		:= TComboBox():New( 020,257,{|u| If(PCount()>0,cStatusCabecalho:=u,cStatusCabecalho)},{"","Cadastrado","Confirmado"},072,010,oPanelCabecalho,,,,CLR_BLACK,CLR_WHITE,.T.,,"",,,,,,,cStatusCabecalho )
	oCBoxStatus:lReadOnly := .T.
	oPedidoVenda 	:= TGet():New( 020,337,{|u| If(PCount()>0,cPedidoVenda:=u,cPedidoVenda)},oPanelCabecalho,042,008,'',,CLR_BLACK,CLR_WHITE,,,,.T.,"",,,.F.,.F.,,.T.,.F.,"","cPedidoVenda",,)

Return

/*/
	Criar Grids superior e inferior
/*/
Static Function criarGerids()
	Local aCamposSX3    := {}   as array
	Local aWindTela     := Nil  as object
	Local nOpc			:= 0	as numeric
	Local cLinhaOK		:= ""	as character
	Local cTudoOk		:= ""	as character
	Local aAlterar		:= {}	as array

	If (cOpcao == "I")
		nOpc        := GD_INSERT+GD_DELETE+GD_UPDATE
	Endif

	cLinhaOK	:= "compras.entrada.refaturamento.u_validarLinhaAjuste()"
	cTudoOk		:= "AllwaysTrue()"
	aAlterar	:= {"FS_PRODUTO","FS_QUANT","FS_PESO","FS_OBS","FS_LOCAL","FS_LOTECTL","FS_VUNIT"}
	bChange		:= {|| compras.entrada.refaturamento.u_iniciarItemAjuste() }

	aWindTela := oLayerRefaturamento:GetWinPanel("LY_SUPERIOR","ITM_PROD","SUPERIOR")

	oGridItensDocumento	:= FWBrowse():New()
	oGridItensDocumento:DisableFilter()
	oGridItensDocumento:DisableConfig()
	oGridItensDocumento:DisableReport()
	oGridItensDocumento:DisableSeek()
	oGridItensDocumento:DisableSaveConfig()
	oGridItensDocumento:SetAlias(cAliasSD1)
	oGridItensDocumento:SetDataTable()
	oGridItensDocumento:SetInsert(.F.)
	oGridItensDocumento:SetDelete(.F., { || .F. })
	oGridItensDocumento:lHeaderClick := .F.
	oGridItensDocumento:bChange := {|| mudaLinhaDocumento()}
	oGridItensDocumento:SetColumns(aColunas)
	oGridItensDocumento:SetOwner(aWindTela)
	oGridItensDocumento:Activate()

	aHeaderAjuste := {}
	aCamposSX3 := FWTamSX3("D1_ITEM")
	aAdd( aHeaderAjuste,	{"Item Doc"		,"FS_ITEM"	    ,""						,aCamposSX3[1],0,"","","C","",""}	)

	aCamposSX3 := FWTamSX3("D1_COD")
	aAdd( aHeaderAjuste,	{"Produto"	    ,"FS_PRODUTO"   ,"@!"	                ,aCamposSX3[1]    ,0            ,'compras.entrada.refaturamento.u_validarProduto()',"","C","SB1",""}	)

	aCamposSX3 := FWTamSX3("B1_DESC")
	aAdd( aHeaderAjuste,	{"Descrição"    ,"FS_DESC"		,"@!"	                ,aCamposSX3[1]    ,0            ,"","","C","",""}	)

	aCamposSX3 := FWTamSX3("D1_LOCAL")
	aAdd( aHeaderAjuste,	{"Armazém"    	,"FS_LOCAL"		,""	                	,aCamposSX3[1]    ,0            ,'compras.entrada.refaturamento.u_validarArmazem()',"","C","NNR",""}	)

	aCamposSX3 := FWTamSX3("D1_QUANT")
	aAdd( aHeaderAjuste,	{"Quantidade"   ,"FS_QUANT"	    ,X3Picture("D1_QUANT")    ,aCamposSX3[1]    ,aCamposSX3[2],"","","N","",""}	)

	aCamposSX3 := FWTamSX3("D1_VUNIT")
	aAdd( aHeaderAjuste,	{"Vlr.Unitario"  ,"FS_VUNIT"	,X3Picture("D1_VUNIT")	    ,aCamposSX3[1]    ,aCamposSX3[2],"","","N","",""}	)

	aCamposSX3 := FWTamSX3("D1_PESO")
	aAdd( aHeaderAjuste,	{"Peso"         ,"FS_PESO"	    ,X3Picture("D1_PESO")	,aCamposSX3[1]    ,aCamposSX3[2],"","","N","",""}	)

	aCamposSX3 := FWTamSX3("D1_LOTECTL")
	aAdd( aHeaderAjuste,	{"Lote"         ,"FS_LOTECTL"	,"@!"	                ,aCamposSX3[1]    ,0            ,'compras.entrada.refaturamento.u_validarLote()',"","C","",""}	)

	aCamposSX3 := FWTamSX3("D1_DTVALID")
	aAdd( aHeaderAjuste,	{"Validade"         ,"FS_DTVALID"	,""	                ,aCamposSX3[1]    ,0            ,"","","D","",""}	)

	aCamposSX3 := FWTamSX3("D1_LOTEFOR")
	aAdd( aHeaderAjuste,	{"Lote Fornec." ,"FS_LOTEFOR"	,"@!"	                ,aCamposSX3[1]    ,0            ,".T.","","C","",""}	)

	aAdd( aHeaderAjuste,	{"Obs."         ,"FS_OBS"	    ,""	                    ,10               ,0            ,"","","M","",""}	)

	aWindTela := oLayerRefaturamento:GetWinPanel("LY_INFERIOR","ITM_TRANS","INFERIOR")

	oGridAjusteItens      := MsNewGetDados():New(012,016,116,308,nOpc,cLinhaOK,cTudoOk,/*cIniCpos*/,aAlterar,0,99,'AllwaysTrue()',,'AllwaysTrue()',aWindTela,aHeaderAjuste,aColsAjuste,bChange )
	oGridAjusteItens:oBrowse:Align	:= CONTROL_ALIGN_ALLCLIENT

	compras.entrada.refaturamento.u_iniciarItemAjuste()

Return

/*/
	Realizar o estorno do refaturamento
/*/
Static Function estornarRefaturamento()
	lOCAL lGeradoSucesso		:= .T.	as logical
	Local cDocumentoTrasnf		:= ""	as character

	Private lMsErroAuto 	:= .F.	as logical
	Private lMsHelpAuto    	:= .T.	as logical
	Private lAutoErrNoFile	:= .T.	as logical

	dbSelectArea("SZ7")
	SZ7->(dbSetOrder(1))

	If SZ7->(dbSeek(FWxFilial("SZ7")+cNumProcesso))
		If !( verificarPVFaturado(SZ7->Z7_NUMPV,"S") )
			If FWAlertYesNo("Refaturamento confirmado."+CRLF+"Deseja realmente estornar?"+CRLF+"(Essa ação irá excluir o pedido de venda e estornar a transferêcia de saldos)",cTitulo)
				cDocumentoTrasnf	:= SZ7->Z7_DOCTRAN
				cPedidoVenda		:= SZ7->Z7_NUMPV
			Else
				Return .F.
			Endif
		Else
			Return .F.
		Endif
	Endif

	ProcRegua(3)
	Begin Transaction

		aLogErro := {}

		IncProc("Gerando cancelamento da transferencia")
		If !Empty(cDocumentoTrasnf)
			If ! (estoque.transferencia.refaturamento.u_estornoTransferencia(cDocumentoTrasnf) )
				lGeradoSucesso := .F.
			Endif
		Endif

		IncProc("Excluindo o pedido de venda")
		If !Empty(cPedidoVenda)
			If ( lGeradoSucesso ) .And. (!faturamento.pedido.refaturamento.u_excluirPedidoVenda(cPedidoVenda))
				lGeradoSucesso := .F.
			Endif
		Endif

		IncProc("Atualizando o reprocesso")
		If ( lGeradoSucesso ) .And. (!atualizarRefaturamento("S",""))
			lGeradoSucesso := .F.
		Endif

		If ( lGeradoSucesso == .T. )
			FWAlertSuccess("Refaturamento estornado com sucesso!",cTitulo)
		Else
			DisarmTransaction()
			errosLogs()
		Endif

	End Transaction

	If ( lGeradoSucesso == .T. )
		oTelaRefaturamento:End()
	Endif

Return

/*/
	Confirmar o refaturamento
/*/
Static Function confirmarRefaturamento()
	Local lRet  			:= .T.  as logical
	Local lGeradoSucesso	:= .T.	as logical
	Local cDocTransferencia	:= ""	as character

	Private lMsErroAuto 	:= .F.	as logical
	Private lMsHelpAuto    	:= .T.	as logical
	Private lAutoErrNoFile	:= .T.	as logical

	aLogErro := {}
	ProcRegua(7)
	IncProc("Salvando o refaturamento")
	If !salvarRefaturamento(.F.)
		Return
	Endif

	IncProc("Validando o refaturamento")
	If !validarConfirmacao()
		Return
	Endif

	Begin Transaction

		IncProc("Ajustando lotes dos produtos")
		If !alterarLoteProdutosAjuste()
			lGeradoSucesso := .F.
		Endif

	/*/	IncProc("Gerando a baixa saldos")
		If ( lGeradoSucesso ) .And. (!estoque.transferencia.refaturamento.u_gerarBaixaSaldos(@cDocTransferencia))
			lGeradoSucesso := .F.
		Endif
	/*/

		IncProc("Gerando a transferencia")
		If ( lGeradoSucesso ) .And. (!estoque.transferencia.refaturamento.u_gerarTransferencia(@cDocTransferencia))
			lGeradoSucesso := .F.
		Endif

		IncProc("Gerando o pedido de venda")
		If ( lGeradoSucesso ) .And. (!faturamento.pedido.refaturamento.u_gerarPedidoVenda())
			lGeradoSucesso := .F.
		Endif

		IncProc("Atualizando o refaturamento")
		If ( lGeradoSucesso ) .And. (!atualizarRefaturamento("E",cDocTransferencia))
			lGeradoSucesso := .F.
		Endif

		If ( lGeradoSucesso == .T. )
			FWAlertSuccess("Refaturamento gerado com sucesso!",cTitulo)
			ConfirmSX8()
			oTelaRefaturamento:End()
		Else
			DisarmTransaction()
			errosLogs()
			RollbackSx8()
		Endif

	End Transaction


Return lRet

/*/
	Excluir o refaturamento
/*/
Static Function excluirRefaturamento()
	lOCAL lGeradoSucesso		:= .T.	as logical
	Local cDocumentoTrasnf		:= ""	as character

	Private lMsErroAuto 	:= .F.	as logical
	Private lMsHelpAuto    	:= .T.	as logical
	Private lAutoErrNoFile	:= .T.	as logical

	dbSelectArea("SZ7")
	SZ7->(dbSetOrder(1))

	If !SZ7->(dbSeek(FWxFilial("SZ7")+cNumProcesso))
		FWAlertWarning("Não foi possível excluir, refaturmanto não existe.",cTitulo)
		Return
	Endif

	If SZ7->Z7_STATUS == "1"
		If !(FWAlertYesNo("Deseja realmente excluir o refaturamento?",cTitulo))
			Return .F.
		Endif
	Else
		If !( verificarPVFaturado(SZ7->Z7_NUMPV,"D") )
			If FWAlertYesNo("Refaturamento confirmado."+CRLF+"Deseja realmente excluir?"+CRLF+"(Essa ação irá excluir o pedido de venda e estornar a transferêcia de saldos)",cTitulo)
				cDocumentoTrasnf		:= SZ7->Z7_DOCTRAN
				cPedidoVenda			:= SZ7->Z7_NUMPV
			Else
				Return .F.
			Endif
		Else
			Return .F.
		Endif
	Endif

	Begin Transaction

		aLogErro := {}

		If !Empty(cDocumentoTrasnf)
			If ! (estoque.transferencia.refaturamento.u_estornoTransferencia(cDocumentoTrasnf) )
				lGeradoSucesso := .F.
			Endif
		Endif

		If !Empty(cPedidoVenda)
			If ( lGeradoSucesso ) .And. (!faturamento.pedido.refaturamento.u_excluirPedidoVenda(cPedidoVenda))
				lGeradoSucesso := .F.
			Endif
		Endif

		If ( lGeradoSucesso ) .And. (!excluirItemRefaturamento())
			lGeradoSucesso := .F.
		Endif

		If ( lGeradoSucesso == .T. )
			FWAlertSuccess("Refaturamento excluido com sucesso!",cTitulo)
		Else
			DisarmTransaction()
			errosLogs()
		Endif

	End Transaction

	If ( lGeradoSucesso == .T. )
		oTelaRefaturamento:End()
	Endif

Return

/*/
	Verificar se o pedido foi faturado
/*/
Static Function verificarPVFaturado(cNumPedidoVenda,cOpcao)
	Local lRet				:= .F.	as logical

	Default cNumPedidoVenda	:= ""

	dbSelectArea("SC5")
	If ( SC5->(dbSeek(FWxFilial("SC5")+cNumPedidoVenda)))
		If !(Empty(SC5->C5_NOTA))
			If ( cOpcao == "D")
				FWAlertWarning("Refaturamento não pode ser excluido. Pedido de venda está faturado.",cTitulo)
			Else
				FWAlertWarning("Refaturamento não pode ser estornado. Pedido de venda está faturado.",cTitulo)
			Endif
			lRet := .T.
		Endif
	Endif

REturn lRet

/*/
	Excluir o refaturamento
/*/
Static Function excluirItemRefaturamento()
	Local lRet	:= .T.	as logical

	dbSelectArea("SZ7")
	SZ7->(dbSetOrder(1))

	dbSelectArea("SZ8")
	SZ8->(dbSetOrder(1))

	If SZ7->(dbSeek(FWxFilial("SZ7")+cNumProcesso))
		If RecLock("SZ7",.F.)
			SZ7->(dbDelete())
			SZ7->(MsUnlock())
		Else
			FWAlertWarning("Não foi possível excluir o refaturmanto.",cTitulo)
			Return .F.
		Endif
	Endif

	If SZ8->(dbSeek(FWxFilial("SZ8")+cNumProcesso))
		While (!SZ8->(eof())) .And. ( SZ8->Z8_FILIAL == FWxFilial("SZ8")) .And. ( SZ8->Z8_NUM == cNumProcesso)
			If RecLock("SZ8",.F.)
				SZ8->(dbDelete())
				SZ8->(MsUnlock())
			Else
				FWAlertWarning("Não foi possível excluir o refaturmanto.",cTitulo)
				Return .F.
			Endif
			SZ8->(dbSkip())
		Enddo
	Endif

	dbSelectArea("SD1")
	SD1->(dbSetOrder(1))
	cFiltro     := cNotaFiscal+cSerieNota+cCodFornecedor+cLojFornecedor
	If ( SD1->(dbSeek(FWxFilial("SD1")+cFiltro)))
		While !( SD1->(eof())) .And. ( SD1->D1_FILIAL == FWxFilial("SD1") ) .And. ;
				( SD1->D1_DOC+SD1->D1_SERIE+SD1->D1_FORNECE+SD1->D1_LOJA == cFiltro )

			RecLock("SD1",.F.)
			SD1->D1_ZREFAT := ""
			SD1->(MsUnlock())

			SD1->(dbSkip())
		EndDo
	Endif

Return lRet

/*/
	Cancelar o refaturamento
/*/
Static Function cancelarRefaturamento()

	RollbackSx8()
	oTelaRefaturamento:End()

Return

/*/
	Validar se a linha grid ajuste está ok
/*/
User Function validarLinhaAjuste()
	Local lRet		:= .T.	as logical
	Local nLinha	:= 0	as numeric

	nLinha 		:= oGridAjusteItens:NAT

	If ( oGridAjusteItens:aCols[nLinha,POS_DELELTE_AJUSTE] == .F. )

		Do Case
		Case Empty(oGridAjusteItens:aCols[nLinha,POS_COD_AJUSTE])
			FWAlertWarning("Campo 'Produto' é obrigatótio.",cTitulo)
			lRet := .F.

		Case oGridAjusteItens:aCols[nLinha,POS_PESO_AJUSTE] == 0
			FWAlertWarning("Campo 'Peso' é obrigatótio.",cTitulo)
			lRet := .F.

		Case !(validarQuantidade(nLinha))
			FWAlertWarning("Campo 'Quantidade' é obrigatótio.",cTitulo)
			lRet := .F.

		EndCase

	Endif

Return lRet

/*/
	Valida a quantidade para produtos incluidos
	que não estão no documento
/*/
Static Function validarQuantidade(nLinha)
	Local lRet		:= .T.	as logical
	Local aAreaSD1	:= {}	as array
	Local cProduto	:= ""	as character
	Local nQtdItem	:= 0	as numeric

	aAreaSD1	:= (cAliasSD1)->(getArea())
	cProduto	:= oGridAjusteItens:aCols[nLinha,POS_COD_AJUSTE]
	nQtdItem	:= oGridAjusteItens:aCols[nLinha,POS_QUANT_AJUSTE]

	(cAliasSD1)->(dbSetOrder(2))

	If !(cAliasSD1)->(dbSeek(cProduto)) .And. ( nQtdItem == 0 )
		lRet := .F.
	Endif

	RestArea(aAreaSD1)

Return lRet

/*/
	Validar produto e preencher descricap
/*/
User Function validarProduto()
	Local lRet				:= .T.	as logical
	Local nLinha			:= 0	as numeric
	Local cItemDocumento	:= ""	as character

	cItemDocumento := (cAliasSD1)->FS_ITEM

	nLinha := oGridAjusteItens:NAT

	If ( oGridAjusteItens:aCols[nLinha,POS_DELELTE_AJUSTE] == .F. )

		If Empty(M->FS_PRODUTO)
			FWAlertWarning("Campo 'Produto' é obrigatótio.",cTitulo)
			Return .F.
		Endif

		dbSelectArea("SB1")
		If SB1->(dbSeek(FWxFilial("SB1")+M->FS_PRODUTO))
			oGridAjusteItens:aCols[nLinha,POS_DESC_AJUSTE]  := SB1->B1_DESC
			oGridAjusteItens:aCols[nLinha,POS_LOCAL_AJUSTE] := (cAliasSD1)->FS_LOCAL
			oGridAjusteItens:aCols[nLinha,POS_LOTE_AJUSTE] := (cAliasSD1)->FS_LOTECTL
			oGridAjusteItens:aCols[nLinha,POS_VALID_AJUSTE] := (cAliasSD1)->FS_DTVALID
			oGridAjusteItens:aCols[nLinha,POS_VLRUNIT_AJUSTE] := (cAliasSD1)->FS_VUNIT
			oGridAjusteItens:aCols[nLinha,POS_LOCAL_AJUSTE] := SB1->B1_LOCPAD
		Else
			FWAlertWarning("Produto informado não encontrado.",cTitulo)
			Return .F.
		Endif

	Endif

Return lRet

/*/
	Validar Armazem informado
/*/
User Function validarArmazem()
	Local lRet			:= .T.	as logical
	Local nLinha		:= 0	as numeric
	Local aAreaSD1		:= {}	as array
	Local cCodProduto	:= ""	as character

	If Empty(M->FS_LOCAL)
		FWAlertWarning("Campo 'Armazém' é obrigatótio.",cTitulo)
		Return .F.
	Endif

	aAreaSD1 	:= (cAliasSD1)->(getArea())
	nLinha 		:= oGridAjusteItens:NAT

	If ( oGridAjusteItens:aCols[nLinha,POS_DELELTE_AJUSTE] == .F. )

		cCodProduto	:= oGridAjusteItens:aCols[nLinha,POS_COD_AJUSTE]

		dbSelectArea("NNR")
		NNR->(dbSetOrder(1))

		If !NNR->(dbSeek(FWxFilial("NNR")+M->FS_LOCAL))
			FWAlertWarning("Armazém não encontrado.",cTitulo)
			Return .F.
		Endif

		(cAliasSD1)->(dbSetOrder(2))

		If (cAliasSD1)->(dbSeek(cCodProduto))
			FWAlertWarning("Armazém não pode ser alterado.",cTitulo)
			lRet := .F.
		Endif

	Endif

	RestArea(aAreaSD1)

Return lRet

/*/
	Validar Lote Item
/*/
User Function validarLote()
	Local lRet			:= .T.	as logical
	Local nLinha		:= 0	as numeric
	Local aAreaSD1		:= {}	as array
	Local cCodProduto	:= ""	as character

	If Empty(M->FS_LOTECTL)
		Return .T.
	Endif

	aAreaSD1 	:= (cAliasSD1)->(getArea())
	nLinha 		:= oGridAjusteItens:NAT

	If ( oGridAjusteItens:aCols[nLinha,POS_DELELTE_AJUSTE] == .F. )

		cCodProduto	:= oGridAjusteItens:aCols[nLinha,POS_COD_AJUSTE]

		(cAliasSD1)->(dbSetOrder(2))

		If (cAliasSD1)->(dbSeek(cCodProduto)) .And. ( !Empty((cAliasSD1)->FS_LOTECTL) )
			FWAlertWarning("Lote não pode ser alterado.",cTitulo)
			lRet := .F.
		Endif

	Endif

	RestArea(aAreaSD1)

Return lRet

User Function iniciarItemAjuste()
	Local nLinha	:= 0	as numeric

	nLinha := oGridAjusteItens:NAT

	If ( oGridAjusteItens:aCols[nLinha,POS_DELELTE_AJUSTE] == .F. )

		oGridAjusteItens:aCols[nLinha,POS_ITEM_AJUSTE] 	:= (cAliasSD1)->FS_ITEM
		oGridAjusteItens:aCols[nLinha,POS_LOTEFOR_AJUSTE] 	:= (cAliasSD1)->FS_LOTEFOR
		oGridAjusteItens:Refresh()

	Endif

Return

/*/
	Muda a linha do documento para edição do ajuste
/*/
Static Function mudaLinhaDocumento()
	Local nLinha			:= 1	as numeric
	Local cItemDocumento	:= ""	as character

	If ( ValType(oGridAjusteItens) == "U" )
		Return nil
	Endif

	cItemDocumento := oGridAjusteItens:aCols[nLinha,POS_ITEM_AJUSTE]

	salvarRegistroAjuste(cItemDocumento,(cAliasSD1)->FS_ITEM)

Return


/*/
	Criar tabela temporaria para ajuste
/*/
Static Function criarTabelaTmpAjuste()
	Local aFields 		:= {}	as array

	cAliasTmpAjuste	:= GetNextAlias()
	oTabelaTmpAjuste:= FWTemporaryTable():New(cAliasTmpAjuste)

	aCamposSX3 := FWTamSX3("D1_ITEM")
	aAdd( aFields,	{"FS_ITEM"	    , aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("D1_COD")
	aAdd( aFields,	{"FS_PRODUTO"   , aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("B1_DESC")
	aAdd( aFields,	{"FS_DESCRI"	, aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("D1_LOCAL")
	aAdd( aFields,	{"FS_LOCAL"	, aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("D1_QUANT")
	aAdd( aFields,	{"FS_QUANT"	    , aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("D1_VUNIT")
	aAdd( aFields,	{"FS_VUNIT"	    , aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("D1_PESO")
	aAdd( aFields,	{"FS_PESO"	    , aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("D1_LOTECTL")
	aAdd( aFields,	{"FS_LOTECTL"	    , aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("D1_DTVALID")
	aAdd( aFields,	{"FS_DTVALID"	    , aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aCamposSX3 := FWTamSX3("D1_LOTEFOR")
	aAdd( aFields,	{"FS_LOTEFOR"	    , aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	aAdd( aFields,	{"FS_OBS"	    , "M"			, 10		   , 0}	)

	aCamposSX3 := FWTamSX3("D1_LOTECTL")
	aAdd( aFields,	{"FS_LOTEDES"	    , aCamposSX3[3]	, aCamposSX3[1], aCamposSX3[2]}	)

	oTabelaTmpAjuste:SetFields( aFields )
	oTabelaTmpAjuste:AddIndex("1", {"FS_ITEM","FS_PRODUTO"} )
	oTabelaTmpAjuste:AddIndex("2", {"FS_PRODUTO"} )
	oTabelaTmpAjuste:Create()

Return

/*/
	Salvar registro na tabela TMP ajuaste
/*/	
Static Function salvarRegistroAjuste(cItemDocumento,cNovoItemDocumento)
	Local nRecord				:= 0	as numeric
	Local lRet					:= .T.	as logical

	Default cItemDocumento 		:= ""
	Default cNovoItemDocumento	:= ""

	If Empty(cItemDocumento) .Or. Empty(cNovoItemDocumento)
		Return Nil
	Endif

	If (cAliasTmpAjuste)->(dbSeek(cItemDocumento))
		While !(cAliasTmpAjuste)->(eof()) .And. (cAliasTmpAjuste)->FS_ITEM == cItemDocumento

			RecLock(cAliasTmpAjuste,.F.)

			(cAliasTmpAjuste)->(dbDelete())

			(cAliasTmpAjuste)->(MsUnlock())

			(cAliasTmpAjuste)->(dbSkip())
		EndDo
	Endif

	For nRecord := 1 To Len(oGridAjusteItens:aCols)

		If ( oGridAjusteItens:aCols[nRecord,POS_DELELTE_AJUSTE] == .F. )

			If !Empty(oGridAjusteItens:aCols[nRecord,POS_COD_AJUSTE])

				RecLock(cAliasTmpAjuste,.T.)
				(cAliasTmpAjuste)->FS_ITEM		:= oGridAjusteItens:aCols[nRecord,POS_ITEM_AJUSTE]
				(cAliasTmpAjuste)->FS_PRODUTO	:= oGridAjusteItens:aCols[nRecord,POS_COD_AJUSTE]
				(cAliasTmpAjuste)->FS_DESCRI	:= oGridAjusteItens:aCols[nRecord,POS_DESC_AJUSTE]
				(cAliasTmpAjuste)->FS_LOCAL		:= oGridAjusteItens:aCols[nRecord,POS_LOCAL_AJUSTE]
				(cAliasTmpAjuste)->FS_QUANT		:= oGridAjusteItens:aCols[nRecord,POS_QUANT_AJUSTE]
				(cAliasTmpAjuste)->FS_VUNIT		:= oGridAjusteItens:aCols[nRecord,POS_VLRUNIT_AJUSTE]
				(cAliasTmpAjuste)->FS_PESO		:= oGridAjusteItens:aCols[nRecord,POS_PESO_AJUSTE]
				(cAliasTmpAjuste)->FS_LOTECTL	:= oGridAjusteItens:aCols[nRecord,POS_LOTE_AJUSTE]
				(cAliasTmpAjuste)->FS_LOTEFOR	:= oGridAjusteItens:aCols[nRecord,POS_LOTEFOR_AJUSTE]
				(cAliasTmpAjuste)->FS_DTVALID	:= oGridAjusteItens:aCols[nRecord,POS_VALID_AJUSTE]
				(cAliasTmpAjuste)->FS_OBS		:= oGridAjusteItens:aCols[nRecord,POS_OBS_AJUSTE]

				(cAliasTmpAjuste)->(MsUnlock())

			EndIf
		Endif
	Next

	atualizarLinhaGridAjuste(cNovoItemDocumento)

Return lRet

/*/
	Atualizar grid Ajueste novo iteme
/*/	
Static Function atualizarLinhaGridAjuste(cNovoItemDocumento)

	Default cNovoItemDocumento := ""

	oGridAjusteItens:aCols := {}
	oGridAjusteItens:Refresh()

	If (cAliasTmpAjuste)->(dbSeek(cNovoItemDocumento))
		While !(cAliasTmpAjuste)->(eof()) .And. (cAliasTmpAjuste)->FS_ITEM == cNovoItemDocumento

			aAdd(oGridAjusteItens:aCols,;
				{cNovoItemDocumento,;
				(cAliasTmpAjuste)->FS_PRODUTO,;
				(cAliasTmpAjuste)->FS_DESCRI,;
				(cAliasTmpAjuste)->FS_LOCAL,;
				(cAliasTmpAjuste)->FS_QUANT,;
				(cAliasTmpAjuste)->FS_VUNIT,;
				(cAliasTmpAjuste)->FS_PESO,;
				(cAliasTmpAjuste)->FS_LOTECTL,;
				(cAliasTmpAjuste)->FS_DTVALID,;
				(cAliasTmpAjuste)->FS_LOTEFOR,;
				(cAliasTmpAjuste)->FS_OBS,;
				.F.;
				})

			(cAliasTmpAjuste)->(dbSkip())
		EndDo
	Else
		aAdd(oGridAjusteItens:aCols,;
			{cNovoItemDocumento,;
			Space(TamSx3("D1_COD")[1]),;
			Space(TamSx3("B1_DESC")[1]),;
			Space(TamSx3("D1_LOCAL")[1]),;
			0,;
			0,;
			0,;
			Space(TamSx3("D1_LOTECTL")[1]),;
			CTOD(""),;
			Space(TamSx3("D1_LOTEFOR")[1]),;
			"",;
			.F.;
			})

	Endif

	oGridAjusteItens:Refresh()

Return

/*/
	Salvar as informações nas tabelas
/*/
Static Function salvarRefaturamento(lMostraMsg)
	Local cItemDocumento	:= ""	as character
	Local nLinha			:= 1	as numeric
	Local lRet				:= .T.	as logical

	Default lMostraMsg := .T.

	If !( compras.entrada.refaturamento.u_validarLinhaAjuste() )
		Return .F.
	Endif

	If !( verificarPesoAjuste("S") )
		Return .F.
	Endif

	dbSelectArea("SZ7")
	SZ7->(dbSetOrder(1))

	dbSelectArea("SZ8")
	SZ8->(dbSetOrder(1))

	cItemDocumento	:= 	oGridAjusteItens:aCols[nLinha,POS_ITEM_AJUSTE]

	If !(salvarRegistroAjuste(cItemDocumento,cItemDocumento))
		Return
	Endif

	(cAliasTmpAjuste)->(dbGotop())

	If !(cAliasTmpAjuste)->(eof())

		If !SZ7->(dbSeek(FWxFilial("SZ7")+cNumProcesso))
			salvarCabecalhoRefaturamento()
		Endif

		If SZ8->(dbSeek(FWxFilial("SZ8")+cNumProcesso))
			excluirItensAjustes()
		Endif

		While !( (cAliasTmpAjuste)->(eof()) )
			RecLock("SZ8",.T.)
			SZ8->Z8_FILIAL	:= FWxFilial("SZ8")
			SZ8->Z8_NUM    	:= cNumProcesso
			SZ8->Z8_NUMNF  	:= cNotaFiscal
			SZ8->Z8_SERIE  	:= cSerieNota
			SZ8->Z8_ITEMNF 	:= (cAliasTmpAjuste)->FS_ITEM
			SZ8->Z8_PRODUTO	:= (cAliasTmpAjuste)->FS_PRODUTO
			SZ8->Z8_QUANT  	:= (cAliasTmpAjuste)->FS_QUANT
			SZ8->Z8_VUNIT  	:= (cAliasTmpAjuste)->FS_VUNIT
			SZ8->Z8_PESOLIQ	:= (cAliasTmpAjuste)->FS_PESO
			SZ8->Z8_PESOLIQ	:= (cAliasTmpAjuste)->FS_PESO
			SZ8->Z8_LOTECTL	:= (cAliasTmpAjuste)->FS_LOTECTL
			SZ8->Z8_LOTEDES	:= (cAliasTmpAjuste)->FS_LOTEDES
			SZ8->Z8_DTVALID	:= (cAliasTmpAjuste)->FS_DTVALID
			SZ8->Z8_LOTEFOR	:= (cAliasTmpAjuste)->FS_LOTEFOR
			SZ8->Z8_LOCAL	:= (cAliasTmpAjuste)->FS_LOCAL
			SZ8->Z8_OBS		:= (cAliasTmpAjuste)->FS_OBS
			SZ8->Z8_STATUS 	:= "1"

			SZ8->(MsUnlock())

			(cAliasTmpAjuste)->(dbSkip())
		EndDo

		If lMostraMsg
			FWAlertSuccess("Refaturamento salvo com sucesso", cTitulo)
			oTelaRefaturamento:End()
		Endif
		ConfirmSX8()
	Else
		FWAlertWarning("Nenhum Ajuste foi realizado para documento.",cTitulo)
		lRet := .F.
	Endif

Return lRet


/*/
	Salvar cabecalho Refaturamento
/*/
Static Function salvarCabecalhoRefaturamento()

	RecLock("SZ7",.T.)
	SZ7->Z7_FILIAL 	:= FWxFilial("SZ7")
	SZ7->Z7_NUM		:= cNumProcesso
	SZ7->Z7_NUMNF  	:= cNotaFiscal
	SZ7->Z7_SERIE  	:= cSerieNota
	SZ7->Z7_FORNECE	:= cCodFornecedor
	SZ7->Z7_LOJA   	:= cLojFornecedor
	SZ7->Z7_EMISSAO	:= dDatabase
	SZ7->Z7_STATUS 	:= "1"

	SZ7->(MsUnlock())

Return

/*/
	Excluir Itens do Ajustes
/*/
Static Function excluirItensAjustes()

	If SZ8->(dbSeek(FWxFilial("SZ8")+cNumProcesso))
		While !SZ8->(eof()) .And. SZ8->Z8_FILIAL == FWxFilial("SZ8") .And. SZ8->Z8_NUM == cNumProcesso
			RecLock("SZ8",.F.)
			SZ8->(dbDelete())
			SZ8->(MsUnlock())
			SZ8->(dbSkip())
		EndDo
	Endif
Return

/*/
	Alimentar a tabela de ajuste para refaturamento salvo
/*/
Static Function alimentaTabelaAjuste()

	dbSelectArea("SZ8")
	SZ8->(dbSetOrder(1))

	If SZ8->(dbSeek(FWxFilial("SZ8")+cNumProcesso))
		While !SZ8->(eof()) .And. SZ8->Z8_FILIAL == FWxFilial("SZ8") .And. SZ8->Z8_NUM == cNumProcesso

			RecLock(cAliasTmpAjuste,.T.)
			(cAliasTmpAjuste)->FS_ITEM 		:= SZ8->Z8_ITEMNF
			(cAliasTmpAjuste)->FS_PRODUTO 	:= SZ8->Z8_PRODUTO
			(cAliasTmpAjuste)->FS_QUANT		:= SZ8->Z8_QUANT
			(cAliasTmpAjuste)->FS_VUNIT		:= SZ8->Z8_VUNIT
			(cAliasTmpAjuste)->FS_PESO		:= SZ8->Z8_PESOLIQ
			(cAliasTmpAjuste)->FS_LOTECTL	:= SZ8->Z8_LOTECTL
			(cAliasTmpAjuste)->FS_LOTEFOR	:= SZ8->Z8_LOTEFOR
			(cAliasTmpAjuste)->FS_OBS		:= SZ8->Z8_OBS
			(cAliasTmpAjuste)->FS_LOCAL		:= SZ8->Z8_LOCAL
			(cAliasTmpAjuste)->FS_DESCRI	:= Posicione("SB1",1,FWxFilial("SB1")+SZ8->Z8_PRODUTO,"B1_DESC")
			(cAliasTmpAjuste)->FS_DTVALID	:= SZ8->Z8_DTVALID

			(cAliasTmpAjuste)->(MsUnlock())

			SZ8->(dbSkip())
		EndDo

		If (cAliasTmpAjuste)->(dbSeek((cAliasSD1)->FS_ITEM))

			oGridAjusteItens:aCols := {}
			oGridAjusteItens:Refresh()

			While !(cAliasTmpAjuste)->(eof()) .And. (cAliasTmpAjuste)->FS_ITEM == (cAliasSD1)->FS_ITEM

				aAdd(oGridAjusteItens:aCols,;
					{(cAliasSD1)->FS_ITEM,;
					(cAliasTmpAjuste)->FS_PRODUTO,;
					(cAliasTmpAjuste)->FS_DESCRI,;
					(cAliasTmpAjuste)->FS_LOCAL,;
					(cAliasTmpAjuste)->FS_QUANT,;
					(cAliasTmpAjuste)->FS_VUNIT,;
					(cAliasTmpAjuste)->FS_PESO,;
					(cAliasTmpAjuste)->FS_LOTECTL,;
					(cAliasTmpAjuste)->FS_DTVALID,;
					(cAliasTmpAjuste)->FS_LOTEFOR,;
					(cAliasTmpAjuste)->FS_OBS,;
					.F.;
					})

				(cAliasTmpAjuste)->(dbSkip())
			EndDo

		Endif
	Else
		If !(cAliasTmpAjuste)->(eof())
			While !(cAliasTmpAjuste)->(eof())

				RecLock(cAliasTmpAjuste,.F.)

				(cAliasTmpAjuste)->(dbDelete())

				(cAliasTmpAjuste)->(MsUnlock())

				(cAliasTmpAjuste)->(dbSkip())
			EndDo
		Endif

		(cAliasSD1)->(dbGotop())
		While !(cAliasSD1)->(eof())

			RecLock(cAliasTmpAjuste,.T.)

			(cAliasTmpAjuste)->FS_ITEM 		:= (cAliasSD1)->FS_ITEM
			(cAliasTmpAjuste)->FS_PRODUTO	:= (cAliasSD1)->FS_PRODUTO
			(cAliasTmpAjuste)->FS_DESCRI	:= (cAliasSD1)->FS_DESCRI
			(cAliasTmpAjuste)->FS_LOCAL		:= (cAliasSD1)->FS_LOCAL
			(cAliasTmpAjuste)->FS_QUANT		:= (cAliasSD1)->FS_QUANT
			(cAliasTmpAjuste)->FS_VUNIT		:= (cAliasSD1)->FS_VUNIT
			(cAliasTmpAjuste)->FS_PESO		:= (cAliasSD1)->FS_PESO
			(cAliasTmpAjuste)->FS_LOTECTL	:= (cAliasSD1)->FS_LOTECTL
			(cAliasTmpAjuste)->FS_DTVALID	:= (cAliasSD1)->FS_DTVALID
			(cAliasTmpAjuste)->FS_LOTEFOR	:= (cAliasSD1)->FS_LOTEFOR
			(cAliasTmpAjuste)->FS_OBS 		:= ""

			(cAliasTmpAjuste)->(MsUnlock())

			If Empty(oGridAjusteItens:aCols[1,2])

				oGridAjusteItens:aCols := {}
				oGridAjusteItens:Refresh()

				aAdd(oGridAjusteItens:aCols,;
					{(cAliasTmpAjuste)->FS_ITEM,;
					(cAliasTmpAjuste)->FS_PRODUTO,;
					(cAliasTmpAjuste)->FS_DESCRI,;
					(cAliasTmpAjuste)->FS_LOCAL,;
					(cAliasTmpAjuste)->FS_QUANT,;
					(cAliasTmpAjuste)->FS_VUNIT,;
					(cAliasTmpAjuste)->FS_PESO,;
					(cAliasTmpAjuste)->FS_LOTECTL,;
					(cAliasTmpAjuste)->FS_DTVALID,;
					(cAliasTmpAjuste)->FS_LOTEFOR,;
					(cAliasTmpAjuste)->FS_OBS,;
					.F.;
					})
			Endif
			(cAliasSD1)->(dbSkip())
		EndDo

	Endif

	oGridAjusteItens:Refresh()
	(cAliasSD1)->(dbGotop())

Return

/*/
	Pode executar rotina
/*/
Static Function podeExecutar()
	Local lRet	:= .F. as logical

	Begin Sequence

		dbSelectArea("SZ7")
		SZ7->(dbSetOrder(2))

		If !( SZ7->(dbSeek(FWxFilial("SZ7")+cNotaFiscal+cSerieNota+cCodFornecedor+cLojFornecedor)))

			If !( SF1->F1_FORMUL == "S")
				FWAlertWarning("Nota fiscal não é formulario proprio.",cTitulo)
				Break
			Endif

			If !verificarItensDocumeto()
				Break
			Endif
		Endif

		lRet := .T.

	End Sequence

Return lRet

/*/
	Verificar se os intens do documento entrada
/*/
Static Function verificarItensDocumeto()
	Local lRet			:= .T.	as logical
	Local cTesRefatura	:= ""	as character
	Local nQtdRegistro	:= 0	as numeric
	Local nSaldoItem	:= 0	as numeric
	Local cFiltro   	:= ""   as character
	Local cTesRefItem	:= ""   as character

	cTesRefatura	:= GetNewPar("FS_TESREFT","001")
	cFiltro     	:= cNotaFiscal+cSerieNota+cCodFornecedor+cLojFornecedor

	dbSelectArea("SF4")
	SF4->(dbSetOrder(1))

	dbSelectArea("SB1")
	SB1->(dbSetOrder(1))

	dbSelectArea("SD1")
	SD1->(dbSetOrder(1))
	If ( SD1->(dbSeek(FWxFilial("SD1")+cFiltro)))
		While !( SD1->(eof())) .And. ( SD1->D1_FILIAL == FWxFilial("SD1") ) .And. ;
				( SD1->D1_DOC+SD1->D1_SERIE+SD1->D1_FORNECE+SD1->D1_LOJA == cFiltro )

			If ( SD1->D1_TES $ cTesRefatura)

				If ( SD1->D1_ZPESO == 0 )
					FWAlertWarning("Campo peso não foi informado no Item '"+SD1->D1_ITEM+". É obrigatório",cTitulo)
					lRet := .F.
					Exit
				Endif

				If SF4->(dbSeek(FWxFilial("SF4")+SD1->D1_TES)) .And. ( SF4->F4_ESTOQUE == "S")

					nSaldoItem := verificarSaldoItem()

					If !( nSaldoItem == SD1->D1_QUANT) .And. !( SD1->D1_ZREFAT == "S")
						FWAlertWarning("Saldo em estoque está divergente da quantidade no Item '"+SD1->D1_ITEM+".",cTitulo)
						lRet := .F.
						Exit
					Endif

				Endif

				nQtdRegistro ++
			Else
				If !( SD1->D1_TES $ cTesRefItem )
					cTesRefItem := cTesRefItem + SD1->D1_TES + CRLF
				Endif
			EndIf

			SD1->(dbSkip())
		EndDo
	Else
		FWAlertWarning("Item do documento não encontrado",cTitulo)
		lRet := .F.
	Endif

	If ( nQtdRegistro == 0 ) .And. ( lRet == .T.)
		If !Empty(cTesRefItem)
			FWAlertWarning("Nenhum item encontrado"+CRLF+"TES não existe no parametro 'FS_TESREFT'"+CRLF+cTesRefItem,cTitulo)
		Else
			FWAlertWarning("Nenhum item encontrado",cTitulo)
		Endif
		lRet := .F.
	Endif

Return lRet

/*/
	Verificar saldo do item
/*/
Static Function verificarSaldoItem()
	Local nRet		:= 0	as numeric
	Local cQuery	:= ""	as character
	Local cAliasSB8	:= ""	as character

	cQuery 		:= 	queryBuscarLote()
	cAliasSB8	:=  MpSysOpenQuery(cQuery)

	dbSelectArea(cAliasSB8)

	If ( (cAliasSB8)->(!EOF()) )
		nRet := (cAliasSB8)->B8_SALDO - ((cAliasSB8)->B8_QACLASS + (cAliasSB8)->B8_QEMPPRE)
	Endif

	(cAliasSB8)->(dbCloseArea())

Return nRet

/*
	Query do lote SB8
*/
Static Function queryBuscarLote()
	Local cQuery	:= ""	as character

	cQuery += " SELECT " + CRLF
	cQuery += "        * "		+ CRLF

	cQuery += " FROM " + CRLF
	cQuery += "     " + RetSQLTab("SB8") + CRLF

	cQuery += " INNER JOIN " + CRLF
	cQuery += "     " + RetSQLTab("SD1") + CRLF
	cQuery += "     	ON" + CRLF
	cQuery += " 	    D1_FILIAL		= B8_FILIAL " + CRLF
//	cQuery += " 	    AND D1_DOC		= B8_DOC " + CRLF
//	cQuery += " 	    AND D1_SERIE	= B8_SERIE " + CRLF
//	cQuery += " 	    AND D1_FORNECE	= B8_CLIFOR " + CRLF
//	cQuery += " 	    AND D1_LOJA		= B8_LOJA " + CRLF
	cQuery += " 	    AND D1_LOCAL	= B8_LOCAL " + CRLF
	cQuery += " 	    AND D1_COD		= B8_PRODUTO " + CRLF
	cQuery += " 	    AND D1_LOTECTL	= B8_LOTECTL " + CRLF
	cQuery += "	    	AND " + RetSqlDel("SD1") + CRLF

	cQuery += " WHERE " + CRLF
	cQuery += " 	    1 = 1 " + CRLF
	cQuery += "	 		AND " + RetSqlFil("SB8") + CRLF
	cQuery += " 		AND B8_LOTECTL  = "+ ValToSql(SD1->D1_LOTECTL) + CRLF
//	cQuery += " 		AND B8_LOTEFOR  = "+ ValToSql(SD1->D1_LOTEFOR) + CRLF
	cQuery += " 		AND B8_LOCAL  = " + ValToSql(SD1->D1_LOCAL) + CRLF
	cQuery += " 		AND B8_PRODUTO  = " + ValToSql(SD1->D1_COD) + CRLF
//	cQuery += " 		AND B8_ORIGLAN  = 'NF'" + CRLF
	cQuery += "	    	AND " + RetSqlDel("SB8") + CRLF

Return cQuery

/*/
	Chamar funcao saldos por lote
/*/
Static Function sadosPorLote()
	Local cProduto	:= ""	as character
	Local cArmazem	:= ""	as character
	Local nLinha	:= 0	as numeric
	Local aRetLote	:= {}	as array

	If ( Type("M->FS_LOTECTL") == "C")
		nLinha 		:= oGridAjusteItens:NAT

		If ( oGridAjusteItens:aCols[nLinha,POS_DELELTE_AJUSTE] == .F. )

			cProduto	:= oGridAjusteItens:aCols[nLinha,POS_COD_AJUSTE]
			cArmazem	:= oGridAjusteItens:aCols[nLinha,POS_LOCAL_AJUSTE]

			If Empty(cProduto) .Or. Empty(cArmazem)
				FWAlertWarning("Produto e Armazém são obrigatorio",cTitulo)
				Return
			Endif

			aRetLote := lib.estoque.u_saldosLote(cProduto,cArmazem)
			M->FS_LOTECTL := aRetLote[1]
			oGridAjusteItens:aCols[nLinha,POS_VALID_AJUSTE] := aRetLote[2]

		Endif

	Endif
Return

/*/
	Validar se pode confirmar o refaturamento
/*/
Static Function validarConfirmacao()
	Local lRet		:= .F.	as logical
	Local aAreaSD1	:= {}	as array
	Local aAreaTmp	:= {}	as array

	aAreaSD1	:= (cAliasSD1)->(getArea())
	aAreaTmp	:= (cAliasTmpAjuste)->(getArea())

	Begin Sequence

		If !( verificarPesoAjuste("C") )
			Break
		Endif

		If !( verificarOutrosProdutos() )
			Break
		Endif

		lRet := .T.

	End Sequence

	RestArea(aAreaSD1)
	RestArea(aAreaTmp)

Return lRet

/*/
	Verificar outros produtos informados que não consta
	nos itens do documento de entrdada
/*/
Static Function verificarOutrosProdutos()
	Local lRet			:= .T.	as logical
	Local cCodProduto	:= ""	as character
	Local cLote			:= ""	as character
	Local cItemAjuste	:= ""	as character
	Local nQuantidade	:= 0	as numeric
	Local aAreaSD1		:= {}	as array
	Local aAreaTmp		:= {}	as array

	aAreaSD1	:= (cAliasSD1)->(getArea())
	aAreaTmp	:= (cAliasTmpAjuste)->(getArea())

	(cAliasTmpAjuste)->(dbSetOrder(2))
	(cAliasSD1)->(dbSetOrder(2))

	(cAliasTmpAjuste)->(dbGotop())
	While !(cAliasTmpAjuste)->(eof())

		cCodProduto 	:= (cAliasTmpAjuste)->FS_PRODUTO
		nPeso			:= (cAliasTmpAjuste)->FS_QUANT
		cLote			:= (cAliasTmpAjuste)->FS_LOTECTL
		cItemAjuste		:= (cAliasTmpAjuste)->FS_ITEM
		nQuantidade		:= (cAliasTmpAjuste)->FS_QUANT

		If !(cAliasSD1)->(dbSeek(cCodProduto))

			If ( nQuantidade ==  0)
				FWAlertWarning("Quantidade Produto '"+Alltrim(cCodProduto)+"' do Item '"+cItemAjuste+"' no ajuste é obrigatório.",cTitulo)
				lRet := .F.
				Exit
			Endif

			If Empty(cLote)
				FWAlertWarning("Lote Produto '"+Alltrim(cCodProduto)+"' do Item '"+cItemAjuste+"' no ajuste é obrigatório.",cTitulo)
				lRet := .F.
				Exit
			Endif

		Endif
		(cAliasTmpAjuste)->(dbSkip())
	EndDo

	aAreaSD1	:= (cAliasSD1)->(getArea())
	aAreaTmp	:= (cAliasTmpAjuste)->(getArea())

Return lRet

/*/
	Verificar se o peso informado no ajuste
	não estar acima do original
/*/
Static Function verificarPesoAjuste(cOpcao)
	Local lRet				:= .T.	as logical
	Local nPesoDocumento	:= 0	as numeric
	Local nPesoAjuste		:= 0	as numeric
	Local nRecord			:= 0	as numeric
	Local nPeso				:= 0	as numeric
	Local aAreaSD1			:= {}	as array
	Local aAreaTmp			:= {}	as array

	aAreaSD1	:= (cAliasSD1)->(getArea())
	aAreaTmp	:= (cAliasTmpAjuste)->(getArea())

	(cAliasTmpAjuste)->(dbSetOrder(1))

	(cAliasSD1)->(dbGotop())
	While !(cAliasSD1)->(eof())

		nPesoDocumento	:= nPesoDocumento + (cAliasSD1)->FS_PESO

		(cAliasSD1)->(dbSkip())
	EndDo

	If ( cOpcao == "C")

		nPesoAjuste		:= 0

		(cAliasTmpAjuste)->(dbGotop())
		While !(cAliasTmpAjuste)->(eof())
			nPesoAjuste := nPesoAjuste + (cAliasTmpAjuste)->FS_PESO
			(cAliasTmpAjuste)->(dbSkip())
		EndDo

		If ( nPesoAjuste >  nPesoDocumento)
			FWAlertWarning("Peso total do ajuste está maior que o peso Total documento.",cTitulo)
			lRet := .F.
		Endif
	Else
		nPesoAjuste		:= 0

		For nRecord := 1 To Len(oGridAjusteItens:aCols)
			If ( oGridAjusteItens:aCols[nRecord,POS_DELELTE_AJUSTE] == .F. )
				nPeso				:= oGridAjusteItens:aCols[nRecord,POS_PESO_AJUSTE]
				nPesoAjuste	:= nPesoAjuste + nPeso
			Endif
		Next

		If ( nPesoAjuste >  nPesoDocumento)
			FWAlertWarning("Peso total do ajuste está maior que o peso Total documento.",cTitulo)
			lRet := .F.
		Endif
	Endif

	RestArea(aAreaSD1)
	RestArea(aAreaTmp)

Return lRet

/*/
	Gerar Pedido de Venda
/*/
Static Function gerarPedidoVenda()
	Local lRet 				:= .T.	as logical
	Local aAreaSD1			:= {}	as array
	Local aAreaTmp			:= {}	as array
	Local aAutoCab			:= {}	as array
	Local aAutoItens		:= {}	as array

	Local cMsgErro			:= ""	as character
	Local aErrosLog			:= {}	as array
	Local nRegLog			:= 0	as numeric

	aAreaSD1	:= (cAliasSD1)->(getArea())
	aAreaTmp	:= (cAliasTmpAjuste)->(getArea())

	lMsErroAuto 	:= .F.
	lMsHelpAuto    	:= .T.
	lAutoErrNoFile	:= .T.

	aAutoCab	:= getAutoCab()
	aAutoItens 	:= getAutoItens()

	MSExecAuto({|x,y,z|Mata410(x,y,z)}, aAutoCab, aAutoItens, OPERACAO_INCLUSAO)

	If ( lMsErroAuto )

		cMsgErro := "Erro ao gerar pedido de venda." + CRLF
		aErrosLog := GetAutoGrLog()

		For nRegLog := 1 to Len(aErrosLog)
			cMsgErro += aErrosLog[nRegLog] + CRLF
		Next

		aAdd(aLogErro,{3,cMsgErro,"Erro ao gerar pedido de venda.",cNotaFiscal,cSerieNota,cCodFornecedor,cLojFornecedor})

		lRet := .F.
	Else
		cPedidoVenda := SC5->C5_NUM
	EndIf

	RestArea(aAreaSD1)
	RestArea(aAreaTmp)

Return lRet

/*/
	Atualizar o registro do refaturamento
/*/
Static Function atualizarRefaturamento(cTipo,cDocTransferencia)
	Local lRet					:= .T.		as logical
	Local aAreaSD1				:= {}		as array
	Local aAreaTmp				:= {}		as array
	Local cCodProduto			:= ""		as character
	Local cItem					:= ""		as character
	Local cFiltro				:= ""		as character
	Local cStatus				:= ""		as character
	Local cStatusRefaturamento	:= ""		as character
	Local dDataConfirmacao		:= CTOD("")	as date

	DEfault cDocTransferencia := ""

	aAreaSD1	:= (cAliasSD1)->(getArea())
	aAreaTmp	:= (cAliasTmpAjuste)->(getArea())

	dbSelectArea("SD1")
	SD1->(dbSetOrder(1))

	dbSelectArea("SZ7")
	SZ7->(dbSetOrder(1))

	dbSelectArea("SZ8")
	SZ8->(dbSetOrder(4))

	If ( cTipo == "S")
		cStatus := "1"
		cStatusRefaturamento := ""
		cPedidoVenda := ""
	Else
		cStatus := "2"
		dDataConfirmacao := dDataBase
		cStatusRefaturamento := "S"
	Endif

	(cAliasSD1)->(dbSetOrder(1))

	(cAliasTmpAjuste)->(dbGotop())

	While !(cAliasTmpAjuste)->(eof())

		cCodProduto := (cAliasTmpAjuste)->FS_PRODUTO
		cItem		:= (cAliasTmpAjuste)->FS_ITEM
		cFiltro		:= cNotaFiscal+cSerieNota+cCodFornecedor+cLojFornecedor+cCodProduto

		If ( SZ8->(dbSeek(FWxFilial("SZ8")+cItem+cCodProduto)))
			RecLock("SZ8",.F.)
			SZ8->Z8_STATUS 	:= cStatus
			SZ8->Z8_NUMPV	:= cPedidoVenda
			SZ8->(MsUnlock())
		Endif

		If SD1->(dbSeek(FWxFilial("SD1")+cFiltro))
			RecLock("SD1",.F.)
			SD1->D1_ZREFAT := cStatusRefaturamento
			SD1->(MsUnlock())
		Endif

		(cAliasTmpAjuste)->(dbSkip())

	Enddo

	If ( SZ7->(dbSeek(FWxFilial("SZ7")+cNumProcesso)))
		RecLock("SZ7", .F.)
		SZ7->Z7_STATUS 	:= cStatus
		SZ7->Z7_DTCONFI	:= dDataConfirmacao
		SZ7->Z7_NUMPV	:= cPedidoVenda
		SZ7->Z7_DOCTRAN	:= cDocTransferencia
		SZ7->(MsUnlock())
	Endif

	RestArea(aAreaSD1)
	RestArea(aAreaTmp)

Return lRet

/*/
	Ajusta os novos lotes para produtos
/*/
Static Function alterarLoteProdutosAjuste()
	Local lRet			:= .T.	as logical
	Local aAreaSD1		:= {}	as array
	Local aAreaTmp		:= {}	as array
	Local aProdutosLote	:= {}	as array
	Local nPos			:= 0 	as numeric
	Local nTamCampoLote	:= 0 	as numeric
	Local cLoteCtl		:= ""	as character
	Local cComplemento	:= ""	as character
	Local cTes			:= ""	as character

	aAreaSD1		:= (cAliasSD1)->(getArea())
	aAreaTmp		:= (cAliasTmpAjuste)->(getArea())
	nTamCampoLote	:= FWTamSX3("D1_LOTECTL")[1]

	(cAliasSD1)->(dbSetOrder(1))

	(cAliasTmpAjuste)->(dbGotop())

	While !(cAliasTmpAjuste)->(eof())

		(cAliasSD1)->(dbSeek( (cAliasTmpAjuste)->FS_ITEM))

		cLoteCtl := AvKey((cAliasTmpAjuste)->FS_LOTECTL,"D1_LOTECTL")

		cTes := (cAliasSD1)->FS_TES

		If SF4->(dbSeek(FWxFilial("SF4")+cTes)) .And. ( SF4->F4_ESTOQUE == "S") .And. ( SF4->F4_PODER3 == "N")

			If !((cAliasTmpAjuste)->FS_QUANT == 0 )
				nPos := aScan(aProdutosLote,{|x| x[1] == cLoteCtl})
				If ( nPos == 0)
					cComplemento	:= "A"
					aAdd(aProdutosLote,{cLoteCtl,cComplemento})
				Else
					cComplemento	:= Soma1(aProdutosLote[nPos,2])
					aProdutosLote[nPos,2] := cComplemento
				Endif
				If !Empty(cLoteCtl)
					cLoteCtl := Alltrim(SubStr(cLoteCtl,1,nTamCampoLote-1)) + cComplemento
				Endif
			Endif
		Endif

		RecLock(cAliasTmpAjuste,.F.)

		(cAliasTmpAjuste)->FS_LOTEDES := cLoteCtl
		(cAliasTmpAjuste)->(MsUnlock())

		(cAliasTmpAjuste)->(dbSkip())
	EndDo

	RestArea(aAreaSD1)
	RestArea(aAreaTmp)

Return lRet


/*/
	Mostra erro logs Grig
/*/
Static Function errosLogs()
	Local aDadosCampos	:= {}	as array

	aadd(aDadosCampos, {"TITERRO"   	, "Erro"   			, "C", 100, 00, ""})
	aadd(aDadosCampos, {"F1_DOC"		, "Nota Fiscal"		, "C", 009, 00, ""})
	aadd(aDadosCampos, {"F1_SERIE"    	, "Serie Nota"		, "C", 004, 00, ""})
	aadd(aDadosCampos, {"F1_FORNECE"	, "Fornecedor"		, "C", 006, 00, ""})
	aadd(aDadosCampos, {"F1_LOJA"		, "Loja" 			, "C", 004, 00, ""})

	lib.U_ShowLogGrid(cTitulo,aLogErro,aDadosCampos)

Return

