#include "protheus.ch"

#define		OPERACAO_ESTORNO	6
#define 	OPERACAO_INCLUSAO	3

namespace estoque.transferencia.refaturamento

/*/ {Protheus.doc} GerarTransferencia

Rotina de Refaturamento para gerar Transferencia

@type function
@author Elcilei Lopes - DsmSolutions
@since 10/12/2025
@version P12
@database ORACLE

@param - cDocTransferencia - character -  Numero do documento para gerar transferencia

@return - lRet - Logial - Retorna se a operação foi realizada com sucesso
/*/
User Function GerarTransferencia(cDocTransferencia)
	Local lRet 			    := .T.	as logical
	Local lContinua			:= .T.	as logical
	Local cDocumento	    := ""	as character
	Local cItem			    := ""	as character
	Local aAutoCab		    := {}	as array
	Local aLinha		    := {}	as array
	Local aAreaSD1		    := {}	as array
	Local aAreaTmp		    := {}	as array
	Local nQuantidade	    := 0	as numeric
	Local nItem			    := 0	as numeric
	Local nTamCampoItem	    := 0	as numeric
	Local cMsgErro		    := ""	as character
	Local cEndereco		    := ""	as character
	Local cProduto		    := ""	as character
	Local cLocal		    := ""	as character
	Local cLote			    := ""	as character
	Local aErrosLog		    := {}	as array
	Local nRegLog		    := 0	as numeric

	Private lMsErroAuto 	:= .F.	as logical
	Private lMsHelpAuto    	:= .T.	as logical
	Private lAutoErrNoFile	:= .T.	as logical

	Default cDocTransferencia	:= ""

	aAreaSD1	:= (cAliasSD1)->(getArea())
	aAreaTmp	:= (cAliasTmpAjuste)->(getArea())

	nTamCampoItem	:= FWTamSX3("D3_ITEM")[1]

	dbSelectArea("SB1")
	SB1->(dbSetOrder(1))

	dbSelectArea("SF4")
	SF4->(dbSetOrder(1))

	(cAliasSD1)->(dbSetOrder(1))

	(cAliasTmpAjuste)->(dbGotop())

	While !(cAliasTmpAjuste)->(eof())

		lContinua := .F.

		If SF4->(dbSeek(FWxFilial("SF4")+(cAliasTmpAjuste)->FS_PRODUTO)) .And. ( SF4->F4_ESTOQUE == "S") .And. ( SF4->F4_PODER3 == "N")
			lContinua := .T.
		Endif

		If ( lContinua == .T.)

			nQuantidade := (cAliasTmpAjuste)->FS_QUANT

			If !( nQuantidade == 0 )

				If Empty(aAutoCab)
					cDocumento  	    := getNumeroDocTransferencia()
					cDocTransferencia   := cDocumento
					aAdd(aAutoCab,{cDocumento,dDataBase})
				Endif

				nItem 		++
				cItem		:= StrZero(nItem,nTamCampoItem)
				aLinha		:= {}
				cEndereco	:= ""
				cProduto 	:= (cAliasTmpAjuste)->FS_PRODUTO
				cLocal		:= (cAliasTmpAjuste)->FS_LOCAL
				cLote		:= (cAliasTmpAjuste)->FS_LOTECTL

				(cAliasSD1)->(dbSeek( (cAliasTmpAjuste)->FS_ITEM))
				
				SB1->(dbSeek(FWxFilial("SB1")+(cAliasSD1)->FS_PRODUTO))
	
				aAdd(aLinha,{"ITEM"			, cItem							,Nil})
				aAdd(aLinha,{"D3_COD"		, (cAliasSD1)->FS_PRODUTO	, Nil})
				aAdd(aLinha,{"D3_DESCRI"	, (cAliasSD1)->FS_DESCRI	, Nil})
				aAdd(aLinha,{"D3_UM"		, SB1->B1_UM					, Nil})
				aAdd(aLinha,{"D3_LOCAL"		, (cAliasSD1)->FS_LOCAL	, Nil})

				If SB1->B1_LOCALIZ == "S"
					cEndereco := getEndereco((cAliasSD1)->FS_PRODUTO,(cAliasSD1)->FS_LOCAL,(cAliasSD1)->FS_LOTECTL)
				Endif
				aAdd(aLinha,{"D3_LOCALIZ"	, cEndereco						, Nil})

				SB1->(dbSeek(FWxFilial("SB1")+(cAliasTmpAjuste)->FS_PRODUTO))

				aAdd(aLinha,{"D3_COD"		, (cAliasTmpAjuste)->FS_PRODUTO	, Nil})
				aAdd(aLinha,{"D3_DESCRI"	, (cAliasTmpAjuste)->FS_DESCRI	, Nil})
				aAdd(aLinha,{"D3_UM"		, SB1->B1_UM 					, Nil})
				aAdd(aLinha,{"D3_LOCAL"		, (cAliasTmpAjuste)->FS_LOCAL	, Nil})
				aAdd(aLinha,{"D3_LOCALIZ"	, cEndereco						, Nil})
		
				aAdd(aLinha,{"D3_NUMSERI"	, ""							, Nil})
				aAdd(aLinha,{"D3_LOTECTL"	, (cAliasTmpAjuste)->FS_LOTECTL	, Nil})
				aAdd(aLinha,{"D3_NUMLOTE"	, ""							, Nil})
				aAdd(aLinha,{"D3_DTVALID"	, (cAliasTmpAjuste)->FS_DTVALID	, Nil})
				aAdd(aLinha,{"D3_POTENCI"	, 0								, Nil})
				aAdd(aLinha,{"D3_QUANT"		, (cAliasTmpAjuste)->FS_QUANT	, Nil})
				aAdd(aLinha,{"D3_QTSEGUM"	, 0								, Nil})
				aAdd(aLinha,{"D3_ESTORNO"	, ""							, Nil})
				aAdd(aLinha,{"D3_NUMSEQ"	, ""							, Nil})

				aAdd(aLinha,{"D3_LOTECTL"	, (cAliasTmpAjuste)->FS_LOTEDES	, Nil})
				aAdd(aLinha,{"D3_NUMLOTE"	, ""							, Nil})
				aAdd(aLinha,{"D3_DTVALID"	, (cAliasTmpAjuste)->FS_DTVALID , Nil})
				aAdd(aLinha,{"D3_ITEMGRD"	, ""							, Nil})

				aAdd(aLinha,{"D3_CODLAN"	, ""							, Nil})
				aAdd(aLinha,{"D3_CODLAN"	, ""							, Nil})

				aAdd(aAutoCab,aLinha)

			Endif
		Endif

		(cAliasTmpAjuste)->(dbSkip())
	EndDo

	If !Empty(aAutoCab)

		MSExecAuto({|x,y| mata261(x,y)},aAutoCab,OPERACAO_INCLUSAO)

		If ( lMsErroAuto == .T.)
			cMsgErro := "Erro ao gerar transferencia." + CRLF
			aErrosLog := GetAutoGrLog()

			For nRegLog := 1 to Len(aErrosLog)
				cMsgErro += aErrosLog[nRegLog] + CRLF
			Next

			aAdd(aLogErro,{3,cMsgErro,"Erro ao gerar transferencia.",cNotaFiscal,cSerieNota,cCodFornecedor,cLojFornecedor})

			lRet := .F.
		Else
			//cDocTransferencia := SD3->D3_DOC
		EndIf

	Endif

	RestArea(aAreaSD1)
	RestArea(aAreaTmp)

Return lRet

/*/
	Verificar endereco do produto
/*/
Static Function getEndereco(cProduto,cLocal,cLote)
	Local cRet		:= ""				as character
	Local aAreaBF	:= SBF->(getArea())	as array

	dbSelectArea("SBF")
	SBF->(dbSetOrder(2))

	If SBF->(dbSeek(FWxFilial("SBF")+cProduto+cLocal+cLote))
		cRet := SBF->BF_LOCALIZ
	Endif

	RestArea(aAreaBF)
Return cRet

/*/
	Buscar proximo numero documento transferencia
/*/
Static Function getNumeroDocTransferencia()
	Local cRet		:= ""	as character
	Local aAreaSD3	:= {}	as array
	Local lContinua	:= .T.	as logical

	aAreaSD3 := SD3->(getArea())

	dbSelectArea("SD3")
	SD3->(dbSetOrder(2))

	While lContinua
		cRet := GetSxeNum("SD3","D3_DOC")
		If !SD3->(dbSeek(FWxFilial("SD3")+cRet))
			lContinua := .F.
		Else
			ConfirmSX8()
		Endif

	Enddo

	RestArea(aAreaSD3)

Return cRet
