#include "tlpp-core.th"
#include "protheus.ch"

#define CRLF chr(13) + chr(10)

namespace faturamento.pedido

/*/
{Protheus.doc} origemProdutoEntrada

Gatilho no pedido de venda para buscar a origem do produto da NF de entrada

@type Function
@author Gabriel Goncalves
@since 24/11/2024
@version P12
@database MSSQL
/*/
User Function origemProdutoEntrada()
	Local cQuery			:= ""	as character
	Local cAliasOrigem		:= ""	as character
	Local nPosProduto		:= aScan(Aheader,{|x| AllTrim(x[2]) == "C6_PRODUTO"})	as integer
	Local nPosClasfis		:= aScan(Aheader,{|x| AllTrim(x[2]) == "C6_CLASFIS"})	as integer
	Local cClassificacao	:= ""	as character
	Local cCharClass		:= ""	as character
	Local nRecord			:= 0	as integer
	Local nLinhaProduto		:= 0	as integer

	Private cCodigoProduto	:= ""	as character
	Private cLoteProduto	:= ""	as character
	Private cIdBobina		:= ""	as character

	aColsTmp := aCols

	cIdBobina := Iif(Inclui == .T.,M->C5_ZLOTCTL,SC5->C5_ZLOTCTL)

	For nRecord := 1 To Len(aCols)
		cCodigoProduto		:= aCols[nRecord,nPosProduto]
		cClassificacao		:= ""

		If !Empty(cCodigoProduto)
			cQuery := queryBuscarOrigemNF()
			MPSysOpenQuery( cQuery, cAliasOrigem := GetNextAlias() )

			DbSelectArea(cAliasOrigem)
			(cAliasOrigem)->(DbGoTop())
			If !((cAliasOrigem)->(EoF()))
				cClassificacao := (cAliasOrigem)->D1_CLASFIS
				nLinhaProduto := nRecord
				If !Empty(cClassificacao)
					Exit
				Endif
			EndIf

			(cAliasOrigem)->(DbCloseArea())
		EndIf
	Next nRecord

	If !Empty(cClassificacao)
		cCharClass := SubStr(cClassificacao,1,1)
		For nRecord := 1 To Len(aCols)
			If ( nLinhaProduto == nRecord )
				aCols[nRecord,nPosClasfis] := cClassificacao	
			Else
				aCols[nRecord,nPosClasfis] := cCharClass + SubStr(aCols[nRecord,nPosClasfis],2,3)
			Endif
		Next nRecord
	Endif

Return

/*/
	Query buscar origem produto da NF
/*/
Static Function queryBuscarOrigemNF()
	Local cQuery	:= ""	as character

	cQuery += " SELECT " + CRLF
	cQuery += "        D1_CLASFIS"		+ CRLF

	cQuery += " FROM " + CRLF
	cQuery += "     " + RetSQLTab("SD1") + CRLF

	cQuery += " WHERE " + CRLF
	cQuery += " 	    1 = 1 " + CRLF
	cQuery += "	 		AND " + RetSqlFil("SD1") + CRLF
	cQuery += " 		AND ( D1_TIPO = 'N' OR D1_TIPO = 'B' ) " + CRLF
	cQuery += " 		AND D1_COD		= '"+AllTrim(cCodigoProduto)+"'" + CRLF
	cQuery += " 		AND D1_LOTECTL	= '"+AllTrim(cIdBobina)+"'" + CRLF
	cQuery += "	    	AND " + RetSqlDel("SD1") + CRLF

Return cQuery
