#include "totvs.ch"
#include "topconn.ch"
#include "tbiconn.ch"
#include "tbicode.ch"

namespace fiscal.complementoFiscal

/*/ {Protheus.doc} MGP022_CENTRASA_SMUD22_DF_BUSCA NF COMPLEMENTO ICMS
Nome:       Módulo	Compras
Processo:   Faturamento
Subprocesso:        Verificação NF de Complemento ICMS
Número e Nome DF:	MGP022_CENTRASA_SMUD22_DF_BUSCA NF COMPLEMENTO ICMS

@type function/gatilho campo C6_NFORI
@author Helerson - DSM
@since 24/09/2024
@version P12
@database TCLOUD SQL
/*/

User Function buscaIcms()
	Local lRetorno	:= .T.	as logical
	Local cMensagem	:= ""	as character
	Local cC6Oper3	:= AllTrim(GetMV("ZV_C6OPER3"))	as character

	Private cAliasICMS	:= GetNextAlias()	as character

	buscaComplementoICMS()
	
	DbSelectArea(cAliasICMS)
	(cAliasICMS)->(DbGoTop())
	While !(cAliasICMS)->(EoF())
		If !(AllTrim((cAliasICMS)->C6_OPER) $ cC6Oper3)
			lRetorno	:= .F.
			cMensagem	:= "NF de devolução deverá calcular ICMS, e por isso deve usar o Tipo de Operação " + cC6Oper3 + "."

			Help(,,"HELP-Centrasa",,cMensagem,1,0)
			Exit
		EndIf

		(cAliasICMS)->(DbSkip())
	EndDo

	(cAliasICMS)->(DbCloseArea())
Return lRetorno

/*
	Buscar dados de complemento de ICMS
*/
Static Function buscaComplementoICMS()
	Local cQuery	:= ""	as character

	cQuery	:= getQueryBuscaComplementoICMS()

	MPSysOpenQuery( cQuery, cAliasICMS )
Return

/*
	Monta a query para buscar dados a faturar
*/
Static Function getQueryBuscaComplementoICMS()
	Local cQuery		:= ""	as character

	cQuery := "	SELECT " + CRLF
	cQuery += "			C6_ITEM " + CRLF
	cQuery += "			,C6_PRODUTO " + CRLF
	cQuery += "			,C6_OPER " + CRLF
	cQuery += "			,C6_TES " + CRLF

	cQuery += "	FROM " + CRLF
	cQuery += "		" + RetSQLTab("SC5") + CRLF

	cQuery += "	INNER JOIN " + CRLF
	cQuery += "		" + RetSQLTab("SC6") + CRLF
	cQuery += "			ON" + CRLF
	cQuery += "			" + RetSqlFil("SC6") + CRLF
	cQuery += "			AND C6_NUM		= C5_NUM " + CRLF
	cQuery += "			AND " + RetSqlDel("SC6") + CRLF

	cQuery += "	INNER JOIN " + CRLF
	cQuery += "		" + RetSQLTab("SF4") + CRLF
	cQuery += "			ON" + CRLF
	cQuery += "			" + RetSqlFil("SF4") + CRLF
	cQuery += "			AND F4_CODIGO	= C6_TES " + CRLF
	cQuery += "			AND F4_PODER3	= 'D' " + CRLF
	cQuery += "			AND " + RetSqlDel("SF4") + CRLF

	cQuery += "	INNER JOIN " + CRLF
	cQuery += "		" + RetSQLTab("SD1") + CRLF
	cQuery += "			ON" + CRLF
	cQuery += "			" + RetSqlFil("SD1") + CRLF
	cQuery += "			AND D1_NFORI	= C6_NFORI " + CRLF
	cQuery += "			AND D1_SERIORI	= C6_SERIORI " + CRLF
	cQuery += "			AND D1_ITEMORI	= C6_ITEMORI " + CRLF
	cQuery += "			AND D1_TIPO		= 'I' " + CRLF
	cQuery += "			AND " + RetSqlDel("SD1") + CRLF

	cQuery += "	WHERE " + CRLF
	cQuery += "			1 = 1 " + CRLF
	cQuery += "			AND " + RetSqlFil("SC5") + CRLF
	cQuery += "			AND C5_NUM		= '"+SC5->C5_NUM+"' " + CRLF
	cQuery += "			AND " + RetSqlDel("SC5") + CRLF
Return cQuery
