#include "tlpp-core.th"
#include "protheus.ch"

#define CRLF chr(13) + chr(10)

namespace producao.op

/*/{Protheus.doc} apontamentoBlankChapa

Apontamento Blank/Chapa

@type Function
@author Gabriel Goncalves
@since 24/11/2024
@version P12
@database MSSQL

/*/
User Function apontamentoBlankChapa(cAlias, nRegistro)
	Private oTelaApontamento		as object
	Private oLayerApontamento		as object
	Private oGridApontamento		as object
	Private oListaBotoes			as object

	Private aOperacoes				:= {}	as array
	Private aHeader				 	:= {}	as array
	Private aCols					:= {}	as array
	Private cAliasTela				:= cAlias	as character
	Private nRegistroTela			:= nRegistro	as integer

	Private cEspessuraLIE			:= ""	as character
	Private cEspessuraLSE			:= ""	as character
	Private cRebarbaLIE				:= ""	as character
	Private cRebarbaLSE				:= ""	as character
	Private cComprimentoMenorLIE	:= ""	as character
	Private cComprimentoMenorLSE	:= ""	as character
	Private cComprimentoMaiorLIE	:= ""	as character
	Private cComprimentoMaiorLSE	:= ""	as character
	Private cLarguraLIE				:= ""	as character
	Private cLarguraLSE				:= ""	as character
	Private cAngulo1LIE				:= ""	as character
	Private cAngulo1LSE				:= ""	as character
	Private cAngulo2LIE				:= ""	as character
	Private cAngulo2LSE				:= ""	as character
	Private cFlechaLIE				:= ""	as character
	Private cFlechaLSE				:= ""	as character

	montaTelaApontamento()
Return

/*
	Funcao caixao de dialogo para montagem da tela inicial
*/
Static Function montaTelaApontamento()
	Local aSize	:= MsAdvSize() 	as array //Retorna dados sobre tamanho da tela

	cLabel:="Apontamento Blank/Chapa "+AllTrim((cAliasTela)->TMP_ORDEM)+" - Cod Insp:" +AllTrim((cAliasTela)->C5_ZINSPE)+" - Id:"+AllTrim((cAliasTela)->C5_ZLOTCTL);
		+" - Cod Prod:"+AllTrim((cAliasTela)->C2_PRODUTO) +" - Desc Prod:"+AllTrim((cAliasTela)->TMP_DESPRD) ;
		+" - Nome Cli:"+ AllTrim((cAliasTela)->A1_NOME)

	oTelaApontamento	:= MSDialog():New(0, 0, aSize[6], aSize[5], cLabel, , , .F., , , , , , .T., , , .T.) //Monta tela principal
	oTelaApontamento:lMaximized := .T.

	oLayerApontamento	:= FWLayer():New() //Cria paineis para segregar a tela
	oLayerApontamento:Init(oTelaApontamento, .F.) //Relaciona paineis com Objeto pai (dialog principal)

	//Cria as linhas para os Paineis
	//oLayerApontamento:AddLine("SUPERIOR"	, 022, .T.)
	oLayerApontamento:AddLine("CENTRAL"		, 085, .T.)
	oLayerApontamento:AddLine("INFERIOR"	, 015, .T.)

	//Cria as colunas no Painel Superior
	//oLayerApontamento:AddCollumn("SUP_A"	, 100, .T., "SUPERIOR")

	//Cria as colunas no Painel Central
	oLayerApontamento:AddCollumn("CENT_A"	, 100, .T., "CENTRAL")

	//Cria as colunas no Painel Inferior
	oLayerApontamento:AddCollumn("INF_A"	, 100, .T., "INFERIOR")
	//oLayerApontamento:AddCollumn("INF_B"	, 012, .T., "INFERIOR")

	//Cria e posiciona as janelas nos Paineis Superiores
	//oLayerApontamento:AddWindow("SUP_A"		, "CABECALHO"	, "Dados do Apontamento"	, 100, .F., .F., , "SUPERIOR" , )

	//Cria e posiciona as janelas nos Paineis Centrais
	oLayerApontamento:AddWindow("CENT_A"	, "OPERACOES"		, "Operacoes"				, 100, .F., .F., , "CENTRAL" , )

	//Cria e posiciona as janelas nos Paineis Inferiores
	oLayerApontamento:AddWindow("INF_A"		, "BOTOES"			, "Acoes"				, 100, .F., .F., , "INFERIOR" , )
	//oLayerApontamento:AddWindow("INF_B"		, "LOTE"		, "Acoes"					, 100, .F., .F., , "INFERIOR" , )

	montaListaOperacoes()
	montaBotoes()

	ACTIVATE MSDIALOG oTelaApontamento CENTERED
Return

/*
	Monta Lista de Itens
*/
Static Function montaListaOperacoes()
	Local aAlter		:= {}
	Local nOpc         	:= GD_INSERT+GD_UPDATE+GD_DELETE			// GD_INSERT+GD_UPDATE+GD_DELETE
	Local cLinOk       	:= "producao.op.u_validaLinhaBlankChapa()"		// Funcao executada para validar o contexto da linha atual do aCols
	Local cTudoOk      	:= "AllwaysTrue"		// Funcao executada para validar o contexto geral da MsNewGetDados (todo aCols)
	Local nMax 			:= 99					// Numero maximo de linhas permitidas. Valor padrao 99
	Local cFieldOk 		:= "producao.op.u_validaFieldBlankChapa()"		// Funcao executada na validacao do campo
	Local cSuperDel 	:= ""					// Funcao executada quando pressionada as teclas <Ctrl>+<Delete>
	Local cDelOk 		:= "producao.op.u_validaDeleteLinhaBlankChapa()"		// Funcao executada para validar a exclusao de uma linha do aCols
	Local bChange		:= { ||  }
	Local cTela			:= NIL
	Local cOperacoes	:= "ST=SETUP;SD=SHUTDOWN"
	Local nOperacao		:= 0

	For nOperacao := 1 To 99
		cOperacoes	+= ";"+ StrZero(nOperacao, 2) + "=" + StrZero(nOperacao, 2)
	Next nOperacao

	aAdd( aHeader,	{"Operacao"					,"XX_OPERAC"	,""					,02,0,"AllwaysTrue()","","C","","R",cOperacoes,"",""}	)
	aAdd( aHeader,	{"Data"						,"XX_DATA"		,""					,08,0,"AllwaysTrue()","","D","","R","","",""}	)
	aAdd( aHeader,	{"Horario"					,"XX_HORARIO"	,"99:99"			,05,0,"AllwaysTrue()","","C","","R","","Time()",""}	)
	aAdd( aHeader,	{"Cod.Micrometro"			,"XX_CODMIC"	,""					,06,0,"AllwaysTrue()","","C","ZQM2","R","","",""}	)
	aAdd( aHeader,	{"Espessura(mm)"			,"XX_ESPESSU"	,""					,30,0,"AllwaysTrue()","","C","","R","","",""}	)
	aAdd( aHeader,	{"Rebarba(mm)"				,"XX_REBARBA"	,""					,30,0,"AllwaysTrue()","","C","","R","","",""}	)
	aAdd( aHeader,	{"Cod.Paquimetro/Trena"		,"XX_CODPAQ1"	,""					,06,0,"AllwaysTrue()","","C","ZQM2","R","","",""}	)
	aAdd( aHeader,	{"Comprimento.Menor(mm)"	,"XX_COMPMEN"	,""					,42,0,"AllwaysTrue()","","C","","R","","",""}	)
	aAdd( aHeader,	{"Comprimento.Maior(mm)"	,"XX_COMPMAI"	,""					,42,0,"AllwaysTrue()","","C","","R","","",""}	)
	aAdd( aHeader,	{"Cod.Paquimetro/Trena"		,"XX_CODPAQ2"	,""					,06,0,"AllwaysTrue()","","C","ZQM2","R","","",""}	)
	aAdd( aHeader,	{"Largura(mm)"				,"XX_LARGURA"	,""					,39,0,"AllwaysTrue()","","C","","R","","",""}	)
	aAdd( aHeader,	{"Cod.Transferidor.Grau"	,"XX_CODTRAN"	,""					,06,0,"AllwaysTrue()","","C","ZQM2","R","","",""}	)
	aAdd( aHeader,	{"Angulo( )"				,"XX_ANGULO1"	,""					,27,0,"AllwaysTrue()","","C","","R","","",""}	)
	aAdd( aHeader,	{"Angulo( )"				,"XX_ANGULO2"	,""					,27,0,"AllwaysTrue()","","C","","R","","",""}	)
	aAdd( aHeader,	{"Cod.Mesa"					,"XX_CODMESA"	,""					,06,0,"AllwaysTrue()","","C","ZQM2","R","","",""}	)
	aAdd( aHeader,	{"Cod.Regua"				,"XX_CODREGU"	,""					,06,0,"AllwaysTrue()","","C","ZQM2","R","","",""}	)
	aAdd( aHeader,	{"Cod.Paquimetro"			,"XX_CODPAQ3"	,""					,06,0,"AllwaysTrue()","","C","ZQM2","R","","",""}	)
	aAdd( aHeader,	{"Flecha(mm)"				,"XX_FLECHA"	,""					,27,0,"AllwaysTrue()","","C","","R","","",""}	)
	aAdd( aHeader,	{"Aspecto.Visual"			,"XX_ASPVISU"	,""					,01,0,"AllwaysTrue()","","C","","R","S=OK;N=N OK","",""}	)
	aAdd( aHeader,	{"Aprovado/Reprovado"		,"XX_APROVAD"	,""					,01,0,"AllwaysTrue()","","C","","R","D=Digitando;A=Aprovado;R=Reprovado","'D'",""}	)
	aAdd( aHeader,	{"Qtde.Pecas"				,"XX_QTDPECA"	,"9,999,999.9999"	,12,4,"AllwaysTrue()","","N","","R","","",""}	)
	aAdd( aHeader,	{"Peso.Bruto"				,"XX_PESOBRU"	,"9,999,999.9999"	,12,4,"AllwaysTrue()","","N","","R","","",""}	)
	aAdd( aHeader,	{"Peso.Liquido"				,"XX_PESOLIQ"	,"9,999,999.9999"	,12,4,"AllwaysTrue()","","N","","R","","",""}	)
	aAdd( aHeader,	{"Lote Empenho"				,"XX_LOTEEMP"	,""					,13,0,"AllwaysTrue()","","C","","R","","",""}	)
	aAdd( aHeader,	{"Conforme.Solicitado?"		,"XX_SOLICIT"	,""					,01,0,"AllwaysTrue()",""                                   ,"C","","R","S=Sim;N=Nao","",""}	)
	aAdd( aHeader,	{"RecnoSZ3"					,;
		"XX_RECNO"		,;
		""					,;
		15,;
		0,;
		"AllwaysTrue()",;
		GetSX3Cache("AB8_FILIAL","X3_USADO") ,;
		"N",;
		"",;
		"V",;
		"",;
		"",;
		".F.",;
		"V",;
		"",;
		"",;
		".F."}	)

	aAdd( aHeader,	{"Apontado?"				,"XX_APONTOK"	,""					,01,0,"AllwaysTrue()","","C","","R","S=Sim;N=Nao","'N'",""}	)

	aAlter		:= {	"XX_OPERAC", "XX_DATA", "XX_HORARIO",;
		"XX_CODMIC", "XX_ESPESSU", "XX_REBARBA",;
		"XX_CODPAQ1", "XX_COMPMEN", "XX_COMPMAI",;
		"XX_CODPAQ2", "XX_LARGURA", "XX_CODTRAN",;
		"XX_ANGULO1", "XX_ANGULO2", "XX_CODMESA",;
		"XX_CODREGU", "XX_CODPAQ3", "XX_FLECHA",;
		"XX_ASPVISU", "XX_QTDPECA",;
		"XX_PESOBRU", "XX_PESOLIQ",;
		"XX_SOLICIT", "XX_RECNO";
		}

	zeraArrayOperacoes()
	SetKey(VK_F4, { ||  getLote(u_getLoteOp(AllTrim((cAliasTela)->TMP_ORDEM)) ,"01",substr((cAliasTela)->TMP_ORDEM,1,6)) } )// escolha de lote

	oGridApontamento := MsNewGetDados():New(1,1,240,185,nOpc,cLinOk,cTudoOk,/*cIniCpos*/,;
		aAlter,/*nFreeze*/,nMax,cFieldOk,cSuperDel,cDelOk,oLayerApontamento:GetWinPanel("CENT_A", "OPERACOES", "CENTRAL"),aHeader,aCols,bChange,cTela)

	oGridApontamento:SetArray( aOperacoes )
	oGridApontamento:oBrowse:align := CONTROL_ALIGN_ALLCLIENT
Return

/*
	Monta grupo de botoes na tela
*/
Static Function montaBotoes()
	Local nPosVert		:= 0	as integer
	Local oBotaoSalvar			as object
	Local oBotaoGravar			as object
	Local oBotaoConhecimento	as object
	Local oBotaoObservacao		as object
	Local oBotaoSair			as object
	Local oBotaoEtiqueta		as object
	Local nTamanhoBotao	:= 90	as integer

	oListaBotoes	:= oLayerApontamento:GetWinPanel("INF_A", "BOTOES", "INFERIOR")

	oBotaoSalvar		:= TButton():New( nPosVert	,	0							,	"Salvar"			, oListaBotoes, {|| if (u_validaLinhaBlanktudook('S'),salvaApontamento(),'')}	, nTamanhoBotao, 020, , , , .T., , , , , , )
	oBotaoGravar		:= TButton():New( nPosVert	,	nTamanhoBotao + 5			,	"Aprovação Final"	, oListaBotoes, {|| if (u_validaLinhaBlanktudook('A'),processaApontamento(),'')}	, nTamanhoBotao, 020, , , , .T., , , , , , )
	oBotaoEtiqueta		:= TButton():New( nPosVert	,	( nTamanhoBotao + 5 ) * 2	,	"Etiqueta"			, oListaBotoes, {|| producao.etiquetas.u_etiquetaAberturaOp(AllTrim((cAliasTela)->TMP_ORDEM))}	, nTamanhoBotao, 020, , , , .T., , , , , , )
	oBotaoConhecimento	:= TButton():New( nPosVert	,	( nTamanhoBotao + 5 ) * 3	,	"Conhecimento"		, oListaBotoes, {|| estoque.conhecimento.u_Produto(cAliasTela,nil,nil)}	, nTamanhoBotao, 020, , , , .T., , , , , , )
	oBotaoObservacao	:= TButton():New( nPosVert	,	( nTamanhoBotao + 5 ) * 4	,	"Observação"		, oListaBotoes, {|| ShowLog((cAliasTela)->C2_ZOBS)}	, nTamanhoBotao, 020, , , , .T., , , , , , )
	oBotaoSair			:= TButton():New( nPosVert	,	( nTamanhoBotao + 5 ) * 5	,	"Sair"				, oListaBotoes, {|| cancelaApontamento()}	, nTamanhoBotao, 020, , , , .T., , , , , , )
Return

/*
	Cancela o apontamento
*/
Static Function cancelaApontamento()
	oTelaApontamento:End()
Return

/*
	Zera os arrays com os dados dos produtos e lotes
*/
Static Function zeraArrayOperacoes()
	Local nPosHeader	:= 0
	Local cTipoDado		:= ""

	aOperacoes		:= {{}}

	//aAdd(aOperacoes		, {" ", StoD(""), " ", " ", 0, 0, " ", 0, 0, " ", 0, " ", 0, 0, " ", " ", " ", 0, " ", " ", 0, 0, 0, " ", .F.})
	For nPosHeader := 1 To Len(aHeader)
		cTipoDado	:= aHeader[nPosHeader][8]

		If cTipoDado == "C"
			aAdd(aOperacoes[1]	, Space(aHeader[nPosHeader][4]))
		ElseIf cTipoDado == "N"
			aAdd(aOperacoes[1]	, 0)
		ElseIf cTipoDado == "D"
			aAdd(aOperacoes[1]	, StoD(""))
		EndIf
	Next nPosHeader

	aAdd(aOperacoes[1]	, .F.)

	buscarLimitesMedicoes()
	buscarApontamentos()
Return

/*
	Busca limites das medicoes
*/
Static Function buscarLimitesMedicoes()
	Local cQuery	:= ""	as character

	cQuery := 	queryBuscarLimitesMedicoes()

	MPSysOpenQuery( cQuery, cAlias := GetNextAlias() )

	(cAlias)->(DbGoTop())
	While (cAlias)->(!EoF())
		If AllTrim((cAlias)->QP1_DESCPO) == "ESPESSURA"
			aOperacoes[1][5]	:= "N "+AllTrim((cAlias)->QP7_NOMINA)+"  |  LI "+AllTrim((cAlias)->QP7_LIE)+"  |  LS "+AllTrim((cAlias)->QP7_LSE)
			cEspessuraLIE		:= AllTrim((cAlias)->QP7_LIE)
			cEspessuraLSE		:= AllTrim((cAlias)->QP7_LSE)
		ElseIf AllTrim((cAlias)->QP1_DESCPO) == "REBARBA"
			aOperacoes[1][6]	:= "N "+AllTrim((cAlias)->QP7_NOMINA)+"  |  LI "+AllTrim((cAlias)->QP7_LIE)+"  |  LS "+AllTrim((cAlias)->QP7_LSE)
			cRebarbaLIE			:= AllTrim((cAlias)->QP7_LIE)
			cRebarbaLSE			:= AllTrim((cAlias)->QP7_LSE)
		ElseIf AllTrim((cAlias)->QP1_DESCPO) == "COMPRIMENTO"
			aOperacoes[1][8]		:= "N "+AllTrim((cAlias)->QP7_NOMINA)+"  |  LI "+AllTrim((cAlias)->QP7_LIE)+"  |  LS "+AllTrim((cAlias)->QP7_LSE)
			cComprimentoMenorLIE	:= AllTrim((cAlias)->QP7_LIE)
			cComprimentoMenorLSE	:= AllTrim((cAlias)->QP7_LSE)
		ElseIf AllTrim((cAlias)->QP1_DESCPO) == "COMPRIMENTO 2"
			aOperacoes[1][9]		:= "N "+AllTrim((cAlias)->QP7_NOMINA)+"  |  LI "+AllTrim((cAlias)->QP7_LIE)+"  |  LS "+AllTrim((cAlias)->QP7_LSE)
			cComprimentoMaiorLIE	:= AllTrim((cAlias)->QP7_LIE)
			cComprimentoMaiorLSE	:= AllTrim((cAlias)->QP7_LSE)
		ElseIf AllTrim((cAlias)->QP1_DESCPO) == "LARGURA"
			aOperacoes[1][11]	:= "N "+AllTrim((cAlias)->QP7_NOMINA)+"  |  LI "+AllTrim((cAlias)->QP7_LIE)+"  |  LS "+AllTrim((cAlias)->QP7_LSE)
			cLarguraLIE			:= AllTrim((cAlias)->QP7_LIE)
			cLarguraLSE			:= AllTrim((cAlias)->QP7_LSE)
		ElseIf AllTrim((cAlias)->QP1_DESCPO) == "ANGULO"
			aOperacoes[1][13]	:= "N "+AllTrim((cAlias)->QP7_NOMINA)+"  |  LI "+AllTrim((cAlias)->QP7_LIE)+"  |  LS "+AllTrim((cAlias)->QP7_LSE)
			cAngulo1LIE			:= AllTrim((cAlias)->QP7_LIE)
			cAngulo1LSE			:= AllTrim((cAlias)->QP7_LSE)
		ElseIf AllTrim((cAlias)->QP1_DESCPO) == "ANGULO 2"
			aOperacoes[1][14]	:= "N "+AllTrim((cAlias)->QP7_NOMINA)+"  |  LI "+AllTrim((cAlias)->QP7_LIE)+"  |  LS "+AllTrim((cAlias)->QP7_LSE)
			cAngulo2LIE			:= AllTrim((cAlias)->QP7_LIE)
			cAngulo2LSE			:= AllTrim((cAlias)->QP7_LSE)
		ElseIf AllTrim((cAlias)->QP1_DESCPO) == "FLECHA"
			aOperacoes[1][18]	:= "N "+AllTrim((cAlias)->QP7_NOMINA)+"  |  LI "+AllTrim((cAlias)->QP7_LIE)+"  |  LS "+AllTrim((cAlias)->QP7_LSE)
			cFlechaLIE			:= AllTrim((cAlias)->QP7_LIE)
			cFlechaLSE			:= AllTrim((cAlias)->QP7_LSE)
		EndIf

		(cAlias)->(DbSkip())
	EndDo

	(cAlias)->(DbCloseArea())
Return

/*
	Query dos limites de medicao
*/
Static Function queryBuscarLimitesMedicoes()
	Local cQuery	:= ""	as character

	cQuery += " SELECT * FROM ( " + CRLF

	cQuery += " SELECT " + CRLF
	cQuery += "        QP7_ENSAIO "		+ CRLF
	cQuery += "        ,QP7_NOMINA "	+ CRLF
	cQuery += "        ,QP7_LIE "		+ CRLF
	cQuery += "        ,QP7_LSE "		+ CRLF
	cQuery += "        ,QP7_REVI "		+ CRLF
	cQuery += "        ,QP1_DESCPO "	+ CRLF

	cQuery += " FROM " + CRLF
	cQuery += "     " + RetSQLTab("SC2") + CRLF

	cQuery += " INNER JOIN " + CRLF
	cQuery += "     " + RetSQLTab("QP7") + CRLF
	cQuery += "     	ON" + CRLF
	cQuery += " 	    " + RetSqlFil("QP7") + CRLF
	cQuery += " 	    AND QP7_PRODUT = C2_PRODUTO" + CRLF
	cQuery += " 	    AND QP7_REVI = C2_REVI " + CRLF
	cQuery += "	    	AND " + RetSqlDel("QP7") + CRLF

	cQuery += " INNER JOIN " + CRLF
	cQuery += "     " + RetSQLTab("QP1") + CRLF
	cQuery += "     	ON" + CRLF
	cQuery += " 	    " + RetSqlFil("QP1") + CRLF
	cQuery += " 	    AND QP1_ENSAIO = QP7_ENSAIO" + CRLF
	cQuery += "	    	AND " + RetSqlDel("QP1") + CRLF

	cQuery += " WHERE " + CRLF
	cQuery += " 	    1 = 1 " + CRLF
	cQuery += "	 		AND " + RetSqlFil("SC2") + CRLF
	cQuery += " 		AND C2_NUM||C2_ITEM||C2_SEQUEN  = '"+AllTrim((cAliasTela)->TMP_ORDEM)+"'" + CRLF
	cQuery += "	    	AND " + RetSqlDel("SC2") + CRLF

	cQuery += " UNION ALL " + CRLF

	cQuery += " SELECT " + CRLF
	cQuery += "        QP8_ENSAIO QP7_ENSAIO "	+ CRLF
	cQuery += "        ,'' QP7_NOMINA "	+ CRLF
	cQuery += "        ,'' QP7_LIE "	+ CRLF
	cQuery += "        ,'' QP7_LSE "	+ CRLF
	cQuery += "        ,QP8_REVI QP7_REVI "	+ CRLF
	cQuery += "        ,QP1_DESCPO "	+ CRLF

	cQuery += " FROM " + CRLF
	cQuery += "     " + RetSQLTab("SC2") + CRLF

	cQuery += " INNER JOIN " + CRLF
	cQuery += "     " + RetSQLTab("QP8") + CRLF
	cQuery += "     	ON" + CRLF
	cQuery += " 	    " + RetSqlFil("QP8") + CRLF
	cQuery += " 	    AND QP8_PRODUT = C2_PRODUTO" + CRLF
	cQuery += " 	    AND QP8_REVI = C2_REVI " + CRLF
	cQuery += "	    	AND " + RetSqlDel("QP8") + CRLF

	cQuery += " INNER JOIN " + CRLF
	cQuery += "     " + RetSQLTab("QP1") + CRLF
	cQuery += "     	ON" + CRLF
	cQuery += " 	    " + RetSqlFil("QP1") + CRLF
	cQuery += " 	    AND QP1_ENSAIO = QP8_ENSAIO" + CRLF
	cQuery += "	    	AND " + RetSqlDel("QP1") + CRLF

	cQuery += " WHERE " + CRLF
	cQuery += " 	    1 = 1 " + CRLF
	cQuery += "	 		AND " + RetSqlFil("SC2") + CRLF
	cQuery += " 		AND C2_NUM||C2_ITEM||C2_SEQUEN  = '"+AllTrim((cAliasTela)->TMP_ORDEM)+"'" + CRLF
	cQuery += "	    	AND " + RetSqlDel("SC2") + CRLF

	cQuery += " )T " + CRLF
	cQuery += " ORDER BY QP7_ENSAIO " + CRLF
Return cQuery

/*
	Busca apontamentos existentes
*/
Static Function buscarApontamentos()
	Local cQuery	:= ""	as character

	cQuery := 	queryBuscarApontamentos()

	MPSysOpenQuery( cQuery, cAlias := GetNextAlias() )

	(cAlias)->(DbGoTop())
	While (cAlias)->(!EoF())
		aAdd(aOperacoes	,{	(cAlias)->Z3_OPERAC,;
			StoD((cAlias)->Z3_DATA),;
			(cAlias)->Z3_HORARIO,;
			(cAlias)->Z3_CODMIC,;
			(cAlias)->Z3_ESPESSU,;
			(cAlias)->Z3_REBARBA,;
			(cAlias)->Z3_CODPAQ1,;
			(cAlias)->Z3_COMPMEN,;
			(cAlias)->Z3_COMPMAI,;
			(cAlias)->Z3_CODPAQ2,;
			(cAlias)->Z3_LARGURA,;
			(cAlias)->Z3_CODTRAN,;
			(cAlias)->Z3_ANGULO1,;
			(cAlias)->Z3_ANGULO2,;
			(cAlias)->Z3_CODMESA,;
			(cAlias)->Z3_CODREGU,;
			(cAlias)->Z3_CODPAQ3,;
			(cAlias)->Z3_FLECHA,;
			(cAlias)->Z3_ASPVISU,;
			(cAlias)->Z3_APROVAD,;
			(cAlias)->Z3_QTDPECA,;
			(cAlias)->Z3_PESOBRU,;
			(cAlias)->Z3_PESOLIQ,;
			(cAlias)->Z3_LOTEEMP,;
			(cAlias)->Z3_SOLICIT,;
			(cAlias)->R_E_C_N_O_,;
			(cAlias)->Z3_APONTOK,;
			,	.F.})

		(cAlias)->(DbSkip())
	EndDo

	(cAlias)->(DbCloseArea())
Return

/*
	Query dos apontamentos
*/
Static Function queryBuscarApontamentos()
	Local cQuery	:= ""	as character

	cQuery += " SELECT " + CRLF
	cQuery += "        * "		+ CRLF

	cQuery += " FROM " + CRLF
	cQuery += "     " + RetSQLTab("SZ3") + CRLF

	cQuery += " WHERE " + CRLF
	cQuery += " 	    1 = 1 " + CRLF
	cQuery += "	 		AND " + RetSqlFil("SZ3") + CRLF
	cQuery += " 		AND Z3_OP  = '"+AllTrim((cAliasTela)->TMP_ORDEM)+"'" + CRLF
	cQuery += "	    	AND " + RetSqlDel("SZ3") + CRLF

	cQuery += " ORDER BY SZ3.R_E_C_N_O_"
Return cQuery

/*
	Query dos apontamentos
*/
Static Function queryBuscarRecursos()
	Local cQuery	:= ""	as character

	cQuery += " SELECT " + CRLF
	cQuery += "        H8_OPER "		+ CRLF
	cQuery += "        ,H8_RECURSO "		+ CRLF

	cQuery += " FROM " + CRLF
	cQuery += "     " + RetSQLTab("SH8") + CRLF

	cQuery += " WHERE " + CRLF
	cQuery += " 	    1 = 1 " + CRLF
	cQuery += "	 		AND " + RetSqlFil("SH8") + CRLF
	cQuery += " 		AND H8_OP  = '"+AllTrim((cAliasTela)->TMP_ORDEM)+"'" + CRLF
	cQuery += "	    	AND " + RetSqlDel("SH8") + CRLF

	cQuery += " ORDER BY SH8.R_E_C_N_O_"
Return cQuery

Static Function queryBuscarRecursosSG2()
	Local cQuery	:= ""	as character

	cQuery += " SELECT " + CRLF
	cQuery += "        G2_OPERAC AS H8_OPER"		+ CRLF
	cQuery += "        ,G2_RECURSO AS H8_RECURSO"		+ CRLF

	cQuery += " FROM " + CRLF
	cQuery += "     " + RetSQLTab("SG2") + CRLF

	cQuery += " WHERE " + CRLF
	cQuery += " 	    1 = 1 " + CRLF
	cQuery += "	 		AND " + RetSqlFil("SG2") + CRLF
	cQuery += " 		AND G2_PRODUTO  = '"+AllTrim((cAliasTela)->C2_PRODUTO)+"'" + CRLF
	cQuery += "	    	AND " + RetSqlDel("SG2") + CRLF

	cQuery += " ORDER BY SG2.R_E_C_N_O_"
Return cQuery

/*
	Refresh nas telas
*/
Static Function refreshTela()
	oTelaApontamento:Refresh()
	oGridApontamento:ForceRefresh()
Return

/*
	Validacoes dos campos do apontamento no grid
*/
User Function validaFieldBlankChapa()
	Local lRetorno				:= .T.	as logical
	Local cUltimoApontamento	:= "00"	as character
	Local nItemGrid				:= 0	as integer
	Local nPosdgt:=	aScan(oGridApontamento:aHeader,{ |x| x[2] = "XX_APONTOK"    })
	Local nPosPsl:=	aScan(oGridApontamento:aHeader,{ |x| x[2] = "XX_PESOLIQ"    })
	Local nPosPbr:=	aScan(oGridApontamento:aHeader,{ |x| x[2] = "XX_PESOBRU"    })



	Private cCampo	:= ReadVar()	as character

	If oGridApontamento:nAt == 1
		lRetorno	:= .F.
		FWAlertWarning("A primeira linha não pode ser editada, somente consulta das informações.", "Linha de Consulta")
	ElseIf oGridApontamento:aCols[oGridApontamento:nAt][nPosdgt] == "S"
		lRetorno	:= .F.
		FWAlertWarning("Apontamento j  realizado para essa linha, não pode ser editada.", "Apontamento Realizado")
	Else
		Do Case
		Case cCampo == "M->XX_OPERAC"
			If oGridApontamento:nAt == 2 .And. !(XX_OPERAC == "ST")
				lRetorno	:= .F.
				FWAlertWarning("A primeira opera  o deve ser o SETUP.", "SETUP")
			ElseIf oGridApontamento:nAt > 2 .And. XX_OPERAC == "ST"
				lRetorno	:= .F.
				FWAlertWarning("SETUP s  pode ser a primeira opera  o.", "SETUP")
			ElseIf !(XX_OPERAC $ "ST/SD")
				For nItemGrid := 2 To oGridApontamento:nAt-1
					If !(oGridApontamento:aCols[nItemGrid][1] $ "ST/SD") .And. !(oGridApontamento:aCols[nItemGrid][Len(oGridApontamento:aCols[nItemGrid])])
						cUltimoApontamento	:= oGridApontamento:aCols[nItemGrid][1]
					EndIf
				Next nItemGrid

				If !(Soma1(cUltimoApontamento) == XX_OPERAC)
					lRetorno	:= .F.
					FWAlertWarning("Opera  o fora da sequ ncia.", "Opera  o")
				EndIf
			EndIf

		Case cCampo == "M->XX_DATA"
			If !(XX_DATA == Date())
				lRetorno	:= .F.
				FWAlertWarning("Data inv lida para apontamento.", "Data")
			EndIf

		Case cCampo == "M->XX_HORARIO"
			If !(AtVldHora(XX_HORARIO))
				lRetorno	:= .F.
				FWAlertWarning("Hor rio inv lido.", "Hora")
			EndIf

		Case cCampo == "M->XX_CODMIC"
			If !(ExistCpo("QM2", XX_CODMIC))
				lRetorno	:= .F.
			EndIf

		Case cCampo == "M->XX_CODPAQ1"
			If !(ExistCpo("QM2", XX_CODPAQ1))
				lRetorno	:= .F.
			EndIf

		Case cCampo == "M->XX_CODPAQ2"
			If !(ExistCpo("QM2", XX_CODPAQ2))
				lRetorno	:= .F.
			EndIf

		Case cCampo == "M->XX_CODTRAN"
			If !(ExistCpo("QM2", XX_CODTRAN))
				lRetorno	:= .F.
			EndIf

		Case cCampo == "M->XX_CODMESA"
			If !(ExistCpo("QM2", XX_CODMESA))
				lRetorno	:= .F.
			EndIf

		Case cCampo == "M->XX_CODREGU"
			If !(ExistCpo("QM2", XX_CODREGU))
				lRetorno	:= .F.
			EndIf

		Case cCampo == "M->XX_CODPAQ3"
			If !(ExistCpo("QM2", XX_CODPAQ3))
				lRetorno	:= .F.
			EndIf

		Case cCampo == "M->XX_PESOBRU"
			If XX_PESOBRU < 0
				lRetorno	:= .F.
			ElseIf oGridApontamento:aCols[oGridApontamento:nAt][nPosPsl] > 0 .And. XX_PESOBRU < oGridApontamento:aCols[oGridApontamento:nAt][nPosPsl]
				lRetorno	:= .F.
				FWAlertWarning("Peso liquido maior que o peso bruto.", "Peso")
			EndIf

		Case cCampo == "M->XX_PESOLIQ"
			If XX_PESOLIQ < 0
				lRetorno	:= .F.
			ElseIf oGridApontamento:aCols[oGridApontamento:nAt][nPosPbr] > 0 .And. oGridApontamento:aCols[oGridApontamento:nAt][nPosPbr] < XX_PESOLIQ
				lRetorno	:= .F.
				FWAlertWarning("Peso liquido maior que o peso bruto.", "Peso")
			EndIf

		EndCase
	EndIf
Return lRetorno

/*
	Validacoes da linha do apontamento no grid
*/
User Function validaLinhaBlankChapa()
	Local	lRetorno	:= .T.	as logical

	If !(oGridApontamento:nAt == 1)
		atualizaStatus(oGridApontamento:nAt)

		If oGridApontamento:aCols[oGridApontamento:nAt][20] == "D"
			lRetorno	:= .F.
			FWAlertWarning("Linha ainda em digita  o.", "Digita  o")
		EndIf
	EndIf
Return lRetorno


/*
	Validacoes da linha no tudo ok
*/
User Function validaLinhaBlanktudook(ctipo)
	Local	lRetorno	:= .T.	as logical
	Local nx:=1
	Local nPesob	:=	aScan(oGridApontamento:aHeader,{ |x| x[2] = "XX_PESOBRU"    })
	Local nPesol	:=	aScan(oGridApontamento:aHeader,{ |x| x[2] = "XX_PESOLIQ"    })

	for nx:=2 to len(oGridApontamento:aCols)

		IF  SUBSTR(oGridApontamento:aCols[nx][1], 1, 1) <> "S" .and. ctipo == "A"
			IF  oGridApontamento:aCols[nx][nPesob] <= 0
				FWAlertWarning("Peso bruto menor ou igual a zero.", "Peso")
				Return .F.
			EndIf


			IF  oGridApontamento:aCols[nx][nPesol] <= 0
				FWAlertWarning("Peso liquido menor ou igual a zero.", "Peso")
				Return .F.
			Endif
		EndIf


		atualizaStatus(nx)
		If oGridApontamento:aCols[nx][20] == "D"
			lRetorno	:= .F.
			FWAlertWarning("Linha ainda em digita  o.", "Digita  o")
			nx:=len(oGridApontamento:aCols)
		EndIf

	next nx
Return lRetorno


/*
	Atualiza status da linha
*/
Static Function atualizaStatus(nLinha)
	Local lAprovado	:= .T.	as logical

	If Empty(oGridApontamento:aCols[nLinha][5]) .Or. Empty(oGridApontamento:aCols[nLinha][6]);
			.Or. Empty(oGridApontamento:aCols[nLinha][8]) .Or. Empty(oGridApontamento:aCols[nLinha][9]);
			.Or. Empty(oGridApontamento:aCols[nLinha][11]) .Or. Empty(oGridApontamento:aCols[nLinha][13]);
			.Or. Empty(oGridApontamento:aCols[nLinha][14]) .Or. Empty(oGridApontamento:aCols[nLinha][18]);
			.Or. Empty(oGridApontamento:aCols[nLinha][19])
		oGridApontamento:aCols[nLinha][20]	:= "D"
	Else
		If !Empty(cEspessuraLIE) .And. !Empty(cEspessuraLSE) .And. lAprovado
			lAprovado	:= compararMedicao(oGridApontamento:aCols[nLinha][5], cEspessuraLIE, cEspessuraLSE)
		EndIf

		If !Empty(cRebarbaLIE) .And. !Empty(cRebarbaLSE) .And. lAprovado
			lAprovado	:= compararMedicao(oGridApontamento:aCols[nLinha][6], cRebarbaLIE, cRebarbaLSE)
		EndIf

		If !Empty(cComprimentoMenorLIE) .And. !Empty(cComprimentoMenorLSE) .And. lAprovado
			lAprovado	:= compararMedicao(oGridApontamento:aCols[nLinha][8], cComprimentoMenorLIE, cComprimentoMenorLSE)
			//If !(oGridApontamento:aCols[nLinha][8] >= cComprimentoMenorLIE .And. oGridApontamento:aCols[nLinha][8] <= cComprimentoMenorLSE)
			//	lAprovado	:= .F.
			//EndIf
		EndIf

		If !Empty(cComprimentoMaiorLIE) .And. !Empty(cComprimentoMaiorLSE) .And. lAprovado
			lAprovado	:= compararMedicao(oGridApontamento:aCols[nLinha][9], cComprimentoMaiorLIE, cComprimentoMaiorLSE)
		EndIf

		If !Empty(cLarguraLIE) .And. !Empty(cLarguraLSE) .And. lAprovado
			lAprovado	:= compararMedicao(oGridApontamento:aCols[nLinha][11], cLarguraLIE, cLarguraLSE)
		EndIf

		If !Empty(cAngulo1LIE) .And. !Empty(cAngulo1LSE) .And. lAprovado
			lAprovado	:= compararMedicao(oGridApontamento:aCols[nLinha][13], cAngulo1LIE, cAngulo1LSE)
		EndIf

		If !Empty(cAngulo2LIE) .And. !Empty(cAngulo2LSE) .And. lAprovado
			lAprovado	:= compararMedicao(oGridApontamento:aCols[nLinha][14], cAngulo2LIE, cAngulo2LSE)
		EndIf

		If !Empty(cFlechaLIE) .And. !Empty(cFlechaLSE) .And. lAprovado
			lAprovado	:= compararMedicao(oGridApontamento:aCols[nLinha][18], cFlechaLIE, cFlechaLSE)
		EndIf

		If oGridApontamento:aCols[nLinha][19] == "N"
			lAprovado	:= .F.
		EndIf

		If lAprovado
			oGridApontamento:aCols[nLinha][20]	:= "A"
		Else
			oGridApontamento:aCols[nLinha][20]	:= "R"
		EndIf
	EndIf
Return

/*
	Comparar os valores da medicao
*/
Static Function compararMedicao(cValor, cInferior, cSuperior)
	Local lRetorno	:= .F.	as logical
	cValor:=strtran(cValor,',','.')
	cInferior:=strtran(cInferior,',','.')
	cSuperior:=strtran(cSuperior,',','.')

	If Val(AllTrim(cValor)) >= Val(AllTrim(cInferior)) .And. Val(AllTrim(cValor)) <= Val(AllTrim(cSuperior))
		lRetorno	:= .T.
	EndIf
Return lRetorno

/*
	Salva Apontamento
*/
Static Function salvaApontamento()
	Local nItemGrid		:= 0	as integer
	Local lNovoRegistro	:= .T.	as logical
	Local nPosdgt:=	aScan(oGridApontamento:aHeader,{ |x| x[2] = "XX_APONTOK"    })
	DbSelectArea("SZ3")

	For nItemGrid := 2 To Len(oGridApontamento:aCols)
		If Empty(oGridApontamento:aCols[nItemGrid][26])
			lNovoRegistro	:= .T.
		Else
			lNovoRegistro	:= .F.
			SZ3->(DbGoTop())
			SZ3->(DbGoTo(oGridApontamento:aCols[nItemGrid][26]))
		EndIf

		If !(oGridApontamento:aCols[nItemGrid][Len(oGridApontamento:aCols[nItemGrid])])
			Reclock("SZ3", lNovoRegistro)
			SZ3->Z3_FILIAL	:= xFilial("SZ3")
			SZ3->Z3_OP		:= AllTrim((cAliasTela)->TMP_ORDEM)
			SZ3->Z3_OPERAC	:= oGridApontamento:aCols[nItemGrid][1]
			SZ3->Z3_DATA	:= oGridApontamento:aCols[nItemGrid][2]
			SZ3->Z3_HORARIO	:= oGridApontamento:aCols[nItemGrid][3]
			SZ3->Z3_CODMIC	:= oGridApontamento:aCols[nItemGrid][4]
			SZ3->Z3_ESPESSU	:= AllTrim(oGridApontamento:aCols[nItemGrid][5])
			SZ3->Z3_REBARBA	:= AllTrim(oGridApontamento:aCols[nItemGrid][6])
			SZ3->Z3_CODPAQ1	:= oGridApontamento:aCols[nItemGrid][7]
			SZ3->Z3_COMPMEN	:= AllTrim(oGridApontamento:aCols[nItemGrid][8])
			SZ3->Z3_COMPMAI	:= AllTrim(oGridApontamento:aCols[nItemGrid][9])
			SZ3->Z3_CODPAQ2	:= oGridApontamento:aCols[nItemGrid][10]
			SZ3->Z3_LARGURA	:= AllTrim(oGridApontamento:aCols[nItemGrid][11])
			SZ3->Z3_CODTRAN	:= oGridApontamento:aCols[nItemGrid][12]
			SZ3->Z3_ANGULO1	:= AllTrim(oGridApontamento:aCols[nItemGrid][13])
			SZ3->Z3_ANGULO2	:= AllTrim(oGridApontamento:aCols[nItemGrid][14])
			SZ3->Z3_CODMESA	:= oGridApontamento:aCols[nItemGrid][15]
			SZ3->Z3_CODREGU	:= oGridApontamento:aCols[nItemGrid][16]
			SZ3->Z3_CODPAQ3	:= oGridApontamento:aCols[nItemGrid][17]
			SZ3->Z3_FLECHA	:= AllTrim(oGridApontamento:aCols[nItemGrid][18])
			SZ3->Z3_ASPVISU	:= oGridApontamento:aCols[nItemGrid][19]
			SZ3->Z3_APROVAD	:= oGridApontamento:aCols[nItemGrid][20]
			SZ3->Z3_QTDPECA	:= oGridApontamento:aCols[nItemGrid][21]
			SZ3->Z3_PESOBRU	:= oGridApontamento:aCols[nItemGrid][22]
			SZ3->Z3_PESOLIQ	:= oGridApontamento:aCols[nItemGrid][23]
			SZ3->Z3_LOTEEMP	:= oGridApontamento:aCols[nItemGrid][24]
			SZ3->Z3_SOLICIT	:= oGridApontamento:aCols[nItemGrid][25]
			SZ3->Z3_APONTOK	:= oGridApontamento:aCols[nItemGrid][nPosdgt]
			SZ3->(MsUnlock())
		ElseIf !lNovoRegistro
			Reclock("SZ3", lNovoRegistro)
			SZ3->(DbDelete())
			SZ3->(MsUnlock())
		EndIf
	Next nItemGrid

	zeraArrayOperacoes()
	oGridApontamento:SetArray( aOperacoes )
	refreshTela()

	FWAlertSuccess("Registro salvo com sucesso.", "Salvar")
Return

/*
	Valida delete da linha do apontamento
*/
User Function validaDeleteLinhaBlankChapa()
	Local	lRetorno	:= .F.	as logical

	If oGridApontamento:nAt == Len(oGridApontamento:aCols)
		If oGridApontamento:aCols[oGridApontamento:nAt][27] == "S"
			FWAlertWarning("Linha j  apontada não pode ser deletada.", "Delete")
		Else
			lRetorno	:= .T.
		EndIf
	Else
		FWAlertWarning("Somente a ultima linha pode ser deletada.", "Delete")
	EndIf
Return lRetorno

/*
	Processa Apontamento
*/
Static Function processaApontamento()
	Private oProcess		:= Nil	as object

	oProcess	:=	MsNewProcess():New( { |lEnd| gravaApontamento() },"Apontamento","Executando...",.T.)
	oProcess:Activate()
Return

/*
	Grava os dados do apontamento
*/
Static Function gravaApontamento()
	Local cQuery        := "" as character
	Local aVetorSH6     := {} as array
	Local cAliasRecurso := "" as character
	Local aRecursos     := {} as array
	Local nOperacao     := 1  as integer
	Local cHorario      := "" as character
	Local cGrupoChapa := SuperGetMV("ZV_GRPCHAP",.F.,"000000")
	Private lAutoErrNoFile  := .T.
	Private lMsErroAuto     := .F.
	Private lContinua		:= .T.

	oProcess:SetRegua1(3)
	oProcess:IncRegua1("Salvando Dados...")

	salvaApontamento()

	// cQuery := 	queryBuscarRecursos()
	cQuery := 	queryBuscarRecursosSG2()

	MPSysOpenQuery( cQuery, cAliasRecurso := GetNextAlias() )
	While (cAliasRecurso)->(!EoF())
		aAdd(aRecursos, {(cAliasRecurso)->H8_OPER, (cAliasRecurso)->H8_RECURSO})
		(cAliasRecurso)->(DbSkip())
	EndDo
	(cAliasRecurso)->(DbCloseArea())

	cQuery := 	queryBuscarApontamentos()
	MPSysOpenQuery( cQuery, cAlias := GetNextAlias() )

	oProcess:IncRegua1("Gerando Apontamentos...")

	(cAlias)->(DbGoTop())
	While (cAlias)->(!EoF())
		If (cAlias)->Z3_QTDPECA > 0  .And. !((cAlias)->Z3_APROVAD == "D") .And. !((cAlias)->Z3_OPERAC $ "ST/SD") .And. !((cAlias)->Z3_APONTOK == "S")

			cHorario	:= (cAlias)->Z3_HORARIO
			cGrupx:=alltrim(posicione("SB1",1,xfilial("SB1")+(cAliasTela)->C2_PRODUTO,"B1_GRUPO"))
			cGrupx:=cGrupx + SB1->B1_ZSUBGRU
			If cGrupx $cGrupoChapa  .or. !Empty((cAlias)->Z3_LOTEEMP)
				Begin Transaction
					If Len(aRecursos) == 2
						For nOperacao := 1 To Len(aRecursos)
							oProcess:SetRegua2(7)
							oProcess:IncRegua2("Gravando Apontamento...")

							SB1->(DbSeek(xFilial("SB1")+(cAliasTela)->C2_PRODUTO))

							aLoteProduzido := dsm.genericos.U_fBuscaProximoLote((cAliasTela)->TMP_ORDEM, (cAliasTela)->C2_PRODUTO)

							Begin Sequence
								aVetorSH6 :=	{;
									{"H6_OP"		,	(cAliasTela)->TMP_ORDEM		,	NIL},;
									{"H6_PRODUTO"	,	(cAliasTela)->C2_PRODUTO	,	NIL},;
									{"H6_OPERAC"	,	aRecursos[nOperacao][1]		,	NIL},; //Opera  o sequencial conforme SH8 - Opera  es alocadas para a Ordem de Produ  o;
									{"H6_RECURSO"	,	aRecursos[nOperacao][2]		,	NIL},; //Recurso alocado conforme SH8;
									{"H6_DTAPONT"	,	Date()						,	NIL},;
									{"H6_DATAINI"	,	StoD((cAlias)->Z3_DATA)		,	NIL},;
									{"H6_HORAINI"	,	cHorario					,	NIL},;
									{"H6_DATAFIN"	,	StoD((cAlias)->Z3_DATA)		,	NIL},;
									{"H6_HORAFIN"	,	IncTime(cHorario, 0, 1, 0)	,	NIL},;
									{"H6_PT"		,	"P"							,	NIL},;
									{"H6_LOTECTL"	,	aLoteProduzido[1]			,	NIL},;
									{"H6_DTVALID"	,	aLoteProduzido[2]			,	NIL},;
									{"H6_LOCAL"		,	(cAliasTela)->C2_LOCAL		,	NIL}} //Armaz m padr o C2_LOCAL;

								If SB1->B1_UM $ "KG|TL"
									aAdd(aVetorSH6, {"H6_QTDPROD"	,	(cAlias)->Z3_PESOLIQ	,	NIL})
									aAdd(aVetorSH6, {"H6_ZQUANT"	,	(cAlias)->Z3_QTDPECA	,	NIL})
									aAdd(aVetorSH6, {"H6_ZPESOBT"	,	(cAlias)->Z3_PESOBRU	,	NIL})
								Else
									aAdd(aVetorSH6, {"H6_QTDPROD"	,	(cAlias)->Z3_QTDPECA	,	NIL})
									aAdd(aVetorSH6, {"H6_ZPESO"		,	(cAlias)->Z3_PESOLIQ	,	NIL})
									aAdd(aVetorSH6, {"H6_ZPESOBT"	,	(cAlias)->Z3_PESOBRU	,	NIL})
								EndIf

								lMsErroAuto := .F.

								MSExecAuto({|x| MATA681(x)},aVetorSH6, 3)
							End Sequence

							If lMsErroAuto
								cError := getError()
								addLogs(cError)
								FWAlertError("Apontamento não realizado.", "Apontamento")
								DisarmTransaction()
								lContinua := .F.
								EXIT
							EndIf

							cHorario	:= IncTime(cHorario, 0, 2, 0)
						Next nOperacao
					else
						cError := getError()
						addLogs(cError)
						FWAlertError("Caadastro de Roteiro Invalido. Verifique as operacoes cadastradas", "Apontamento")
						DisarmTransaction()
						lContinua := .F.

					endif
					If lContinua
						SZ3->(DbGoTop())
						SZ3->(DbGoTo((cAlias)->R_E_C_N_O_))
						If SZ3->(Recno()) == (cAlias)->R_E_C_N_O_
							RecLock("SZ3", .F.)
							SZ3->Z3_APONTOK	:= "S"
							SZ3->Z3_LOTECTL	:= SH6->H6_LOTECTL
							SZ3->(MsUnlock())

						Else
							FWAlertError("Confirma  o do apontamento nao realizada. (SZ3)", "Apontamento")
							DisarmTransaction()
							lContinua := .F.
						EndIf
					EndIf

					If lContinua
						oProcess:IncRegua2("Baixando Saldo Empenhado...")
						If !baixarEmpenho()
							cError := getError()
							addLogs(cError)
							FWAlertError("Baixa do empenho não realizada.", "Baixa Empenho")
							DisarmTransaction()
							lContinua := .F.
						EndIf
					EndIf

					If lContinua
						oProcess:IncRegua2("Endereçando Saldo Apontamento...")
						If dsm.genericos.U_fValidaExisteEndereco("98", (cAliasTela)->A1_CGC)
							If !enderecarApontamento()
								cError := getError()
								addLogs(cError)
								FWAlertError("Endere amento de saldo não realizado.", "Saldo")
								DisarmTransaction()
								lContinua := .F.
							EndIf
						else
							DisarmTransaction()
							lContinua := .F.
						Endif
					EndIf

					If lContinua
						oProcess:IncRegua2("Gravando Qualidade...")
						If !gravaQualidade()
							DisarmTransaction()
							lContinua := .F.
						EndIf
					EndIf

					If lContinua
						If (cAlias)->Z3_APROVAD == "A"
							If lContinua
								oProcess:IncRegua2("Endereçando Saldo Qualidade...")
								If dsm.genericos.U_fValidaExisteEndereco((cAliasTela)->C2_LOCAL, (cAliasTela)->A1_CGC)
									If !enderecarQualidade()
										DisarmTransaction()
										lContinua := .F.
									EndIf
								Else
									DisarmTransaction()
									lContinua := .F.
								EndIf
							EndIf

							If lContinua
								If Substr(SH6->H6_OP,9,3) == "001" // Somente executar para a O.P do Produto que esta no pedido de venda. Não executando para O.Ps filhas
									oProcess:IncRegua2("Atualizando Pedido de Venda...")
									dsm.genericos.U_fAddItemPedidoVendaProducao()
								EndIf
							EndIf
						EndIf
					EndIf
				End Transaction
			Else
				cGrupo:=alltrim(posicione("SB1",1,xfilial("SB1")+(cAliasTela)->C2_PRODUTO,"B1_GRUPO"))
				cProdx:=(cAliasTela)->C2_PRODUTO
				cDesc:=alltrim((cAliasTela)->TMP_DESPRD)

				FWAlertError("Aten  o "+CRLF+;
					" O Produto:"+ cProdx+'-'+cDesc+ CRLF+;
					" Esta no Grupo "+cGrupo+" Não permitido seu apontamento sem lote "+CRLF+;
					" Produtos sem lote devem ser do grupo :"+cGrupoChapa+CRLF+;
					" Favor ajustar cadastro de produto ou" +CRLF+;
					" Informar o lote ou "+CRLF+;
					" Ajustar parametro ZV_GRPCHAP", "Não Apontado")
				DisarmTransaction()
				lContinua := .F.
			EndIf
		EndIf

		(cAlias)->(DbSkip())
	EndDo

	If lContinua
		FWAlertSuccess("Apontamento realizado.", "Apontamento")
	Else
		FWAlertError("Apontamento não realizado.", "Apontamento")
	EndIf

	zeraArrayOperacoes()
	oGridApontamento:SetArray( aOperacoes )
	refreshTela()
Return

/*
	Grava os dados no qualidade
*/
Static Function gravaQualidade()
	Local aLibera			:= {}	as array
	Local nAprovaReprova	:= IIF((cAlias)->Z3_APROVAD == "A", 1, 2)	as integer
	Local cChave			:= ""	as character
	Local cAliasQP7			:= ""	as character
	Local cQuery			:= ""	as character
	Local nLaco				:= 0	as integer
	Local cAprovaReprova	:= IIF((cAlias)->Z3_APROVAD == "A", "A", "E")	as character
	Local cSitOP			:= IIF((cAlias)->Z3_APROVAD == "A", "2", "3")	as character
	Local cDescricaoAprova	:= ""	as character
	Local lAprovado			:= .F.	as logical
	Local cMVQIPEST			:= SuperGetMV("MV_QIPEST",.F.,"0") as character
	Local aMov				:= {} as array
	Local aCM				:= {} as array
	Local cLocalRejeitado	:= GetMvNNR("MV_CQREJEI","97") as character

	DbSelectArea("SA1")
	SA1->(DbSetOrder(3))
	SA1->(DbSeek(xFilial("SA1")+(cAliasTela)->A1_CGC))

	DbSelectArea("QPL") //Laudo da OP
	For nLaco := 1 To 2
		RecLock("QPL", .T.)
		QPL->QPL_FILIAL	:= xFilial("QPL")
		QPL->QPL_PRODUT	:= (cAliasTela)->C2_PRODUTO
		QPL->QPL_DTENTR	:= StoD((cAlias)->Z3_DATA)
		QPL->QPL_LOTE	:= SH6->H6_LOTECTL
		QPL->QPL_DTENLA	:= StoD((cAlias)->Z3_DATA)
		QPL->QPL_HRENLA	:= (cAlias)->Z3_HORARIO
		QPL->QPL_LAUDO	:= cAprovaReprova
		QPL->QPL_DTLAUD	:= StoD((cAlias)->Z3_DATA)
		QPL->QPL_HRLAUD	:= (cAlias)->Z3_HORARIO
		QPL->QPL_TAMLOT	:= AllTrim(Str(SH6->H6_QTDPROD))
		QPL->QPL_OP		:= (cAliasTela)->TMP_ORDEM
		QPL->QPL_ROTEIR	:= (cAliasTela)->C2_ROTEIRO

		If cAprovaReprova == "E"
			QPL->QPL_QTREJ	:= AllTrim(Str(SH6->H6_QTDPROD))
		EndIf

		If nLaco == 1
			QPL->QPL_LABOR	:= "LABFIS"
			QPL->QPL_OPERAC	:= (cAliasTela)->H8_OPER
		ElseIf nLaco == 2
			QPL->QPL_DTVAL	:= SH6->H6_DTVALID
		EndIf

		QPL->(MsUnlock())
	Next nLaco

	cQuery := 	queryBuscarLimitesMedicoes()
	MPSysOpenQuery( cQuery, cAliasQP7 := GetNextAlias() )

	DbSelectArea("QAA") // Ensaiadores
	DbSelectArea("QPR") // Medicoes
	(cAliasQP7)->(DbGoTop())
	While (cAliasQP7)->(!EoF())
		cChave	:= QA_SXESXF("QPR","QPR_CHAVE",,4)
		ConfirmSX8()

		RecLock("QPR", .T.)
		QPR->QPR_FILIAL	:= xFilial("QPR")
		QPR->QPR_OP		:= (cAliasTela)->TMP_ORDEM
		QPR->QPR_PRODUT	:= (cAliasTela)->C2_PRODUTO
		QPR->QPR_DTENTR	:= StoD((cAlias)->Z3_DATA)
		QPR->QPR_LOTE	:= SH6->H6_LOTECTL
		QPR->QPR_REVI	:= (cAliasQP7)->QP7_REVI
		QPR->QPR_LABOR	:= "LABFIS"
		QPR->QPR_ENSAIO	:= (cAliasQP7)->QP7_ENSAIO
		QPR->QPR_DTMEDI	:= StoD((cAlias)->Z3_DATA)
		QPR->QPR_HRMEDI	:= (cAlias)->Z3_HORARIO
		QPR->QPR_AMOSTR	:= 1
		//QPR->QPR_RESULT	:= (cAlias)->Z3_APROVAD
		QPR->QPR_OPERAC	:= (cAliasTela)->H8_OPER
		QPR->QPR_CHAVE	:= cChave
		QPR->QPR_CLIENT	:= SA1->A1_COD
		QPR->QPR_LOJA	:= SA1->A1_LOJA
		QPR->QPR_FILMAT	:= xFilial("QPR")
		QPR->QPR_ROTEIR	:= (cAliasTela)->C2_ROTEIRO
		QPR->QPR_ENSR	:= QP215Ens()
		QPR->(MsUnlock())

		RecLock("QPT", .T.)
		QPT->QPT_FILIAL	:= xFilial("QPT")
		QPT->QPT_CODMED	:= cChave
		QPT->(MsUnlock())

		If AllTrim((cAliasQP7)->QP1_DESCPO) == "ASPECTO VISUAL"
			RecLock("QPQ", .T.)
			QPQ->QPQ_FILIAL	:= xFilial("QPQ")
			QPQ->QPQ_CODMED	:= cChave
			QPQ->QPQ_MEDICA	:= (cAlias)->Z3_ASPVISU
			QPQ->(MsUnlock())

			RecLock("QPR", .F.)
			QPR->QPR_RESULT	:= IIF((cAlias)->Z3_ASPVISU == "N", "R", "A")
			QPR->(MsUnlock())
		Else
			RecLock("QPS", .T.)
			QPS->QPS_FILIAL	:= xFilial("QPS")
			QPS->QPS_CODMED	:= cChave
			//QPS->QPS_INDMED	:= cAprovaReprova

			If AllTrim((cAliasQP7)->QP1_DESCPO) == "ESPESSURA"
				lAprovado	:= compararMedicao((cAlias)->Z3_ESPESSU, cEspessuraLIE, cEspessuraLSE)

				QPS->QPS_INDMED	:= IIF(lAprovado, "A", "E")
				QPS->QPS_MEDICA	:=   space(TamSx3("QPS_MEDICA")[1]  - len(alltrim((cAlias)->Z3_ESPESSU )))+alltrim((cAlias)->Z3_ESPESSU )
			ElseIf AllTrim((cAliasQP7)->QP1_DESCPO) == "REBARBA"
				lAprovado	:= compararMedicao((cAlias)->Z3_REBARBA, cRebarbaLIE, cRebarbaLSE)

				QPS->QPS_INDMED	:= IIF(lAprovado, "A", "E")
				QPS->QPS_MEDICA	:=  space(TamSx3("QPS_MEDICA")[1]  - len(alltrim((cAlias)->Z3_REBARBA )))+alltrim((cAlias)->Z3_REBARBA )
			ElseIf AllTrim((cAliasQP7)->QP1_DESCPO) == "COMPRIMENTO"
				lAprovado	:= compararMedicao((cAlias)->Z3_COMPMEN, cComprimentoMenorLIE, cComprimentoMenorLSE)

				QPS->QPS_INDMED	:= IIF(lAprovado, "A", "E")
				QPS->QPS_MEDICA	:=    space(TamSx3("QPS_MEDICA")[1]  - len(alltrim((cAlias)->Z3_COMPMEN )))+alltrim((cAlias)->Z3_COMPMEN )
			ElseIf AllTrim((cAliasQP7)->QP1_DESCPO) == "COMPRIMENTO 2"
				lAprovado	:= compararMedicao((cAlias)->Z3_COMPMAI, cComprimentoMaiorLIE, cComprimentoMaiorLSE)

				QPS->QPS_INDMED	:= IIF(lAprovado, "A", "E")
				QPS->QPS_MEDICA	:=  space(TamSx3("QPS_MEDICA")[1]  - len(alltrim((cAlias)->Z3_COMPMAI )))+alltrim((cAlias)->Z3_COMPMAI )
			ElseIf AllTrim((cAliasQP7)->QP1_DESCPO) == "LARGURA"
				lAprovado	:= compararMedicao((cAlias)->Z3_LARGURA, cLarguraLIE, cLarguraLSE)

				QPS->QPS_INDMED	:= IIF(lAprovado, "A", "E")
				QPS->QPS_MEDICA	:=   space(TamSx3("QPS_MEDICA")[1]  - len(alltrim((cAlias)->Z3_LARGURA )))+alltrim((cAlias)->Z3_LARGURA )
			ElseIf AllTrim((cAliasQP7)->QP1_DESCPO) == "ANGULO"
				lAprovado	:= compararMedicao((cAlias)->Z3_ANGULO1, cAngulo1LIE, cAngulo1LSE)

				QPS->QPS_INDMED	:= IIF(lAprovado, "A", "E")
				QPS->QPS_MEDICA	:=  space(TamSx3("QPS_MEDICA")[1]  - len(alltrim((cAlias)->Z3_ANGULO1 )))+alltrim((cAlias)->Z3_ANGULO1 )
				QPS->(MsUnlock())

				lAprovado	:= compararMedicao((cAlias)->Z3_ANGULO2, cAngulo2LIE, cAngulo2LSE)

				RecLock("QPS", .T.)
				QPS->QPS_FILIAL	:= xFilial("QPS")
				QPS->QPS_CODMED	:= cChave
				QPS->QPS_INDMED	:= IIF(lAprovado, "A", "E")
				QPS->QPS_MEDICA	:=   space(TamSx3("QPS_MEDICA")[1]  - len(alltrim((cAlias)->Z3_ANGULO2 )))+alltrim((cAlias)->Z3_ANGULO2 )
			ElseIf AllTrim((cAliasQP7)->QP1_DESCPO) == "FLECHA"
				lAprovado	:= compararMedicao((cAlias)->Z3_FLECHA, cFlechaLIE, cFlechaLSE)

				QPS->QPS_INDMED	:= IIF(lAprovado, "A", "E")
				QPS->QPS_MEDICA	:=  space(TamSx3("QPS_MEDICA")[1]  - len(alltrim((cAlias)->Z3_FLECHA )))+alltrim((cAlias)->Z3_FLECHA )
			EndIf

			QPS->(MsUnlock())

			RecLock("QPR", .F.)
			QPR->QPR_RESULT	:= IIF(lAprovado, "A", "R")
			QPR->(MsUnlock())
		EndIf

		(cAliasQP7)->(DbSkip())
	EndDo
	(cAliasQP7)->(DbCloseArea())

	DbSelectArea("QPD")
	QPD->(DbSeek(xFilial("QPD")+cAprovaReprova))
	cDescricaoAprova	:= QPD->QPD_DESCPO

	DbSelectArea("QPM") //Especificoes da Operacoes
	RecLock("QPM", .T.)
	QPM->QPM_FILIAL	:= xFilial("QPM")
	QPM->QPM_PRODUT	:= (cAliasTela)->C2_PRODUTO
	QPM->QPM_DTPROD	:= StoD((cAlias)->Z3_DATA)
	QPM->QPM_LOTE	:= SH6->H6_LOTECTL
	QPM->QPM_DTENLA	:= StoD((cAlias)->Z3_DATA)
	QPM->QPM_HRENLA	:= (cAlias)->Z3_HORARIO
	QPM->QPM_LAUDO	:= cAprovaReprova
	QPM->QPM_DESLAU	:= cDescricaoAprova
	QPM->QPM_DTLAUD	:= StoD((cAlias)->Z3_DATA)
	QPM->QPM_HRLAUD	:= (cAlias)->Z3_HORARIO
	QPM->QPM_DTVAL	:= SH6->H6_DTVALID
	QPM->QPM_TAMLOT	:= AllTrim(Str(SH6->H6_QTDPROD))
	QPM->QPM_OP		:= (cAliasTela)->TMP_ORDEM
	QPM->QPM_OPERAC	:= (cAliasTela)->H8_OPER
	QPM->QPM_ROTEIR	:= SC2->C2_ROTEIRO
	QPM->(MsUnlock())

	DbSelectArea("QPK")
	If QPK->(DbSeek(xFilial("QPK")+AvKey((cAliasTela)->TMP_ORDEM,"QPK_OP")+SH6->H6_LOTECTL))
		RecLock("QPK", .F.)
		//QPK->QPK_CHAVE	:= cChave
		QPK->QPK_LAUDO	:= cAprovaReprova
		QPK->QPK_CERQUA	:= QA_SEQUSX6("QIP_CEQU",TamSX3("C2_CERQUA")[1],"S","Certificado Qualidade")
		QPK->QPK_CLIENT	:= SA1->A1_COD
		QPK->QPK_LOJA	:= SA1->A1_LOJA
		QPK->QPK_SITOP	:= cSitOP
		QPK->(MsUnlock())
	Else
		FWAlertError("Registro do qualidade não encontrado (QPK).", "Qualidade")
		//DisarmTransaction()
		lContinua := .F.
	EndIf

	DbSelectArea("SD3")
	SD3->(DbSetOrder(14))
	If SD3->(DbSeek(xFilial("SD3")+SH6->H6_PRODUTO+SH6->H6_IDENT))
		DbSelectArea("SD7")
		SD7->(DbSetOrder(3))
		If SD7->(DbSeek(xFilial("SD7")+SH6->H6_PRODUTO+SD3->D3_NUMSEQ))

			If cMVQIPEST == "0"

				Begin Sequence
					aAdd(aLibera,	{;
						{"D7_TIPO"		,	nAprovaReprova			,	NIL},;
						{"D7_DATA"		,	Date()					,	NIL},;
						{"D7_QTDE"		,	SH6->H6_QTDPROD			,	NIL},;
						{"D7_OBS"		,	""						,	NIL},;
						{"D7_QTSEGUM"	,	NIL						,	NIL},;
						{"D7_MOTREJE"	,	""						,	NIL},;
						{"D7_LOCDEST"	,	IIF(nAprovaReprova == 2, cLocalRejeitado, (cAliasTela)->C2_LOCAL)	,	NIL},;
						{"D7_LOCALIZ"	,	(cAliasTela)->A1_CGC	,	NIL},;
						{"D7_SALDO"		,	NIL						,	NIL},;
						{"D7_SALDO2"	,	NIL						,	NIL},;
						{"D7_ESTORNO"	,	NIL						,	NIL}})

					lMsErroAuto := .F.

					MSExecAuto({|x, y, z| MATA175(x, y)},aLibera, 4)
				End Sequence

				If lMsErroAuto
					cError := getError()
					addLogs(cError)
					FWAlertError("Liberacao do qualidade não realizado.", "Qualidade")
					//DisarmTransaction()
					lContinua := .F.
				EndIf
			Else

				SD7->(DbSetORder(2))
				If SD7->D7_TIPO == 0

					Aadd(aMov,Array(11))
					aMov[Len(aMov),01] := nAprovaReprova   			// Tipo da Movimentacao (1=libera/2=Rejeita)
					aMov[Len(aMov),02] := SH6->H6_QTDPROD   		// Quantidade a ser movimentada
					aMov[Len(aMov),03] := IIF(nAprovaReprova == 2, cLocalRejeitado, (cAliasTela)->C2_LOCAL) 	// Local de Destino da Movimentacao
					aMov[Len(aMov),04] := Date()    				// Data da Movimentacao
					aMov[Len(aMov),05] := ""              			// X = Estornado
					aMov[Len(aMov),06] := ""              			// Motivo da Rejeicao
					aMov[Len(aMov),07] := ""      					// Observacao
					aMov[Len(aMov),08] := nil 						// Quantidade na 2a Unidade de Medida
					aMov[Len(aMov),09] := ""						// Endereco
					aMov[Len(aMov),10] := " " 			   			// Numero de Serie
					aMov[Len(aMov),11] := " " 			   			// Servico
					aCM := {0,0,0,0,0}
					fGravaCQ(SD7->D7_PRODUTO,SD7->D7_NUMERO,.F.,aMov,aCM)
				Else
					FWAlertError("Item não   do tipo 0 na (SD7).", "Qualidade")
					//DisarmTransaction()
					lContinua := .F.
				EndIf
			EndIf
		Else
			FWAlertError("Item não identificado para libera  o do CQ (SD7).", "Qualidade")
			//DisarmTransaction()
			lContinua := .F.
		EndIf
	Else
		FWAlertError("Movimenta  o de produ  o/estoque não encontrada (SD3).", "PCP")
		//DisarmTransaction()
		lContinua := .F.
	EndIf
Return lContinua

/*
	Baixar o empenho com lote correto
*/
Static Function baixarEmpenho()
	Local cTMdaBaixa  := GetNewPar("ZZ_TMBAIXA", "") as character
	Local lSequencia  := .T.                         as logical
	Local nSeqSD3     := 1                           as integer
	Local cSeqOP      := ""                          as character
	Local cQuery      := ""                          as character
	Local cSD4Alias   := ""                          as character
	Local aCabecSD3   := {}                          as array
	Local aItemSD3    := {}                          as array
	Local aItensSD3   := {}                          as array
	Local aArea       := getArea()                   as array
	Local nQtdBaixa   := 0                           as integer
	Local cGrupoChapa := SuperGetMV("ZV_GRPCHAP",.F.," ")
	local cGrupoprod  := posicione("SB1",1,xfilial("SB1")+(cAliasTela)->C2_PRODUTO,"B1_GRUPO")
	Local cLoteBaixa	:= ""	as character

	cGrupoprod:=alltrim(cGrupoprod) + SB1->B1_ZSUBGRU
	If  Empty((cAlias)->Z3_LOTEEMP) .and. !cGrupoprod$cGrupoChapa
		FWAlertError("Obrigat rio informar o LOTE.", "Baixa Empenho")
		lContinua := .F.
		Return lContinua
	EndIf

	Do While lSequencia
		cQuery := ""
		cQuery += " SELECT *  " + CRLF
		cQuery += " FROM " + RetSqlName("SD3") + " D3 " + CRLF
		cQuery += " WHERE D3.D3_DOC = '" + Substr((cAliasTela)->TMP_ORDEM,1,6)+StrZero(nSeqSD3,3) + "' " + CRLF
		cQuery += " AND D3.D_E_L_E_T_ <> '*' " + CRLF
		cQuery += " AND D3.D3_FILIAL = '" + xFilial("SD3") + "' " + CRLF

		dbUseArea(.T., "TOPCONN", TCGenQry(,,cQuery), "TRSD3", .F., .T.)

		DbSelectArea("TRSD3")
		dbGoTop()
		If TRSD3->(EoF())
			lSequencia := .F.
		Else
			nSeqSD3++
		EndIf

		DbSelectArea("TRSD3")
		DbCloseArea()
	EndDo

	cSeqOP := StrZero(nSeqSD3,3)

	cQuery := "SELECT * FROM "+RetSQLTab("SD4") + CRLF
	Cquery += " WHERE 1=1 " + CRLF
	cQuery += "	 AND " + RetSqlFil("SD4") + CRLF
	cQuery += "  AND D4_OP = '"+(cAliasTela)->TMP_ORDEM+"' " + CRLF
	
	If Empty(SZ3->Z3_LOTEEMP)
		cQuery += "  AND D4_LOTECTL = '"+(cAliasTela)->C5_ZLOTCTL+"' " + CRLF
	Else
		//cQuery += "  AND D4_LOTECTL = '"+SZ3->Z3_LOTEEMP+"' " + CRLF*/
		cQuery += "  AND D4_COD = '"+buscaProdutoDoLote()+"' " + CRLF
	EndIf

	cQuery += "	 AND " + RetSqlDel("SD4") + CRLF

	cSD4Alias := MPSysOpenQuery( cQuery )

	If (cSD4Alias)->(!EOF())

		Begin Sequence	///(cAliasTela)->C2_PRODUTO
			SB1->(DbSeek(xFilial("SB1") + (cSD4Alias)->D4_COD))

			If SB1->B1_UM $ "KG|TL"
				nQtdBaixa := SZ3->Z3_PESOLIQ
			Else
				If (AllTrim(SB1->B1_GRUPO) + SB1->B1_ZSUBGRU) $ cGrupoChapa
					If SG1->(DbSeek(FwxFilial("SG1")+(cAliasTela)->C2_PRODUTO+(cSD4Alias)->D4_COD+(cSD4Alias)->D4_TRT))
						nQtdBaixa := SZ3->Z3_QTDPECA * SG1->G1_QUANT
					EndIf
				Else
					nQtdBaixa := SZ3->Z3_QTDPECA
				EndIf
			EndIf

			cLoteBaixa	:= IIF(Empty(SZ3->Z3_LOTEEMP), (cAliasTela)->C5_ZLOTCTL, SZ3->Z3_LOTEEMP)

			aCabecSD3 :={{"D3_DOC"		, Substr((cAliasTela)->TMP_ORDEM,1,6)+cSeqOP	, NIL},;
						{"D3_TM"		, cTMdaBaixa	, NIL},;
						{"D3_EMISSAO"	, dDataBase	, NIL}}
			// {"D3_CC"     , SB1->B1_CC, NIL},;

			aItemSD3  :={{"D3_COD"	, (cSD4Alias)->D4_COD	, NIL},;
						{"D3_OP"     , (cAliasTela)->TMP_ORDEM		, NIL},;
						{"D3_UM"     , SB1->B1_UM					, NIL},;
						{"D3_QUANT"  , nQtdBaixa					, NIL},;
						{"D3_LOCAL"  , (cSD4Alias)->D4_LOCAL		, NIL},;
						{"D3_GRUPO"  , SB1->B1_GRUPO				, NIL},;
						{"D3_LOTECTL", cLoteBaixa					, NIL},;
						{"D3_LOCALIZ", (cAliasTela)->A1_CGC			, NIL}}

			aAdd(aItensSD3,aItemSD3)

			lMsErroAuto := .F.

			MSExecAuto({|x,y,z| MATA241(x,y,z)},aCabecSD3,aItensSD3,3)
		End Sequence

		If lMsErroAuto
			cError := getError()
			addLogs(cError)
			// FWAlertError("Baixa do empenho não realizada.", "Baixa Empenho")
			ShowLog("Baixa do empenho não realizada."+CRLF+cError)
			lContinua := .F.
		EndIf
	Else
		FWAlertError("Lote: "+SZ3->Z3_LOTEEMP+" inv lido.", "Baixa Empenho")
		lContinua := .F.
	EndIf

	RestArea(aArea)

Return lContinua

/*
	Endere ar Saldo do Apontamento
*/
Static Function enderecarApontamento()
	DbSelectArea("SD3")
	SD3->(DbSetOrder(14))
	If SD3->(DbSeek(xFilial("SD3")+SH6->H6_PRODUTO+SH6->H6_IDENT))
		lContinua := enderecarItens()
	Else
		FWAlertError("Movimenta  o de produ  o/estoque não encontrada (SD3).", "PCP")
		//DisarmTransaction()
		lContinua := .F.
	EndIf
Return lContinua

/*
	Endere ar Saldo do Qualidade
*/
Static Function enderecarQualidade()
	DbSelectArea("SD3")
	SD3->(DbSetOrder(9))
	If SD3->(DbSeek(xFilial("SD3")+AvKey(SD7->D7_NUMERO,"D3_DOC")+AvKey("", "D3_ITEM")+"DE4"))
		lContinua := enderecarItens()
	Else
		FWAlertError("Movimenta  o de libera  o do CQ não encontrada (SD3).", "Qualidade")
		//DisarmTransaction()
		lContinua := .F.
	EndIf
Return lContinua

/*
	Endere ar Itens
*/
Static Function enderecarItens()
	Local aCabecalhoSDA	:= {}	as array
	Local aItemSDB		:= {}	as array
	Local aItensSDB		:= {}	as array
	Local aArea			:= GetArea()	as array

	DbSelectArea("SDA")
	SDA->(DbSetOrder(1))

	SDA->(DbGoTop()) // Posiciona o cabe alho
	If SDA->(DbSeek(xFilial("SDA") + SD3->D3_COD + SD3->D3_LOCAL + SD3->D3_NUMSEQ))
		If SDA->DA_SALDO > 0
			aAdd(aCabecalhoSDA	, {"DA_PRODUTO", SDA->DA_PRODUTO	, Nil})
			aAdd(aCabecalhoSDA	, {"DA_NUMSEQ" , SDA->DA_NUMSEQ		, Nil})

			aAdd(aItemSDB	, {"DB_ITEM"   , "0001"			, Nil})
			aAdd(aItemSDB	, {"DB_ESTORNO", " "			, Nil})
			aAdd(aItemSDB	, {"DB_LOCALIZ", (cAliasTela)->A1_CGC	, Nil})
			aAdd(aItemSDB	, {"DB_DATA"   , Date()			, Nil})
			aAdd(aItemSDB	, {"DB_QUANT"  , SDA->DA_SALDO	, Nil})

			aAdd(aItensSDB, aItemSDB)

			lMsErroAuto := .F.
			MATA265(aCabecalhoSDA, aItensSDB, 3)

			If lMsErroAuto
				cError := getError()
				addLogs(cError)
				//FWAlertError("Endere amento de saldo não realizado.", "Saldo")
				//DisarmTransaction()
				lContinua := .F.
			EndIf
		EndIf
	Else
		FWAlertError("Saldo a endere ar nao encontrado (SDA).", "Saldo")
		//DisarmTransaction()
		lContinua := .F.
	EndIf

	RestArea(aArea)
Return lContinua

/*
	Rotina que recupera o Log da Rotina Autom tica, sem excluir o Log Padr o
*/
Static Function getError(cSeparador)
	Local aAutoErro 	:= GetAutoGRLog()
	Local cLog			:= ""
	Local nLog			:= 1

	Default cSeparador	:= CRLF

	For nLog:=1 to Len(aAutoErro)
		//If (nLog <= 2) .Or. ("Invalido" $ Alltrim(aAutoErro[nLog]))
		cLog += Alltrim(aAutoErro[nLog]) + cSeparador
		//EndIf

		//Refaz a Grava  o do Log de Erro
		AutoGRLog( aAutoErro[nLog] )
	Next nLog
Return cLog

/*
	Tratamento de Logs para Rotina Autom tica e pela Interface com Solu  o
*/
Static Function addLogs(cLogs, cSolucao, lRet)
	Local aSolucao 	:= {}

	Default lRet	:= .F.

	If !( lRet )
		If !Empty(cSolucao)
			aAdd( aSolucao , cSolucao )
		EndIf

		Help(,,"HELP",,cLogs,1,0, Nil, Nil, Nil, Nil, Nil, aSolucao )
	EndIf
Return




/*
	Busca de Op
*/
user Function getLoteOp(cCodigoOrdemProducao)
	Local cCodigoMP          := ""								as character


	dbSelectArea("SD4")
	SD4->(dbSetOrder(2))

	If SD4->(dbSeek(FWxFilial("SD4")+cCodigoOrdemProducao))
		While !SD4->(eof()) .And. Alltrim(SD4->D4_OP) == cCodigoOrdemProducao
			If ( SB1->(dbSeek(FWxFilial("SB1")+SD4->D4_COD)))
				cCodigoMP	:= SD4->D4_COD
				Exit
			Endif
			SD4->(dbSkip())
		Enddo
	Endif


Return cCodigoMP


/*
	tela de f4 do lote
*/
Static Function getLote(cProduto,cLocal,cLote)
	Local cQuery :=''
	Local cAliasSB8 := GetNextAlias()
	Local aAreaAtu    	:= GetArea()
	Local aCabec      	:= {}
	Local nRet        	:= 0
	Local cCadastro   	:= "Selecione o Lote"
	Local aNewButton  	:= {}
	Local lCancel     	:= .T.
	Local lRet			:= .F.
	Local nLinAtu		:=oGridApontamento:nAt
	Local nPosLote:=	aScan(oGridApontamento:aHeader,{ |x| x[2] = "XX_LOTEEMP"    })
	Local nPosApon:=	aScan(oGridApontamento:aHeader,{ |x| x[2] = "XX_APONTOK"    })
	Private aOrc	   	:= {}
	Private aTitulo		:= {}
	aAdd( aTitulo,"Produto " )
	aAdd( aTitulo,"Descri  o" )
	aAdd( aTitulo,"Lote" )
	aAdd( aTitulo,"Saldo" )

	if nLinAtu==1
		FWAlertWarning("A primeira linha não pode ser editada, somente consulta das informa  es.", "Linha de Consulta")
		RETURN(.t.)
	Endif

	if  oGridApontamento:aCols[nLinAtu,nPosApon]=='S'

		FWAlertWarning("Linha ja Apontada nao pode ser alterada!",'Linha Apontada')
		return(.t.)
	EndIf

	cQuery:=" SELECT B8_PRODUTO,B1_DESC,B8_LOTECTL,B8_SALDO FROM "+RetSqlName('SB8')+" SB8
	cQuery+=" inner join "+RetSqlName('SB1')+" SB1 on B1_COD=B8_PRODUTO AND SB1.D_E_L_E_T_=' ' "
	cQuery+=" WHERE "
	cQuery+=" B8_PRODUTO='"+cProduto+" '
	cQuery+=" AND B8_LOCAL='"+cLocal+"'
	cQuery+=" AND substring(B8_LOTECTL,1,6)='"+cLote+"'
	cQuery+=" AND SB8.D_E_L_E_T_=' '  and SB8.B8_SALDO > 0  "
	cQuery+=" ORDER BY
	cQuery+=" B8_LOTECTL

	cQuery := ChangeQuery( cQuery )

	dbUseArea( .t., "TOPCONN", TcGenQry( ,,cQuery ), cAliasSB8, .f., .t. )

	While !( cAliasSB8 )->( Eof())

		aAdd(aOrc,{ ( cAliasSB8 )->B8_PRODUTO,alltrim(( cAliasSB8 )->B1_DESC),( cAliasSB8 )->B8_LOTECTL,( cAliasSB8 )->B8_SALDO })

		( cAliasSB8 )->( dbSkip() )
	EndDo

	( cAliasSB8 )->( dbCloseArea() )


	RestArea(aAreaAtu)
	nRet :=0

	If Len(aOrc)>0
		nRet := TmsF3Array( aTitulo, aOrc, cCadastro, lCancel, aNewButton, aCabec )


		If nRet >0
			oGridApontamento:aCols[nLinAtu][nPosLote]:= aOrc[nRet,3]

			lRet := .T.
		EndIf
	else
		FWAlertWarning("Não existem lotes para o produto "+cProduto+" Armazem "+cLocal,'Linha Apontada')
	EndIf

Return(lRet)

/*
	Busca Produto do Lote selecionado
*/
Static Function buscaProdutoDoLote()
	Local cRetorno	:= ""	as character
	Local cQuery	:= ""	as character

	cQuery	:= queryBuscaProdutoDoLote()

	cRetorno	:= MPSysExecScalar(cQuery, "B8_PRODUTO")
Return cRetorno

/*
	Busca Produto do Lote selecionado
*/
Static Function queryBuscaProdutoDoLote()
	Local cQuery	:= ""	as character

	cQuery += " SELECT " + CRLF
	cQuery += "        B8_PRODUTO "		+ CRLF

	cQuery += " FROM " + CRLF
	cQuery += "     " + RetSQLTab("SB8") + CRLF

	cQuery += " WHERE " + CRLF
	cQuery += " 	    1 = 1 " + CRLF
	cQuery += "	 		AND " + RetSqlFil("SB8") + CRLF
	cQuery += " 		AND B8_LOTECTL  = '"+SZ3->Z3_LOTEEMP+"'" + CRLF
	cQuery += "	    	AND " + RetSqlDel("SB8") + CRLF
Return cQuery
