#include "totvs.ch"
#include "topconn.ch"

namespace producao.etiquetas

/*/ {Protheus.doc} FSPCPA01
Etiqueta tiras para ordem de producao - OP
@type function
@author Elcilei Lopes - DSM
@since 18/06/2024
@version P12
@database ORACLE
/*/

User Function EtiquetaTiras(cAlias,nReg,nOpc)

	Local cPerg             := "ETQTIRAS"	as character
	Local aPerg			    := {}			as array
	Local oProcess        	:= nil			as object

	Private nPortaImp		:= 1			as numeric
	Private nQtdEtqImprimir	:= 0			as numeric
	Private nTipoImpressao	:= 0			as numeric
	Private cSequencia		:= ""			as character
	Private cAliasOP		:= cAlias		as character
	Private lIsMssql		:= .F.			as logical
	Private lSequenceAtivo	:= .F.			as logical
	Private	cCodProduto		:= ""			as character
	Private cNumeroOp		:= ""			as character
	acam := {}
	dbSelectArea("SX3")
	SX3->(dbSetorder(1))
	SX3->(dbSeek("CB0"))
	While !SX3->(eof()) .And. SX3->X3_ARQUIVO == "CB0"
		If CpoObrigat(SX3->X3_CAMPO)
			AADD(acam,SX3->X3_CAMPO)
		Endif
		SX3->(dbSkip())
	Enddo
	cPerg 		:= PADR(cPerg,10)
	cNumeroOp	:= (cAliasOP)->TMP_ORDEM

	SX1->(DBSetOrder(1))

	If( !SX1->(DBSeek(cPerg)) )

		AAdd(aPerg,{"01","Porta Impressao?"			    ,"","","MV_CH01","N",001,0, ,"C","","MV_PAR01", "LPT1","LPT2","LPT3","","","","","","","",""})
		AAdd(aPerg,{"02","Qtd Etiquetas ?"			    ,"","","MV_CH02","N",010,0, ,"C","","MV_PAR02", "","","","","","","","","","",""})
		AAdd(aPerg,{"03","Tipo Impressao?"			    ,"","","MV_CH03","N",001,0, ,"C","","MV_PAR03", "Individual","Tudo","","","","","","","","",""})
		AAdd(aPerg,{"04","Sequencia Etiqueta"		    ,"","","MV_CH04","C",006,0, ,"C","","MV_PAR04", "","","","","","","","","","",""})

		AjustaSX1(cPerg, aPerg,{})

	Endif

	If ( SX1->(dbSeek(cPerg+"02")))
		RecLock("SX1",.F.)
		SX1->X1_CNT01 := Alltrim(Str((cAliasOP)->TMP_AMARRA))
		MsUnlock()
	Endif

	If !Pergunte(cPerg,.T.)
		Return
	endif

	nPortaImp		:= MV_PAR01
	nQtdEtqImprimir	:= MV_PAR02
	nTipoImpressao	:= MV_PAR03
	cSequencia		:= MV_PAR04

	oProcess	:=	MsNewProcess():New( { |lEnd| GeraEtiqueta(@oProcess) },"Criando Etiquetas","Executando...",.t.)
	oProcess:Activate()

Return

/*/	
	Programa para imprimir etiqueta
/*/

Static Function GeraEtiqueta(oProcess)
	Local cLoteOp           := ""	as character
	Local cDescProduto      := ""	as character

	dbSelectArea("SB1")
	SB1->(dbSetOrder(1))

	oProcess:SetRegua1( nQtdEtqImprimir )
	oProcess:IncRegua1( "Imprimindo Etiqueta")
	cCodProduto	:= AvKey((cAliasOP)->C2_PRODUTO,"B1_COD")

	SB1->(dbSeek(FWxFilial("SB1")+cCodProduto))
	cDescProduto := Alltrim(SB1->B1_DESC)

	cLoteOp := getLoteOp()
	If Empty( cLoteOp )
		Return
	Endif

	ImprimirEtiqueta(@oProcess,cLoteOp,cDescProduto,nQtdEtqImprimir)

Return

/*/
	Imprimir a Etiqueta
/*/
Static Function ImprimirEtiqueta(oProcess,cLoteOp,cDescProduto,nQtEtiquetas)
	Local nRecord       	:= 0								as numeric
	Local cPagaQtd      	:= ""								as character
	Local cCodigoZPL    	:= ""								as character
	Local cPorta			:= ""								as character
	Local cModelo			:= GetNewPar("ZV_MODELET","ZEBRA")	as character
	Local aDesProduto		:= {}								as array
	Local cVelocidade		:= GetNewPar("ZV_VELETTR","4,4")	as character
	Local cTemperatura		:= GetNewPar("ZV_TEMETTR","10")	as character

	Default cDescProduto	:= ""
	Default cLoteOp			:= ""
	Default nQtEtiquetas	:= 1

	lSequenceAtivo			:= GetNewPar("ZM_CB0SEQ",.T.)

	If ( nTipoImpressao == 1 )
		If Empty(cSequencia)
			FWAlertInfo("Para imprimir etiqueta individual é obrigatório informar 'Sequencia Etiqueta'!", "Etiqueta de Tira")
			Return
		Endif
		nQtEtiquetas := 1
		cPagaQtd := cSequencia
	Endif

	If nPortaImp == 1
		cPorta := "LPT1"
	ElseIf nPortaImp == 2
		cPorta := "LPT2"
	ElseIf nPortaImp == 3
		cPorta := "LPT3"
	Endif

	aDesProduto := quebraString(cDescProduto,27)

	MSCBPRINTER(cModelo ,cPorta,, 10,.F.,,,,,,.f.)

	MSCBCHKSTATUS(.F.)

	oProcess:SetRegua2( nQtEtiquetas )

	For nRecord := 1 To nQtEtiquetas

		If Empty( cPagaQtd )
			cPagaQtd := Alltrim(Str(nRecord))+"/"+Alltrim(Str(nQtEtiquetas))
		Endif

		oProcess:IncRegua2( "Etiqueta: "+Alltrim(cPagaQtd))

		gravaCB0(cDescProduto,cLoteOp,cPagaQtd)

		MSCBBEGIN(1,6)

		cCodigoZPL := ""

		cCodigoZPL += "^XA"+CRLF
		cCodigoZPL += "~TA000"+CRLF
		cCodigoZPL += "~JSN"+CRLF
		cCodigoZPL += "^LT0"+CRLF
		cCodigoZPL += "^MNW"+CRLF
		cCodigoZPL += "^MTT"+CRLF
		cCodigoZPL += "^PON"+CRLF
		cCodigoZPL += "^PMN"+CRLF
		cCodigoZPL += "^LH0,0"+CRLF
		cCodigoZPL += "^JMA"+CRLF
		cCodigoZPL += "^PR"+Alltrim(cVelocidade)+CRLF
		cCodigoZPL += "~SD"+Alltrim(cTemperatura)+CRLF
		cCodigoZPL += "^JUS"+CRLF
		cCodigoZPL += "^LRN"+CRLF
		cCodigoZPL += "^CI27"+CRLF
		cCodigoZPL += "^PA0,1,1,0"+CRLF
		cCodigoZPL += "^XZ"+CRLF
		cCodigoZPL += "^XA"+CRLF
		cCodigoZPL += "^MMT"+CRLF
		cCodigoZPL += "^PW831"+CRLF
		cCodigoZPL += "^LL152"+CRLF
		cCodigoZPL += "^LS0"+CRLF
		cCodigoZPL += "^FO2,4^GB825,144,1^FS"+CRLF
		cCodigoZPL += "^FT15,43^A0N,35,35^FH\^CI28^FD"+cLoteOp+"^FS^CI27"+CRLF
		cCodigoZPL += "^FO169,6^GB0,141,1^FS"+CRLF
		cCodigoZPL += "^FO2,68^GB166,0,1^FS"+CRLF
		cCodigoZPL += "^FT60,118^A0N,40,40^FH\^CI28^FD"+cPagaQtd+"^FS^CI27"+CRLF
		cCodigoZPL += "^FO651,6^GB0,141,1^FS"+CRLF
		cCodigoZPL += "^FT678,132^BQN,2,5"+CRLF
		cCodigoZPL += "^FH\^FDLA,"+cLoteOp+"^FS"+CRLF
		If ( Len(aDesProduto)  >= 1 )
			cCodigoZPL += "^FT181,44^A0N,40,40^FH\^CI28^FD"+aDesProduto[1]+"^FS^CI27"+CRLF
		Endif
		If ( Len(aDesProduto)  >= 2 )
			cCodigoZPL += "^FT179,75^A0N,40,40^FH\^CI28^FD"+aDesProduto[2]+"^FS^CI27"+CRLF
		Endif
		If ( Len(aDesProduto)  >= 3 )
			cCodigoZPL += "^FT179,107^A0N,40,40^FH\^CI28^FD"+aDesProduto[3]+"^FS^CI27"+CRLF
		Endif
		cCodigoZPL += "^PQ1,,,Y"+CRLF
		cCodigoZPL += "^XZ"+CRLF

		MSCBWrite(cCodigoZPL)
		MSCBEND()
		cPagaQtd := ""
	Next
	MSCBCLOSEPRINTER()

Return

/*/
	Verificar o lote da ordem de producao
/*/
Static Function getLoteOp()
	Local cRet     := "" as character
	Local cOPFilha := "" as character
	// Local cGrupoProduto := GetNewPar("ZM_GRPPROD","01")		as character

	dbSelectArea("SD4")
	SD4->(dbSetOrder(2))

	If SD4->(dbSeek(FWxFilial("SD4")+cNumeroOp))
		While !SD4->(eof()) .And. Alltrim(SD4->D4_OP) == cNumeroOp
			// If ( SB1->(dbSeek(FWxFilial("SB1")+SD4->D4_COD))) .And. ( SubStr(SB1->B1_COD,1,2) $ cGrupoProduto )
			// RODOLFO - 24/02/2025 - OPCAO O.P ROLOS
			If SD4->D4_LOTECTL == (cAliasOP)->C5_ZLOTCTL
				cRet := SD4->D4_LOTECTL
				Exit
			EndIf
			SD4->(dbSkip())
		Enddo
	EndIf

	If Empty(cRet)

		// Procurar LOTE O.P Filha
		If Substr(cNumeroOp,9,3) == "001"
			cOPFilha := Substr(cNumeroOp,1,8)+"002"
			If SD4->(dbSeek(FWxFilial("SD4")+cOPFilha))
				While !SD4->(eof()) .And. Alltrim(SD4->D4_OP) == cOPFilha
					If SD4->D4_LOTECTL == (cAliasOP)->C5_ZLOTCTL
						cRet := SD4->D4_LOTECTL
						Exit
					EndIf
					SD4->(dbSkip())
				EndDo
			EndIf
		EndIf
	EndIf

	If Empty(cRet)
		FWAlertInfo("Não foi possível localizar Lote!", "Etiqueta de Tira")
	EndIf

Return cRet

/*/
	Programa Ajusta parametro de pergunta
/*/

Static Function AjustaSX1( cPerg, aPerg, aHelp )
	Local aArea     := GetArea()	as array
	Local aCpoPerg  := {}			as array
	Local nX        := 0			as numeric
	Local nY        := 0			as numeric

	// DEFINE ESTRUTUA DO ARRAY DAS PERGUNTAS COM AS PRINCIPAIS INFORMACOES
	AADD( aCpoPerg, 'X1_ORDEM'   ) 	// 01 = Ordem da Pergunta
	AADD( aCpoPerg, 'X1_PERGUNT' ) 	// 02 = Descricao Portugues
	AADD( aCpoPerg, 'X1_PERSPA'  ) 	// 03 = Descrucai Espanhol
	AADD( aCpoPerg, 'X1_PERENG'  ) 	// 04 = Descricao Ingles
	AADD( aCpoPerg, 'X1_VARIAVL' ) 	// 05 = Variavel do item "mv_ch"
	AADD( aCpoPerg, 'X1_TIPO'    ) 	// 06 = Tipo do conteudo de resposta da pergunta
	AADD( aCpoPerg, 'X1_TAMANHO' ) 	// 07 = Tamanho do campo para a resposta da pergunta
	AADD( aCpoPerg, 'X1_DECIMAL' ) 	// 08 = Numero de casas decimais da resposta, se houver
	AADD( aCpoPerg, 'X1_PRESEL'  ) 	// 09 = Item do cambo selecionado. Parametro cGSC = "C"
	AADD( aCpoPerg, 'X1_GSC'     ) 	// 10 = Tipo pergunta "G" = Permite editar, "S" - Texto sem altera?o e "C" = Selecao de Dados
	AADD( aCpoPerg, 'X1_VALID'   ) 	// 11 = Valida?o do item
	AADD( aCpoPerg, 'X1_VAR01'   ) 	// 12 = Nome do MV_PAR para a utiliza?o nos programas
	AADD( aCpoPerg, 'X1_DEF01'   ) 	// 13 = Conteudo Portugues primeiro combo
	AADD( aCpoPerg, 'X1_DEF02' 	 ) 	// 14 = Conteudo Portugues segundo combo
	AADD( aCpoPerg, 'X1_DEF03'   ) 	// 15 = Conteudo Portugues terceiro combo
	AADD( aCpoPerg, 'X1_DEF04'   ) 	// 16 = Conteudo Portugues quarto combo
	AADD( aCpoPerg, 'X1_DEF05'   ) 	// 17 = Conteudo Portugues quinto combo
	AADD( aCpoPerg, 'X1_CNT01'   ) 	// 18 = Conteudo padrao da pergunta
	AADD( aCpoPerg, 'X1_F3'      ) 	// 19 = Nome da consulta F3
	AADD( aCpoPerg, 'X1_PYME'    ) 	// 20 = Se a pergunta estara disponivel no ambiente Pyme
	AADD( aCpoPerg, 'X1_GRPSXG'  ) 	// 21 = C?igo do grupo de campos SXG para atualizacao automatica
	AADD( aCpoPerg, 'X1_HELP'    ) 	// 22 = Conteudo do campo X1_HELP
	AADD( aCpoPerg, 'X1_PICTURE' ) 	// 23 = Picture de formata?o do conteudo
	DBSelectArea( "SX1" )
	DBSetOrder( 1 )
	For nX := 1 To Len( aPerg )
		IF !DBSeek( PADR(cPerg,10) + aPerg[nX][1] )
			RecLock( "SX1", .T. )	// Inclui
		Else
			RecLock( "SX1", .F. )	// Altera
		Endif
		// Grava informacoes dos campos da SX1
		For nY := 1 To Len( aPerg[nX] )
			If aPerg[nX][nY] <> NIL
				SX1->( &( aCpoPerg[nY] ) ) := aPerg[nX][nY]
			EndIf
		Next
		SX1->X1_GRUPO := PADR(cPerg,10)

		MsUnlock()	// Libera Registro
	Next
	// Apaga perguntas nao definidas no array
	DBSEEK(cPerg,.T.)
	DO WHILE SX1->(!Eof()) .And. SX1->X1_GRUPO == cPerg
		IF ASCAN(aPerg,{|Y| Y[1] == SX1->X1_ORDEM}) == 0
			Reclock("SX1", .F.)
			SX1->(DBDELETE())
			Msunlock()
		ENDIF
		SX1->(DBSKIP())
	ENDDO

	RestArea( aArea )
Return

/*/
	Quebra a string Descricao
/*/
Static Function quebraString(cDescricao,nTamnhoLinha)
	Local nLinhas			:= 0
	Local nRecord			:= 0
	Local aRet				:= {"",""}

	Default cDescricao		:= ""
	Default nTamnhoLinha	:= 0

	If !Empty(cDescricao)
		nLinhas := MLCount(cDescricao,nTamnhoLinha)
		For nRecord := 1 To nLinhas
			If ( nRecord <= 2)
				aRet[nRecord] := MemoLine(cDescricao,nTamnhoLinha,nRecord)
			Endif
		Next
	Endif

Return aRet


/*
	Executa a Gravação da Etiqueta na Tabela CB0, 
*/
Static Function gravaCB0(cDescProduto,cLoteOp,cNumSeq)
	Local cCodigoEtiqueta	:= ""	as character

	dbSelectArea("CB0")
	CB0->(dbSetOrder(1))

	cCodigoEtiqueta := lib.u_buscaCB0()

	Reclock("CB0",.T.)
	CB0->CB0_FILIAL	:= FwxFilial("CB0")
	CB0->CB0_CODETI	:= cCodigoEtiqueta
	CB0->CB0_DTNASC	:= dDatabase
	CB0->CB0_TIPO  	:= "01"
	CB0->CB0_CODPRO	:= cCodProduto
	CB0->CB0_QTDE  	:= 1
	CB0->CB0_USUARI	:= RetCodUsr()
	CB0->CB0_LOTE  	:= cLoteOp
	CB0->CB0_NUMSEQ	:= cNumSeq
	CB0->CB0_OP    	:= cNumeroOp
	CB0->CB0_PALLET := "0"
	MsUnlock()
Return

