#include "totvs.ch"
#include "topconn.ch"
#include "tbiconn.ch"
#include "tbicode.ch"

namespace producao.etiquetas

/*/ {Protheus.doc} EtiquetaAberturaOp

Etiqueta de ordem de producao - OP

@type function
@author Elcilei Lopes - DSM
@since 18/06/2024
@version P12
@database ORACLE
/*/
User Function EtiquetaAberturaOp(cCodigoOrdemProducao)

	Local oProcess        	:= nil			as object
	Local aPergs			:= {}			as array

	Private nPortaImp		:= 1			as numeric
	Private cAlias          := ""			as character
	Private aLogImpressao	:= {}			as array
	Private cObservacoes	:= ""			as character
	Private nQtdEtqImprimir := 1			as numeric

	DEFAULT cCodigoOrdemProducao := ""

	If Empty(cCodigoOrdemProducao)
		FWAlertInfo("Ordem de Produção não informada!", "Etiqueta Produção")
		Return
	EndIf

	aadd(aPergs, {2, "Porta Impressao?", nPortaImp, {"1=LPT1", "2=LPT2", "3=LPT3"}, 122, ".T.", .F.})

	cObservacoes := SPACE(20)
	aadd(aPergs, {1, "OBS.", cObservacoes, "", ".T.", "SB1", ".T.", 80, .F.})

	aAdd(aPergs, {1, "Qtde. por Amarrado?",  nQtdEtqImprimir,  "@E 9,999",     "Positivo()", "", ".T.", 80,  .F.})

	If ParamBox(aPergs, "Informe os parâmetros")
		nPortaImp       := MV_PAR01
		cObservacoes    := MV_PAR02
		nQtdEtqImprimir := MV_PAR03

		oProcess	:=	MsNewProcess():New( { |lEnd| GeraEtiqueta(@oProcess, cCodigoOrdemProducao) },"Criando Etiquetas","Executando...",.t.)
		oProcess:Activate()
	EndIf

Return

/*/
	Programa para imprimir etiqueta
/*/

Static Function GeraEtiqueta(oProcess, cCodigoOrdemProducao)
	Local cQuery            := ""	as character
	Local nTotalReg         := 0	as numeric
	Local lRet				:= .T.	as logical

	Private cCodProduto     := ""	as character
	Private cNumeroOp       := ""	as character
	Private cItemOp			:= ""	as character
	Private cSequenciaOp	:= ""	as character
	Private cLoteOp         := ""	as character
	Private cClienteNome	:= ""	as character
	Private cClientePedido	:= ""	as character
	Private cLojaPedido		:= ""	as character
	Private cNumeroInspecao	:= ""	as character
	Private cCodigoPA		:= ""	as character
	Private cDescProduto	:= ""	as character
	Private nQtdPeso		:= 0	as numeric
	Private nQtdPecas		:= 0	as numeric
	Private cCodQualidade	:= ""	as character
	Private cCodigoMP		:= ""	as character
	Private cTituloMsg		:= ""	as character
	Private cNumInspecao	:= ""	as character
	Private cIdBobina		:= ""	as character
	Private nQuant			:= 0    as numeric
	Private nPeso			:= 0    as numeric
	Private cLoteSc2		:= ""   as character
	cTituloMsg := "Etiqueta de OP"

	dbSelectArea("SB5")
	SB5->(dbSetOrder(1))

	dbSelectArea("SB1")
	SB1->(dbSetOrder(1))

	cQuery := getQuery(cCodigoOrdemProducao)

	TCQUERY CQUERY NEW ALIAS(cAlias:=GetNextAlias())
	Count To nTotalReg

	dbSelectArea(cAlias)
	(cAlias)->(dbGotop())
	If ( (cAlias)->(EOF()) )
		cMsg := "Não há dados a serem impresso!"
		Help(,,"HELP",,cMsg,1,0)
		lRet := .F.
	EndIf

	If ( !lRet )
		If ( Select(cAlias) > 0 )
			(cAlias)->(dbCloseArea())
		Endif
		Return
	Endif

	oProcess:SetRegua1( nTotalReg )

	While ( (cAlias)->(!EOF()) )

		oProcess:IncRegua1( "Processando O.P: " + (cAlias)->C2_NUM + " ..." )

		cCodProduto 	:= AvKey((cAlias)->C2_PRODUTO,"B1_COD")
		cNumeroOp      	:= Alltrim((cAlias)->C2_NUM)
		cItemOp			:= Alltrim((cAlias)->C2_ITEM)
		cSequenciaOp	:= Alltrim((cAlias)->C2_SEQUEN)

		cClienteNome	:= getClientePedido((cAlias)->C2_PEDIDO)
		cLoteSc2		:= cNumeroOp+ cItemOp + cSequenciaOp
		If ( Empty(cClienteNome) )
			(CAlias)->(dbSkip())
			Loop
		Endif

		cLoteOp := cIdBobina // getLoteOp(cCodigoOrdemProducao)

		If (Empty(cLoteOp))
			(CAlias)->(dbSkip())
			Loop
		Endif

		// nQtdEtqImprimir := getDadosComplementar()

		If ( nQtdEtqImprimir == 0)
			(CAlias)->(dbSkip())
			Loop
		Endif

		cCodQualidade := getCodigoQualidade()

		If ( Empty(cCodQualidade) )
			(CAlias)->(dbSkip())
			Loop
		Endif

		cNumeroInspecao	:= cNumInspecao // getNumeroInspecao()


		If ( Empty(cNumeroInspecao) )
			(CAlias)->(dbSkip())
			Loop
		Endif

		cCodigoPA		:= getCodigoPa()

		If ( Empty(cCodigoPA) )
			(CAlias)->(dbSkip())
			Loop
		Endif

		cDescProduto	:= getDescicaoMaterial()

		// Para O.P de Rolos não calcular nada
		// nQtdEtqImprimir := Ceiling((cAlias)->C2_QUANT/nQtdEtqImprimir)

		dDataEmissao	:= dDataBase

		ImprimirEtiqueta(@oProcess,cCodigoOrdemProducao,cLoteSc2)

		(cAlias)->(dbSkip())
	Enddo

Return

/*/
	Imprimir a Etiqueta
/*/
Static Function ImprimirEtiqueta(oProcess,cCodigoOrdemProducao,cLoteSc2)
	Local nRecord       	:= 0								as numeric
	Local cPagaQtd      	:= ""								as character
	Local cCodigoZPL    	:= ""								as character
	Local cPorta			:= ""								as character
	Local cModelo			:= GetNewPar("ZV_MODELET","ZEBRA")	as character
	Local aDesProduto		:= {}								as array
	Local cVelocidade		:= GetNewPar("ZV_VELETOP","4,4")	as character
	Local cTemperatura		:= GetNewPar("ZV_TEMETOP","10")		as character
	Local cQrcod			:= ""								as character

	Private cCodigoEtiqueta	:= ""								as character

	If nPortaImp == 1
		cPorta := "LPT1"
	ElseIf nPortaImp == 2
		cPorta := "LPT2"
	ElseIf nPortaImp == 3
		cPorta := "LPT3"
	Endif

	aDesProduto := quebraString(cDescProduto,60)

	MSCBPRINTER(cModelo ,cPorta,, 10,.F.,,,,,,.f.)
	MSCBCHKSTATUS(.F.)
	MSCBBEGIN(1,6)

	oProcess:SetRegua2( nQtdEtqImprimir )

	For nRecord := 1 To nQtdEtqImprimir

		//carrega dados de quantidade e peso
		getQuerySH6(nRecord,cCodigoOrdemProducao)

		cPagaQtd := Alltrim(Str(nRecord))+"/"+Alltrim(Str(nQtdEtqImprimir))

		oProcess:IncRegua2( "Etiqueta: "+Alltrim(cPagaQtd))

		gravaCB0(cDescProduto,cLoteOp,cPagaQtd)

		cQrcod := Alltrim(cLoteOp)+cPagaQtd+cCodigoEtiqueta+alltrim(cLoteSc2)

		cCodigoZPL := ""

		cCodigoZPL += "^XA"+CRLF
		cCodigoZPL += "~TA000"+CRLF
		cCodigoZPL += "~JSN"+CRLF
		cCodigoZPL += "^LT0"+CRLF
		cCodigoZPL += "^MNW"+CRLF
		cCodigoZPL += "^MTT"+CRLF
		cCodigoZPL += "^PON"+CRLF
		cCodigoZPL += "^PMN"+CRLF
		cCodigoZPL += "^LH0,0"+CRLF
		cCodigoZPL += "^JMA"+CRLF
		cCodigoZPL += "^PR"+Alltrim(cVelocidade)+CRLF
		cCodigoZPL += "~SD"+Alltrim(cTemperatura)+CRLF
		cCodigoZPL += "^JUS"+CRLF
		cCodigoZPL += "^LRN"+CRLF
		cCodigoZPL += "^CI27"+CRLF
		cCodigoZPL += "^PA0,1,1,0"+CRLF
		cCodigoZPL += "^XZ"+CRLF
		cCodigoZPL += "^XA"+CRLF
		cCodigoZPL += "^MMT"+CRLF
		cCodigoZPL += "^PW839"+CRLF
		cCodigoZPL += "^LL1199"+CRLF
		cCodigoZPL += "^LS0"+CRLF
		cCodigoZPL += "^FO58,13^GB770,1170,2^FS"+CRLF
		cCodigoZPL += "^FT790,28^A0R,30,30^FH\^CI28^FDID:^FS^CI27"+CRLF
		cCodigoZPL += "^FT740,28^A0R,60,60^FH\^CI28^FD"+cLoteOp+"^FS^CI27"+CRLF
		cCodigoZPL += "^FO59,979^GB770,0,2^FS"+CRLF
		cCodigoZPL += "^FT790,321^A0R,30,30^FH\^CI28^FDAmarrado : ^FS^CI27"+CRLF
		cCodigoZPL += "^FT757,321^A0R,40,40^FH\^CI28^FD"+cPagaQtd+"^FS^CI27"+CRLF
		cCodigoZPL += "^FO716,625^GB112,0,2^FS"+CRLF
		cCodigoZPL += "^FT790,638^A0R,30,30^FH\^CI28^FDLote Centrasa^FS^CI27"+CRLF
		cCodigoZPL += "^FO716,309^GB112,0,2^FS"+CRLF
		cCodigoZPL += "^FT682,28^A0R,30,30^FH\^CI28^FDCliente^FS^CI27"+CRLF
		cCodigoZPL += "^FO605,18^GB0,965,2^FS"+CRLF
		cCodigoZPL += "^FT643,28^A0R,40,40^FH\^CI28^FD"+cClienteNome+"^FS^CI27"+CRLF
		cCodigoZPL += "^FT568,28^A0R,30,30^FH\^CI28^FDMaterial^FS^CI27"+CRLF
		If Len(aDesProduto) >= 1
			cCodigoZPL += "^FT535,28^A0R,40,40^FH\^CI28^FD"+aDesProduto[1]+"^FS^CI27"+CRLF
		Endif

		If Len(aDesProduto) >= 2
			cCodigoZPL += "^FT493,28^A0R,40,40^FH\^CI28^FD"+aDesProduto[2]+"^FS^CI27"+CRLF
		Endif
		cCodigoZPL += "^FT757,646^A0R,40,40^FH\^CI28^FD"+cLoteSc2+"^FS^CI27"+CRLF
		cCodigoZPL += "^FO363,620^GB120,0,2^FS"+CRLF
		cCodigoZPL += "^FO363,309^GB118,0,2^FS"+CRLF
		cCodigoZPL += "^FO245,471^GB118,0,2^FS"+CRLF
		cCodigoZPL += "^FO101,471^GB141,0,2^FS"+CRLF
		cCodigoZPL += "^FO57,471^GB108,0,2^FS"+CRLF
		cCodigoZPL += "^FO151,17^GB0,457,2^FS"+CRLF
		cCodigoZPL += "^FT444,28^A0R,30,30^FH\^CI28^FDProduto Centrasa:^FS^CI27"+CRLF
		cCodigoZPL += "^FT405,28^A0R,40,40^FH\^CI28^FD"+cCodProduto+"^FS^CI27"+CRLF
		cCodigoZPL += "^FT444,321^A0R,30,30^FH\^CI28^FDCod. Qualidade^FS^CI27"+CRLF
		cCodigoZPL += "^FT405,321^A0R,40,40^FH\^CI28^FD"+cCodQualidade+"^FS^CI27"+CRLF
		cCodigoZPL += "^FT451,638^A0R,30,30^FH\^CI28^FDObservacao:^FS^CI27"+CRLF
		cCodigoZPL += "^FT327,28^A0R,30,30^FH\^CI28^FDNumero Inspecao:^FS^CI27"+CRLF
		cCodigoZPL += "^FT285,28^A0R,40,40^FH\^CI28^FD"+cNumeroInspecao+"^FS^CI27"+CRLF
		cCodigoZPL += "^FT327,490^A0R,30,30^FH\^CI28^FDCod.Cliente^FS^CI27"+CRLF
		
		If Len(cCodigoPA) > 20
			cCodigoZPL += "^FT285,494^A0R,30,30^FH\^CI28^FD"+cCodigoPA+"^FS^CI27"+CRLF
		Else
			cCodigoZPL += "^FT285,494^A0R,40,40^FH\^CI28^FD"+cCodigoPA+"^FS^CI27"+CRLF
		EndIf
		
		cCodigoZPL += "^FT206,28^A0R,30,30^FH\^CI28^FDQtd. Peso:^FS^CI27"+CRLF
		cCodigoZPL += "^FT0170,200^A0R,60,60^FH\^CI28^FD"+cValtochar(nPeso)+"^FS^CI27"+CRLF  // Peso ajustar
		cCodigoZPL += "^FT124,28^A0R,30,30^FH\^CI28^FDQtd. Pecas:^FS^CI27"+CRLF
		cCodigoZPL += "^FT080,200^A0R,60,60^FH\^CI28^FD"+cValtochar(nQuant)+"^FS^CI27"+CRLF  // peças ajutar
		cCodigoZPL += "^FT206,490^A0R,30,30^FH\^CI28^FDDisposicao:^FS^CI27"+CRLF
		cCodigoZPL += "^FO716,13^GB0,965,2^FS"+CRLF
		cCodigoZPL += "^FO479,14^GB0,965,2^FS"+CRLF
		cCodigoZPL += "^FO363,14^GB0,965,2^FS"+CRLF
		cCodigoZPL += "^FO243,15^GB0,965,2^FS"+CRLF
		cCodigoZPL += "^FT79,1186^BQN,2,8"+CRLF
		cCodigoZPL += "^FH\^FDLA,"+cLoteSc2+"^FS"+CRLF
		cCodigoZPL += "^FT34,18^A0R,30,30^FH\^CI28^FD"+cUserName+"^FS^CI27"+CRLF
		cCodigoZPL +="^FT34,900^A0R,30,30^FH\^CI28^FDData :"+DTOC(dDatabase)+"^FS^CI27"+CRLF
		cCodigoZPL += "^PQ1,,,Y"+CRLF
		cCodigoZPL += "^XZ"+CRLF

		MSCBWrite(cCodigoZPL)
		MSCBEND()

	Next
	MSCBCLOSEPRINTER()

Return

/*/
	Gerar codigo do cliente
/*/
Static Function getCodigoPa()
	Local cRet	:= ""	as character

	dbSelectArea("SB1")
	SB1->(dbSetOrder(1))

	dbSelectArea("SA7")
	SA7->(dbSetOrder(2))

	If SA7->(dbSeek(FWxFilial("SA7")+cCodProduto))
		cRet := AllTrim(SA7->A7_CODCLI)
	Endif

	If Empty(cRet)
		If ( SB1->(dbSeek(FWxFilial("SB1")+cCodProduto)) )
			cRet := AllTrim(SB1->B1_ZCODCLI)
		Endif
		If Empty(cRet)
			Aadd(aLogImpressao,{cNumeroOp,cItemOp,cSequenciaOp,"Não foi possível localizar código cliente P.A."})
			FWAlertInfo("Não foi possível localizar código cliente P.A.!", cTituloMsg)
		Endif
	Endif

Return cRet

/*/
	Gerar lote do fornecedor
/*/
Static Function getNumeroInspecao()
	Local cRet	:= ""	as character

	dbSelectArea("SB8")
	SB8->(dbSetorder(5))

	If SB8->(dbSeek(FWxFilial("SB8")+cCodigoMP+cLoteOp))
		cRet := SB8->B8_LOTEFOR
	Endif

	If Empty(cRet)
		Aadd(aLogImpressao,{cNumeroOp,cItemOp,cSequenciaOp,"Não foi possível localizar numero da inspeção."})
		FWAlertInfo("Não foi possível localizar numero da inspeção", cTituloMsg)
	Endif

Return cRet

/*/
	Gerar codigo da qualidade
/*/
Static Function getCodigoQualidade()
	Local cRet				:= ""	as character
	Local cProdQualidade	:= ""	as character

	dbSelectArea("SB8")
	SB8->(dbSetOrder(2))

	dbSelectArea("SB1")
	SB1->(dbSetOrder(1))

	If ( SB8->(dbSeek(FWxFilial("SB8")+AvKey("", "B8_NUMLOTE")+cIdBobina)))
		cProdQualidade := SB8->B8_PRODUTO
		If ( SB1->(dbSeek(FWxFilial("SB1")+cProdQualidade)) )
			cRet := SubStr(SB1->B1_ZDESCQ,1,20)
		Endif
	Endif

	If Empty(cRet)
		Aadd(aLogImpressao,{cNumeroOp,cItemOp,cSequenciaOp,"Não foi possível localizar qualidade da bobina."})
		FWAlertInfo("Não foi possível localizar qualidade da bobina!", cTituloMsg)
	Endif

Return cRet

/*/
	gerar a descrição do material
/*/
Static Function getDescicaoMaterial()
	Local cRet	:= ""	as character

	dbSelectArea("SD4")
	SD4->(dbSetOrder(2))

	If SD4->(dbSeek(FWxFilial("SD4")+cNumeroOp+cItemOp+cSequenciaOp))
		If ( SB1->(dbSeek(FWxFilial("SB1")+SD4->D4_PRODUTO)))
			cRet	:= Alltrim(SB1->B1_DESC)
		Endif
	Endif

	If Empty(cRet)
		FWAlertInfo("Não foi possível localizar descrição do 'Material'!", cTituloMsg)
	Endif

Return cRet

/*/
	Verificar o lote da ordem de producao
/*/
Static Function getLoteOp(cCodigoOrdemProducao)
	Local cRet          := ""								as character
	Local cOPFilha      := ""								as character
	Local cGrupoProduto := GetNewPar("ZM_GRPPROD","01")		as character

	dbSelectArea("SD4")
	SD4->(dbSetOrder(2))

	// If SD4->(dbSeek(FWxFilial("SD4")+cCodigoOrdemProducao))
	// 	While !SD4->(eof()) .And. Alltrim(SD4->D4_OP) == cCodigoOrdemProducao
	// 		If ( SB1->(dbSeek(FWxFilial("SB1")+SD4->D4_COD))) .And. ( SubStr(SB1->B1_COD,1,2) $ cGrupoProduto )
	// 			cRet 		:= SD4->D4_LOTECTL
	// 			cCodigoMP	:= SD4->D4_COD
	// 			Exit
	// 		Endif
	// 		SD4->(dbSkip())
	// 	Enddo
	// Endif

	If SD4->(dbSeek(FWxFilial("SD4")+cCodigoOrdemProducao))
		While !SD4->(eof()) .And. Alltrim(SD4->D4_OP) == cCodigoOrdemProducao
			If SD4->D4_LOTECTL == (cAliasOP)->C5_ZLOTCTL
				cRet := SD4->D4_LOTECTL
				cCodigoMP := SD4->D4_COD
				Exit
			EndIf
			SD4->(dbSkip())
		Enddo
	EndIf

	If Empty(cRet)

		// Procurar LOTE O.P Filha
		If Substr(cCodigoOrdemProducao,9,3) == "001"
			cOPFilha := Substr(cCodigoOrdemProducao,1,8)+"002"
			If SD4->(dbSeek(FWxFilial("SD4")+cOPFilha))
				While !SD4->(eof()) .And. Alltrim(SD4->D4_OP) == cOPFilha
					If SD4->D4_LOTECTL == (cAliasOP)->C5_ZLOTCTL
						cRet := SD4->D4_LOTECTL
						cCodigoMP := SD4->D4_COD
						Exit
					EndIf
					SD4->(dbSkip())
				EndDo
			EndIf
		EndIf
	EndIf

	If Empty(cRet)
		Aadd(aLogImpressao,{cNumeroOp,cItemOp,cSequenciaOp,"Nenhum apontamento realizado para esta O.P!"})
		FWAlertInfo("Nenhum apontamento realizado para esta O.P!", cTituloMsg)
	Endif

Return cRet

/*/
	Verificar dados complementar
/*/
Static Function getDadosComplementar()
	Local nRet          := 0	as numeric

	If !empty(cCodProduto)
		If SB5->(dbSeek(FWxFilial("SB5")+cCodProduto))
			nRet := SB5->B5_FATARMA
		Endif
	Endif

	If ( nRet == 0 )
		Aadd(aLogImpressao,{cNumeroOp,cItemOp,cSequenciaOp,"Não existe dados complementares do Produto.(Fator Armaz.)"})
		FWAlertInfo("Não existe dados complementares do Produto.(Fator Armaz.)!", cTituloMsg)

	Endif


Return nRet

/*/
	Consultar cliente no pedido vinculado a ordem de produção
/*/
Static Function getClientePedido(cNumPedido)
	Local cRet			:= ""	as character

	Default cNumPedido 	:= ""

	dbSelectArea("SA1")
	SA1->(dbSetOrder(1))

	dbSelectArea("SC5")
	SC5->(dbSetOrder(1))
	If SC5->(dbSeek(FWxFilial("SC5")+cNumPedido))
		cRet 			:= SC5->C5_ZENTREG
		cNumInspecao	:= SC5->C5_ZINSPE
		cIdBobina		:= SC5->C5_ZLOTCTL
		SA1->(dbSeek(FWxFilial("SA1")+SC5->C5_CLIENTE+SC5->C5_LOJACLI))
		cLojaPedido		:= SA1->A1_LOJA
		cClientePedido	:= SA1->A1_COD
	Else
		Aadd(aLogImpressao,{cNumeroOp,cItemOp,cSequenciaOp,"Pedido de venda não encontrado para OP."})
		FWAlertInfo("Pedido de venda não encontrado para OP!", cTituloMsg)
	Endif

Return cRet

/*/
	Query ordem de producao
/*/
Static Function getQuery(cCodigoOrdemProducao)
	Local cQyery := ""	as character

	cQyery += "SELECT * FROM "+RetSQLTab("SC2")+CRLF
	cQyery += "WHERE "+RetSqlDel("SC2")+CRLF
	cQyery += "AND "+RetSqlFil("SC2")+CRLF
	cQyery += "AND C2_NUM||C2_ITEM||C2_SEQUEN = "+ValToSql(alltrim(cCodigoOrdemProducao))+CRLF
	cQyery += "ORDER BY C2_NUM,C2_ITEM"

Return cQyery

/*/
	Quebra a string Descricao
/*/
Static Function quebraString(cDescricao,nTamnhoLinha)
	Local nLinhas			:= 0	as numeric
	Local nRecord			:= 0	as numeric
	Local aRet				:= {}	as array

	Default cDescricao		:= ""
	Default nTamnhoLinha	:= 0

	If !Empty(cDescricao)
		nLinhas := MLCount(cDescricao,nTamnhoLinha)
		For nRecord := 1 To nLinhas
			If ( nRecord <= 2)
				Aadd(aRet,MemoLine(cDescricao,nTamnhoLinha,nRecord))
			Endif
		Next
	Endif

Return aRet

/*
	Executa a Gravação da Etiqueta na Tabela CB0,
*/
Static Function gravaCB0(cDescProduto,cLoteOp,cNumSeq)

	dbSelectArea("CB0")
	CB0->(dbSetOrder(1))

	cCodigoEtiqueta := lib.u_buscaCB0()

	Reclock("CB0",.T.)
	CB0->CB0_FILIAL	:= FwxFilial("CB0")
	CB0->CB0_CODETI	:= cCodigoEtiqueta
	CB0->CB0_DTNASC	:= dDatabase
	CB0->CB0_TIPO  	:= "01"
	CB0->CB0_CODPRO	:= cCodProduto
	CB0->CB0_QTDE  	:= 1
	CB0->CB0_USUARI	:= RetCodUsr()
	CB0->CB0_LOTE  	:= cLoteOp
	CB0->CB0_NUMSEQ	:= cNumSeq
	CB0->CB0_OP    	:= cNumeroOp
	CB0->CB0_PALLET := "0"
	MsUnlock()
Return



Static Function getQuerySH6(nLinha,cCodigoOrdemProducao)

	Local cQuery 	:= ""	as Character
	Local cAlQuery	:= ""	as Character
	Local nCount	:= 0    as numeric

	// Busca as informações SH6
	cQuery := "	SELECT H6_ZQUANT, H6_QTDPROD, H6_ZPESO, H6_ZPESOBT " 	+ CRLF
	cQuery += "		FROM " + RetSqlName("SH6") + " SH6 " 			 	+ CRLF
	cQuery += "	WHERE"											    	+ CRLF
	cQuery += "			H6_FILIAL  = '" + xFilial("SH6") + "' " 		+ CRLF
	cQuery += "		AND H6_OP		 = '" + cCodigoOrdemProducao + "' " + CRLF
	cQuery += "		AND  H6_OPERAC ='02'					   "		+ CRLF
	cQuery += "		AND SH6.D_E_L_E_T_ = ' ' 				   " 		+ CRLF

	cQuery := ChangeQuery(cQuery)
	cAlQuery := MPSysOpenQuery(cQuery)

	While !(cAlQuery)->(Eof())
		nCount++

		If nCount == nLinha
			iF (cAlQuery)->H6_ZQUANT > 0
				nQuant := (cAlQuery)->H6_ZQUANT
			Else
				nQuant := (cAlQuery)->H6_QTDPROD
			EndIf

			iF (cAlQuery)->H6_ZPESO > 0
				nPeso := (cAlQuery)->H6_ZPESO
			Else
				nPeso := (cAlQuery)->H6_ZPESOBT
			EndIf
			EXIT
		EndIf
		(cAlQuery)->(DbSkip())

	EndDo

	(cAlQuery)->(DbCloseArea())
	//******************************************************************************************************

Return .T.
